//go:build !ignore_autogenerated
// +build !ignore_autogenerated

package v1alpha1

import (
	"encoding/json"

	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto implements deepcopy for DatabaseCluster
func (in *DatabaseCluster) DeepCopyInto(out *DatabaseCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ObjectMeta = *in.ObjectMeta.DeepCopy()
	if in.Spec != nil {
		out.Spec = in.Spec.DeepCopy()
	}
	if in.Status != nil {
		out.Status = in.Status.DeepCopy()
	}
}

// DeepCopy implements deepcopy for DatabaseCluster
func (in *DatabaseCluster) DeepCopy() *DatabaseCluster {
	if in == nil {
		return nil
	}
	out := new(DatabaseCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object interface
func (in *DatabaseCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto implements deepcopy for DatabaseClusterList
func (in *DatabaseClusterList) DeepCopyInto(out *DatabaseClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = *in.ListMeta.DeepCopy()
	if in.Items != nil {
		out.Items = make([]DatabaseCluster, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

// DeepCopy implements deepcopy for DatabaseClusterList
func (in *DatabaseClusterList) DeepCopy() *DatabaseClusterList {
	if in == nil {
		return nil
	}
	out := new(DatabaseClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object interface
func (in *DatabaseClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto implements deepcopy for TLSSpec
func (in *TLSSpec) DeepCopyInto(out *TLSSpec) {
	*out = *in
	if in.CASecretRef != nil {
		out.CASecretRef = in.CASecretRef.DeepCopy()
	}
	if in.ServerCertSecretRef != nil {
		out.ServerCertSecretRef = in.ServerCertSecretRef.DeepCopy()
	}
	if in.ClientCertSecretRef != nil {
		out.ClientCertSecretRef = in.ClientCertSecretRef.DeepCopy()
	}
}

// DeepCopy implements deepcopy for TLSSpec
func (in *TLSSpec) DeepCopy() *TLSSpec {
	if in == nil {
		return nil
	}
	out := new(TLSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto implements deepcopy for DatabaseClusterSpec
func (in *DatabaseClusterSpec) DeepCopyInto(out *DatabaseClusterSpec) {
	if in == nil {
		return
	}
	b, err := json.Marshal(in)
	if err != nil {
		*out = *in
		return
	}
	_ = json.Unmarshal(b, out)
}

// DeepCopy implements deepcopy for DatabaseClusterSpec
func (in *DatabaseClusterSpec) DeepCopy() *DatabaseClusterSpec {
	if in == nil {
		return nil
	}
	out := new(DatabaseClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto implements deepcopy for DatabaseClusterStatus
func (in *DatabaseClusterStatus) DeepCopyInto(out *DatabaseClusterStatus) {
	if in == nil {
		return
	}
	b, err := json.Marshal(in)
	if err != nil {
		*out = *in
		return
	}
	_ = json.Unmarshal(b, out)
}

// DeepCopy implements deepcopy for DatabaseClusterStatus
func (in *DatabaseClusterStatus) DeepCopy() *DatabaseClusterStatus {
	if in == nil {
		return nil
	}
	out := new(DatabaseClusterStatus)
	in.DeepCopyInto(out)
	return out
}
