//go:build !ignore_autogenerated

// Copyright (C) 2026 The OpenEverest Contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"

	commonv1alpha1 "github.com/openeverest/openeverest/v2/api/common/v1alpha1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialsSchema) DeepCopyInto(out *CredentialsSchema) {
	*out = *in
	if in.Required != nil {
		in, out := &in.Required, &out.Required
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialsSchema.
func (in *CredentialsSchema) DeepCopy() *CredentialsSchema {
	if in == nil {
		return nil
	}
	out := new(CredentialsSchema)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtensionManagedFulfilment) DeepCopyInto(out *ExtensionManagedFulfilment) {
	*out = *in
	in.Requires.DeepCopyInto(&out.Requires)
	if in.Degrades != nil {
		in, out := &in.Degrades, &out.Degrades
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtensionManagedFulfilment.
func (in *ExtensionManagedFulfilment) DeepCopy() *ExtensionManagedFulfilment {
	if in == nil {
		return nil
	}
	out := new(ExtensionManagedFulfilment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringBinding) DeepCopyInto(out *MonitoringBinding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringBinding.
func (in *MonitoringBinding) DeepCopy() *MonitoringBinding {
	if in == nil {
		return nil
	}
	out := new(MonitoringBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MonitoringBinding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringBindingList) DeepCopyInto(out *MonitoringBindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MonitoringBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringBindingList.
func (in *MonitoringBindingList) DeepCopy() *MonitoringBindingList {
	if in == nil {
		return nil
	}
	out := new(MonitoringBindingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MonitoringBindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringBindingSpec) DeepCopyInto(out *MonitoringBindingSpec) {
	*out = *in
	out.InstanceRef = in.InstanceRef
	out.DestinationRef = in.DestinationRef
	if in.ClassRef != nil {
		in, out := &in.ClassRef, &out.ClassRef
		*out = new(commonv1alpha1.ObjectRef)
		**out = **in
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringBindingSpec.
func (in *MonitoringBindingSpec) DeepCopy() *MonitoringBindingSpec {
	if in == nil {
		return nil
	}
	out := new(MonitoringBindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringBindingStatus) DeepCopyInto(out *MonitoringBindingStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringBindingStatus.
func (in *MonitoringBindingStatus) DeepCopy() *MonitoringBindingStatus {
	if in == nil {
		return nil
	}
	out := new(MonitoringBindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringClass) DeepCopyInto(out *MonitoringClass) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringClass.
func (in *MonitoringClass) DeepCopy() *MonitoringClass {
	if in == nil {
		return nil
	}
	out := new(MonitoringClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MonitoringClass) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringClassList) DeepCopyInto(out *MonitoringClassList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MonitoringClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringClassList.
func (in *MonitoringClassList) DeepCopy() *MonitoringClassList {
	if in == nil {
		return nil
	}
	out := new(MonitoringClassList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MonitoringClassList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringClassSpec) DeepCopyInto(out *MonitoringClassSpec) {
	*out = *in
	if in.ProviderManaged != nil {
		in, out := &in.ProviderManaged, &out.ProviderManaged
		*out = new(ProviderManagedFulfilment)
		(*in).DeepCopyInto(*out)
	}
	if in.ExtensionManaged != nil {
		in, out := &in.ExtensionManaged, &out.ExtensionManaged
		*out = new(ExtensionManagedFulfilment)
		(*in).DeepCopyInto(*out)
	}
	if in.DestinationParametersSchema != nil {
		in, out := &in.DestinationParametersSchema, &out.DestinationParametersSchema
		*out = new(commonv1alpha1.ParametersSchema)
		(*in).DeepCopyInto(*out)
	}
	if in.InstanceParametersSchema != nil {
		in, out := &in.InstanceParametersSchema, &out.InstanceParametersSchema
		*out = new(commonv1alpha1.ParametersSchema)
		(*in).DeepCopyInto(*out)
	}
	if in.CredentialsSchema != nil {
		in, out := &in.CredentialsSchema, &out.CredentialsSchema
		*out = new(CredentialsSchema)
		(*in).DeepCopyInto(*out)
	}
	if in.UISchema != nil {
		in, out := &in.UISchema, &out.UISchema
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringClassSpec.
func (in *MonitoringClassSpec) DeepCopy() *MonitoringClassSpec {
	if in == nil {
		return nil
	}
	out := new(MonitoringClassSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringClassStatus) DeepCopyInto(out *MonitoringClassStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringClassStatus.
func (in *MonitoringClassStatus) DeepCopy() *MonitoringClassStatus {
	if in == nil {
		return nil
	}
	out := new(MonitoringClassStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringConfig) DeepCopyInto(out *MonitoringConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringConfig.
func (in *MonitoringConfig) DeepCopy() *MonitoringConfig {
	if in == nil {
		return nil
	}
	out := new(MonitoringConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MonitoringConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringConfigList) DeepCopyInto(out *MonitoringConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MonitoringConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringConfigList.
func (in *MonitoringConfigList) DeepCopy() *MonitoringConfigList {
	if in == nil {
		return nil
	}
	out := new(MonitoringConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MonitoringConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringConfigSpec) DeepCopyInto(out *MonitoringConfigSpec) {
	*out = *in
	if in.PMM != nil {
		in, out := &in.PMM, &out.PMM
		*out = new(PMMMonitoringSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringConfigSpec.
func (in *MonitoringConfigSpec) DeepCopy() *MonitoringConfigSpec {
	if in == nil {
		return nil
	}
	out := new(MonitoringConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringConfigStatus) DeepCopyInto(out *MonitoringConfigStatus) {
	*out = *in
	if in.PMM != nil {
		in, out := &in.PMM, &out.PMM
		*out = new(PMMMonitoringStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringConfigStatus.
func (in *MonitoringConfigStatus) DeepCopy() *MonitoringConfigStatus {
	if in == nil {
		return nil
	}
	out := new(MonitoringConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringDestination) DeepCopyInto(out *MonitoringDestination) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringDestination.
func (in *MonitoringDestination) DeepCopy() *MonitoringDestination {
	if in == nil {
		return nil
	}
	out := new(MonitoringDestination)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MonitoringDestination) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringDestinationList) DeepCopyInto(out *MonitoringDestinationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MonitoringDestination, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringDestinationList.
func (in *MonitoringDestinationList) DeepCopy() *MonitoringDestinationList {
	if in == nil {
		return nil
	}
	out := new(MonitoringDestinationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MonitoringDestinationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringDestinationSpec) DeepCopyInto(out *MonitoringDestinationSpec) {
	*out = *in
	out.ClassRef = in.ClassRef
	if in.CredentialsSecretRef != nil {
		in, out := &in.CredentialsSecretRef, &out.CredentialsSecretRef
		*out = new(commonv1alpha1.SecretRef)
		**out = **in
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringDestinationSpec.
func (in *MonitoringDestinationSpec) DeepCopy() *MonitoringDestinationSpec {
	if in == nil {
		return nil
	}
	out := new(MonitoringDestinationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringDestinationStatus) DeepCopyInto(out *MonitoringDestinationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringDestinationStatus.
func (in *MonitoringDestinationStatus) DeepCopy() *MonitoringDestinationStatus {
	if in == nil {
		return nil
	}
	out := new(MonitoringDestinationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PMMMonitoringSpec) DeepCopyInto(out *PMMMonitoringSpec) {
	*out = *in
	out.CredentialsSecretRef = in.CredentialsSecretRef
	if in.VerifyTLS != nil {
		in, out := &in.VerifyTLS, &out.VerifyTLS
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PMMMonitoringSpec.
func (in *PMMMonitoringSpec) DeepCopy() *PMMMonitoringSpec {
	if in == nil {
		return nil
	}
	out := new(PMMMonitoringSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PMMMonitoringStatus) DeepCopyInto(out *PMMMonitoringStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PMMMonitoringStatus.
func (in *PMMMonitoringStatus) DeepCopy() *PMMMonitoringStatus {
	if in == nil {
		return nil
	}
	out := new(PMMMonitoringStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderManagedFulfilment) DeepCopyInto(out *ProviderManagedFulfilment) {
	*out = *in
	if in.Features != nil {
		in, out := &in.Features, &out.Features
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderManagedFulfilment.
func (in *ProviderManagedFulfilment) DeepCopy() *ProviderManagedFulfilment {
	if in == nil {
		return nil
	}
	out := new(ProviderManagedFulfilment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceRequirements) DeepCopyInto(out *SourceRequirements) {
	*out = *in
	if in.Kinds != nil {
		in, out := &in.Kinds, &out.Kinds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CredentialProfiles != nil {
		in, out := &in.CredentialProfiles, &out.CredentialProfiles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Features != nil {
		in, out := &in.Features, &out.Features
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceRequirements.
func (in *SourceRequirements) DeepCopy() *SourceRequirements {
	if in == nil {
		return nil
	}
	out := new(SourceRequirements)
	in.DeepCopyInto(out)
	return out
}
