apiVersion: v1
data:
  AWS_ACCESS_KEY_ID: bWluaW9hZG1pbg==
  AWS_SECRET_ACCESS_KEY: bWluaW9hZG1pbg==
kind: Secret
type: Opaque
---
apiVersion: backup.openeverest.io/v1alpha1
kind: BackupStorage
spec:
  type: s3
  s3:
    endpointURL: https://minio.minio.svc.cluster.local
    forcePathStyle: true
    region: us-east-1
    verifyTLS: false
