apiVersion: v1
data:
  AWS_ACCESS_KEY_ID: c2Vhd2VlZGZzYWRtaW4=
  AWS_SECRET_ACCESS_KEY: c2Vhd2VlZGZzYWRtaW4=
kind: Secret
type: Opaque
---
apiVersion: everest.percona.com/v1alpha1
kind: BackupStorage
spec:
  endpointURL: https://seaweedfs.seaweedfs.svc.cluster.local
  forcePathStyle: true
  region: us-east-1
  type: s3
  verifyTLS: false
