apiVersion: core.openeverest.io/v1alpha1
kind: NamespaceDefaults
metadata:
  labels:
    app.kubernetes.io/name: openeverest
    app.kubernetes.io/managed-by: kustomize
  name: namespacedefaults-sample
spec:
  # TODO(user): Add fields here
