apiVersion: core.openeverest.io/v1alpha1
kind: Preset
metadata:
  labels:
    app.kubernetes.io/name: openeverest
    app.kubernetes.io/managed-by: kustomize
  name: preset-sample
spec:
  # TODO(user): Add fields here
