// Code generated by mockery v2.53.5. DO NOT EDIT.

package handlers

import (
	context "context"

	api "github.com/openeverest/openeverest/v2/internal/server/api"

	corev1alpha1 "github.com/openeverest/openeverest/v2/api/core/v1alpha1"

	mock "github.com/stretchr/testify/mock"

	monitoringv1alpha1 "github.com/openeverest/openeverest/v2/api/monitoring/v1alpha1"

	v1alpha1 "github.com/openeverest/openeverest/v2/api/backup/v1alpha1"
)

// MockHandler is an autogenerated mock type for the Handler type
type MockHandler struct {
	mock.Mock
}

// CreateBackup provides a mock function with given fields: ctx, cluster, backup
func (_m *MockHandler) CreateBackup(ctx context.Context, cluster string, backup *v1alpha1.Backup) (*v1alpha1.Backup, error) {
	ret := _m.Called(ctx, cluster, backup)

	if len(ret) == 0 {
		panic("no return value specified for CreateBackup")
	}

	var r0 *v1alpha1.Backup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.Backup) (*v1alpha1.Backup, error)); ok {
		return rf(ctx, cluster, backup)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.Backup) *v1alpha1.Backup); ok {
		r0 = rf(ctx, cluster, backup)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.Backup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *v1alpha1.Backup) error); ok {
		r1 = rf(ctx, cluster, backup)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateBackupStorage provides a mock function with given fields: ctx, cluster, bs
func (_m *MockHandler) CreateBackupStorage(ctx context.Context, cluster string, bs *v1alpha1.BackupStorage) (*v1alpha1.BackupStorage, error) {
	ret := _m.Called(ctx, cluster, bs)

	if len(ret) == 0 {
		panic("no return value specified for CreateBackupStorage")
	}

	var r0 *v1alpha1.BackupStorage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.BackupStorage) (*v1alpha1.BackupStorage, error)); ok {
		return rf(ctx, cluster, bs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.BackupStorage) *v1alpha1.BackupStorage); ok {
		r0 = rf(ctx, cluster, bs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.BackupStorage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *v1alpha1.BackupStorage) error); ok {
		r1 = rf(ctx, cluster, bs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateInstance provides a mock function with given fields: ctx, cluster, instance
func (_m *MockHandler) CreateInstance(ctx context.Context, cluster string, instance *corev1alpha1.Instance) (*corev1alpha1.Instance, error) {
	ret := _m.Called(ctx, cluster, instance)

	if len(ret) == 0 {
		panic("no return value specified for CreateInstance")
	}

	var r0 *corev1alpha1.Instance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *corev1alpha1.Instance) (*corev1alpha1.Instance, error)); ok {
		return rf(ctx, cluster, instance)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *corev1alpha1.Instance) *corev1alpha1.Instance); ok {
		r0 = rf(ctx, cluster, instance)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*corev1alpha1.Instance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *corev1alpha1.Instance) error); ok {
		r1 = rf(ctx, cluster, instance)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateMonitoringConfig provides a mock function with given fields: ctx, cluster, namespace, req
func (_m *MockHandler) CreateMonitoringConfig(ctx context.Context, cluster string, namespace string, req *api.MonitoringConfigCreateParams) (*monitoringv1alpha1.MonitoringConfig, error) {
	ret := _m.Called(ctx, cluster, namespace, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateMonitoringConfig")
	}

	var r0 *monitoringv1alpha1.MonitoringConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *api.MonitoringConfigCreateParams) (*monitoringv1alpha1.MonitoringConfig, error)); ok {
		return rf(ctx, cluster, namespace, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *api.MonitoringConfigCreateParams) *monitoringv1alpha1.MonitoringConfig); ok {
		r0 = rf(ctx, cluster, namespace, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*monitoringv1alpha1.MonitoringConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *api.MonitoringConfigCreateParams) error); ok {
		r1 = rf(ctx, cluster, namespace, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateRestore provides a mock function with given fields: ctx, restore
func (_m *MockHandler) CreateRestore(ctx context.Context, restore *v1alpha1.Restore) (*v1alpha1.Restore, error) {
	ret := _m.Called(ctx, restore)

	if len(ret) == 0 {
		panic("no return value specified for CreateRestore")
	}

	var r0 *v1alpha1.Restore
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1alpha1.Restore) (*v1alpha1.Restore, error)); ok {
		return rf(ctx, restore)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1alpha1.Restore) *v1alpha1.Restore); ok {
		r0 = rf(ctx, restore)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.Restore)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1alpha1.Restore) error); ok {
		r1 = rf(ctx, restore)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteBackup provides a mock function with given fields: ctx, cluster, namespace, name, params
func (_m *MockHandler) DeleteBackup(ctx context.Context, cluster string, namespace string, name string, params *api.DeleteBackupParams) error {
	ret := _m.Called(ctx, cluster, namespace, name, params)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBackup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, *api.DeleteBackupParams) error); ok {
		r0 = rf(ctx, cluster, namespace, name, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteBackupStorage provides a mock function with given fields: ctx, cluster, namespace, name
func (_m *MockHandler) DeleteBackupStorage(ctx context.Context, cluster string, namespace string, name string) error {
	ret := _m.Called(ctx, cluster, namespace, name)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBackupStorage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, cluster, namespace, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteInstance provides a mock function with given fields: ctx, cluster, namespace, name, params
func (_m *MockHandler) DeleteInstance(ctx context.Context, cluster string, namespace string, name string, params *api.DeleteInstanceParams) error {
	ret := _m.Called(ctx, cluster, namespace, name, params)

	if len(ret) == 0 {
		panic("no return value specified for DeleteInstance")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, *api.DeleteInstanceParams) error); ok {
		r0 = rf(ctx, cluster, namespace, name, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteMonitoringConfig provides a mock function with given fields: ctx, cluster, namespace, name
func (_m *MockHandler) DeleteMonitoringConfig(ctx context.Context, cluster string, namespace string, name string) error {
	ret := _m.Called(ctx, cluster, namespace, name)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMonitoringConfig")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, cluster, namespace, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteRestore provides a mock function with given fields: ctx, namespace, name
func (_m *MockHandler) DeleteRestore(ctx context.Context, namespace string, name string) error {
	ret := _m.Called(ctx, namespace, name)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRestore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, namespace, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBackup provides a mock function with given fields: ctx, cluster, namespace, name
func (_m *MockHandler) GetBackup(ctx context.Context, cluster string, namespace string, name string) (*v1alpha1.Backup, error) {
	ret := _m.Called(ctx, cluster, namespace, name)

	if len(ret) == 0 {
		panic("no return value specified for GetBackup")
	}

	var r0 *v1alpha1.Backup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*v1alpha1.Backup, error)); ok {
		return rf(ctx, cluster, namespace, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *v1alpha1.Backup); ok {
		r0 = rf(ctx, cluster, namespace, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.Backup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, cluster, namespace, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBackupClass provides a mock function with given fields: ctx, cluster, name
func (_m *MockHandler) GetBackupClass(ctx context.Context, cluster string, name string) (*v1alpha1.BackupClass, error) {
	ret := _m.Called(ctx, cluster, name)

	if len(ret) == 0 {
		panic("no return value specified for GetBackupClass")
	}

	var r0 *v1alpha1.BackupClass
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*v1alpha1.BackupClass, error)); ok {
		return rf(ctx, cluster, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *v1alpha1.BackupClass); ok {
		r0 = rf(ctx, cluster, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.BackupClass)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, cluster, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBackupStorage provides a mock function with given fields: ctx, cluster, namespace, name
func (_m *MockHandler) GetBackupStorage(ctx context.Context, cluster string, namespace string, name string) (*v1alpha1.BackupStorage, error) {
	ret := _m.Called(ctx, cluster, namespace, name)

	if len(ret) == 0 {
		panic("no return value specified for GetBackupStorage")
	}

	var r0 *v1alpha1.BackupStorage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*v1alpha1.BackupStorage, error)); ok {
		return rf(ctx, cluster, namespace, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *v1alpha1.BackupStorage); ok {
		r0 = rf(ctx, cluster, namespace, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.BackupStorage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, cluster, namespace, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCluster provides a mock function with given fields: ctx, name
func (_m *MockHandler) GetCluster(ctx context.Context, name string) (*api.Cluster, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetCluster")
	}

	var r0 *api.Cluster
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*api.Cluster, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *api.Cluster); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.Cluster)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetInstance provides a mock function with given fields: ctx, cluster, namespace, name
func (_m *MockHandler) GetInstance(ctx context.Context, cluster string, namespace string, name string) (*corev1alpha1.Instance, error) {
	ret := _m.Called(ctx, cluster, namespace, name)

	if len(ret) == 0 {
		panic("no return value specified for GetInstance")
	}

	var r0 *corev1alpha1.Instance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*corev1alpha1.Instance, error)); ok {
		return rf(ctx, cluster, namespace, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *corev1alpha1.Instance); ok {
		r0 = rf(ctx, cluster, namespace, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*corev1alpha1.Instance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, cluster, namespace, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetInstanceConnection provides a mock function with given fields: ctx, cluster, namespace, name
func (_m *MockHandler) GetInstanceConnection(ctx context.Context, cluster string, namespace string, name string) (*api.InstanceConnectionDetails, error) {
	ret := _m.Called(ctx, cluster, namespace, name)

	if len(ret) == 0 {
		panic("no return value specified for GetInstanceConnection")
	}

	var r0 *api.InstanceConnectionDetails
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*api.InstanceConnectionDetails, error)); ok {
		return rf(ctx, cluster, namespace, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *api.InstanceConnectionDetails); ok {
		r0 = rf(ctx, cluster, namespace, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.InstanceConnectionDetails)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, cluster, namespace, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetKubernetesClusterInfo provides a mock function with given fields: ctx
func (_m *MockHandler) GetKubernetesClusterInfo(ctx context.Context) (*api.KubernetesClusterInfo, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetKubernetesClusterInfo")
	}

	var r0 *api.KubernetesClusterInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*api.KubernetesClusterInfo, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *api.KubernetesClusterInfo); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.KubernetesClusterInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetKubernetesClusterResources provides a mock function with given fields: ctx
func (_m *MockHandler) GetKubernetesClusterResources(ctx context.Context) (*api.KubernetesClusterResources, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetKubernetesClusterResources")
	}

	var r0 *api.KubernetesClusterResources
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*api.KubernetesClusterResources, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *api.KubernetesClusterResources); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.KubernetesClusterResources)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMonitoringConfig provides a mock function with given fields: ctx, cluster, namespace, name
func (_m *MockHandler) GetMonitoringConfig(ctx context.Context, cluster string, namespace string, name string) (*monitoringv1alpha1.MonitoringConfig, error) {
	ret := _m.Called(ctx, cluster, namespace, name)

	if len(ret) == 0 {
		panic("no return value specified for GetMonitoringConfig")
	}

	var r0 *monitoringv1alpha1.MonitoringConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*monitoringv1alpha1.MonitoringConfig, error)); ok {
		return rf(ctx, cluster, namespace, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *monitoringv1alpha1.MonitoringConfig); ok {
		r0 = rf(ctx, cluster, namespace, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*monitoringv1alpha1.MonitoringConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, cluster, namespace, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProvider provides a mock function with given fields: ctx, cluster, name
func (_m *MockHandler) GetProvider(ctx context.Context, cluster string, name string) (*corev1alpha1.Provider, error) {
	ret := _m.Called(ctx, cluster, name)

	if len(ret) == 0 {
		panic("no return value specified for GetProvider")
	}

	var r0 *corev1alpha1.Provider
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*corev1alpha1.Provider, error)); ok {
		return rf(ctx, cluster, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *corev1alpha1.Provider); ok {
		r0 = rf(ctx, cluster, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*corev1alpha1.Provider)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, cluster, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRestore provides a mock function with given fields: ctx, namespace, name
func (_m *MockHandler) GetRestore(ctx context.Context, namespace string, name string) (*v1alpha1.Restore, error) {
	ret := _m.Called(ctx, namespace, name)

	if len(ret) == 0 {
		panic("no return value specified for GetRestore")
	}

	var r0 *v1alpha1.Restore
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*v1alpha1.Restore, error)); ok {
		return rf(ctx, namespace, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *v1alpha1.Restore); ok {
		r0 = rf(ctx, namespace, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.Restore)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, namespace, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSettings provides a mock function with given fields: ctx
func (_m *MockHandler) GetSettings(ctx context.Context) (*api.Settings, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetSettings")
	}

	var r0 *api.Settings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*api.Settings, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *api.Settings); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.Settings)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserPermissions provides a mock function with given fields: ctx
func (_m *MockHandler) GetUserPermissions(ctx context.Context) (*api.UserPermissions, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetUserPermissions")
	}

	var r0 *api.UserPermissions
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*api.UserPermissions, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *api.UserPermissions); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.UserPermissions)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListBackupClasses provides a mock function with given fields: ctx, cluster
func (_m *MockHandler) ListBackupClasses(ctx context.Context, cluster string) (*v1alpha1.BackupClassList, error) {
	ret := _m.Called(ctx, cluster)

	if len(ret) == 0 {
		panic("no return value specified for ListBackupClasses")
	}

	var r0 *v1alpha1.BackupClassList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*v1alpha1.BackupClassList, error)); ok {
		return rf(ctx, cluster)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *v1alpha1.BackupClassList); ok {
		r0 = rf(ctx, cluster)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.BackupClassList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, cluster)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListBackupStorages provides a mock function with given fields: ctx, cluster, namespace
func (_m *MockHandler) ListBackupStorages(ctx context.Context, cluster string, namespace string) (*v1alpha1.BackupStorageList, error) {
	ret := _m.Called(ctx, cluster, namespace)

	if len(ret) == 0 {
		panic("no return value specified for ListBackupStorages")
	}

	var r0 *v1alpha1.BackupStorageList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*v1alpha1.BackupStorageList, error)); ok {
		return rf(ctx, cluster, namespace)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *v1alpha1.BackupStorageList); ok {
		r0 = rf(ctx, cluster, namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.BackupStorageList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, cluster, namespace)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListClusters provides a mock function with given fields: ctx
func (_m *MockHandler) ListClusters(ctx context.Context) (*api.ClusterList, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListClusters")
	}

	var r0 *api.ClusterList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*api.ClusterList, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *api.ClusterList); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.ClusterList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListInstanceBackups provides a mock function with given fields: ctx, cluster, namespace, instance
func (_m *MockHandler) ListInstanceBackups(ctx context.Context, cluster string, namespace string, instance string) (*v1alpha1.BackupList, error) {
	ret := _m.Called(ctx, cluster, namespace, instance)

	if len(ret) == 0 {
		panic("no return value specified for ListInstanceBackups")
	}

	var r0 *v1alpha1.BackupList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*v1alpha1.BackupList, error)); ok {
		return rf(ctx, cluster, namespace, instance)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *v1alpha1.BackupList); ok {
		r0 = rf(ctx, cluster, namespace, instance)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.BackupList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, cluster, namespace, instance)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListInstanceRestores provides a mock function with given fields: ctx, cluster, namespace, instanceName
func (_m *MockHandler) ListInstanceRestores(ctx context.Context, cluster string, namespace string, instanceName string) (*v1alpha1.RestoreList, error) {
	ret := _m.Called(ctx, cluster, namespace, instanceName)

	if len(ret) == 0 {
		panic("no return value specified for ListInstanceRestores")
	}

	var r0 *v1alpha1.RestoreList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*v1alpha1.RestoreList, error)); ok {
		return rf(ctx, cluster, namespace, instanceName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *v1alpha1.RestoreList); ok {
		r0 = rf(ctx, cluster, namespace, instanceName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.RestoreList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, cluster, namespace, instanceName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListInstances provides a mock function with given fields: ctx, cluster, namespace
func (_m *MockHandler) ListInstances(ctx context.Context, cluster string, namespace string) (*corev1alpha1.InstanceList, error) {
	ret := _m.Called(ctx, cluster, namespace)

	if len(ret) == 0 {
		panic("no return value specified for ListInstances")
	}

	var r0 *corev1alpha1.InstanceList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*corev1alpha1.InstanceList, error)); ok {
		return rf(ctx, cluster, namespace)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *corev1alpha1.InstanceList); ok {
		r0 = rf(ctx, cluster, namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*corev1alpha1.InstanceList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, cluster, namespace)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListMonitoringConfigs provides a mock function with given fields: ctx, cluster, namespaces
func (_m *MockHandler) ListMonitoringConfigs(ctx context.Context, cluster string, namespaces string) (*monitoringv1alpha1.MonitoringConfigList, error) {
	ret := _m.Called(ctx, cluster, namespaces)

	if len(ret) == 0 {
		panic("no return value specified for ListMonitoringConfigs")
	}

	var r0 *monitoringv1alpha1.MonitoringConfigList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*monitoringv1alpha1.MonitoringConfigList, error)); ok {
		return rf(ctx, cluster, namespaces)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *monitoringv1alpha1.MonitoringConfigList); ok {
		r0 = rf(ctx, cluster, namespaces)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*monitoringv1alpha1.MonitoringConfigList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, cluster, namespaces)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListNamespaces provides a mock function with given fields: ctx, cluster
func (_m *MockHandler) ListNamespaces(ctx context.Context, cluster string) ([]string, error) {
	ret := _m.Called(ctx, cluster)

	if len(ret) == 0 {
		panic("no return value specified for ListNamespaces")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return rf(ctx, cluster)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = rf(ctx, cluster)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, cluster)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListProviders provides a mock function with given fields: ctx, cluster
func (_m *MockHandler) ListProviders(ctx context.Context, cluster string) (*corev1alpha1.ProviderList, error) {
	ret := _m.Called(ctx, cluster)

	if len(ret) == 0 {
		panic("no return value specified for ListProviders")
	}

	var r0 *corev1alpha1.ProviderList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*corev1alpha1.ProviderList, error)); ok {
		return rf(ctx, cluster)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *corev1alpha1.ProviderList); ok {
		r0 = rf(ctx, cluster)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*corev1alpha1.ProviderList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, cluster)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetNext provides a mock function with given fields: h
func (_m *MockHandler) SetNext(h Handler) {
	_m.Called(h)
}

// UpdateBackupStorage provides a mock function with given fields: ctx, cluster, bs
func (_m *MockHandler) UpdateBackupStorage(ctx context.Context, cluster string, bs *v1alpha1.BackupStorage) (*v1alpha1.BackupStorage, error) {
	ret := _m.Called(ctx, cluster, bs)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBackupStorage")
	}

	var r0 *v1alpha1.BackupStorage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.BackupStorage) (*v1alpha1.BackupStorage, error)); ok {
		return rf(ctx, cluster, bs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.BackupStorage) *v1alpha1.BackupStorage); ok {
		r0 = rf(ctx, cluster, bs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.BackupStorage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *v1alpha1.BackupStorage) error); ok {
		r1 = rf(ctx, cluster, bs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateInstance provides a mock function with given fields: ctx, cluster, instance
func (_m *MockHandler) UpdateInstance(ctx context.Context, cluster string, instance *corev1alpha1.Instance) (*corev1alpha1.Instance, error) {
	ret := _m.Called(ctx, cluster, instance)

	if len(ret) == 0 {
		panic("no return value specified for UpdateInstance")
	}

	var r0 *corev1alpha1.Instance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *corev1alpha1.Instance) (*corev1alpha1.Instance, error)); ok {
		return rf(ctx, cluster, instance)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *corev1alpha1.Instance) *corev1alpha1.Instance); ok {
		r0 = rf(ctx, cluster, instance)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*corev1alpha1.Instance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *corev1alpha1.Instance) error); ok {
		r1 = rf(ctx, cluster, instance)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateMonitoringConfig provides a mock function with given fields: ctx, cluster, namespace, name, req
func (_m *MockHandler) UpdateMonitoringConfig(ctx context.Context, cluster string, namespace string, name string, req *api.MonitoringConfigUpdateParams) (*monitoringv1alpha1.MonitoringConfig, error) {
	ret := _m.Called(ctx, cluster, namespace, name, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMonitoringConfig")
	}

	var r0 *monitoringv1alpha1.MonitoringConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, *api.MonitoringConfigUpdateParams) (*monitoringv1alpha1.MonitoringConfig, error)); ok {
		return rf(ctx, cluster, namespace, name, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, *api.MonitoringConfigUpdateParams) *monitoringv1alpha1.MonitoringConfig); ok {
		r0 = rf(ctx, cluster, namespace, name, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*monitoringv1alpha1.MonitoringConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, *api.MonitoringConfigUpdateParams) error); ok {
		r1 = rf(ctx, cluster, namespace, name, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockHandler creates a new instance of MockHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHandler {
	mock := &MockHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
