// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes bearerAuthContextKey = "BearerAuth.Scopes"
)

// Defines values for MonitoringConfigBaseType.
const (
	MonitoringConfigBaseTypePmm MonitoringConfigBaseType = "pmm"
)

// Valid indicates whether the value is a known member of the MonitoringConfigBaseType enum.
func (e MonitoringConfigBaseType) Valid() bool {
	switch e {
	case MonitoringConfigBaseTypePmm:
		return true
	default:
		return false
	}
}

// Defines values for MonitoringConfigBaseWithNameType.
const (
	MonitoringConfigBaseWithNameTypePmm MonitoringConfigBaseWithNameType = "pmm"
)

// Valid indicates whether the value is a known member of the MonitoringConfigBaseWithNameType enum.
func (e MonitoringConfigBaseWithNameType) Valid() bool {
	switch e {
	case MonitoringConfigBaseWithNameTypePmm:
		return true
	default:
		return false
	}
}

// Defines values for MonitoringConfigCreateParamsType.
const (
	MonitoringConfigCreateParamsTypePmm MonitoringConfigCreateParamsType = "pmm"
)

// Valid indicates whether the value is a known member of the MonitoringConfigCreateParamsType enum.
func (e MonitoringConfigCreateParamsType) Valid() bool {
	switch e {
	case MonitoringConfigCreateParamsTypePmm:
		return true
	default:
		return false
	}
}

// Defines values for MonitoringConfigUpdateParamsType.
const (
	MonitoringConfigUpdateParamsTypePmm MonitoringConfigUpdateParamsType = "pmm"
)

// Valid indicates whether the value is a known member of the MonitoringConfigUpdateParamsType enum.
func (e MonitoringConfigUpdateParamsType) Valid() bool {
	switch e {
	case MonitoringConfigUpdateParamsTypePmm:
		return true
	default:
		return false
	}
}

// Defines values for DeleteBackupParamsDeletionPolicy.
const (
	DeleteBackupParamsDeletionPolicyDelete DeleteBackupParamsDeletionPolicy = "Delete"
	DeleteBackupParamsDeletionPolicyRetain DeleteBackupParamsDeletionPolicy = "Retain"
)

// Valid indicates whether the value is a known member of the DeleteBackupParamsDeletionPolicy enum.
func (e DeleteBackupParamsDeletionPolicy) Valid() bool {
	switch e {
	case DeleteBackupParamsDeletionPolicyDelete:
		return true
	case DeleteBackupParamsDeletionPolicyRetain:
		return true
	default:
		return false
	}
}

// Defines values for DeleteInstanceParamsDeletionPolicy.
const (
	DeleteInstanceParamsDeletionPolicyCascade DeleteInstanceParamsDeletionPolicy = "Cascade"
	DeleteInstanceParamsDeletionPolicyOrphan  DeleteInstanceParamsDeletionPolicy = "Orphan"
)

// Valid indicates whether the value is a known member of the DeleteInstanceParamsDeletionPolicy enum.
func (e DeleteInstanceParamsDeletionPolicy) Valid() bool {
	switch e {
	case DeleteInstanceParamsDeletionPolicyCascade:
		return true
	case DeleteInstanceParamsDeletionPolicyOrphan:
		return true
	default:
		return false
	}
}

// Cluster defines model for Cluster.
type Cluster struct {
	Name   string `json:"name"`
	Server string `json:"server"`
}

// ClusterList defines model for ClusterList.
type ClusterList struct {
	Items []Cluster `json:"items"`
}

// Error Error response
type Error struct {
	Message *string `json:"message,omitempty"`
}

// KubernetesClusterInfo kubernetes cluster info
type KubernetesClusterInfo struct {
	ClusterType string `json:"clusterType"`

	// StorageClassNames List of storage class names that are available in the cluster.
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	StorageClassNames []string        `json:"storageClassNames"`
	StorageClasses    *[]StorageClass `json:"storageClasses,omitempty"`
}

// KubernetesClusterResources kubernetes cluster resources
type KubernetesClusterResources struct {
	Available ResourcesAvailable `json:"available"`
	Capacity  ResourcesCapacity  `json:"capacity"`
}

// ResourcesAvailable defines model for .
type ResourcesAvailable struct {
	CpuMillis   *uint64 `json:"cpuMillis,omitempty"`
	DiskSize    *uint64 `json:"diskSize,omitempty"`
	MemoryBytes *uint64 `json:"memoryBytes,omitempty"`
}

// ResourcesCapacity defines model for .
type ResourcesCapacity struct {
	CpuMillis   *uint64 `json:"cpuMillis,omitempty"`
	DiskSize    *uint64 `json:"diskSize,omitempty"`
	MemoryBytes *uint64 `json:"memoryBytes,omitempty"`
}

// MonitoringConfigBase MonitoringConfigBase contains common fields for monitoring config
type MonitoringConfigBase struct {
	Type MonitoringConfigBaseType `json:"type,omitempty"`
	Url  string                   `json:"url,omitempty"`

	// VerifyTLS VerifyTLS is set to ensure TLS/SSL verification.
	VerifyTLS *bool `json:"verifyTLS,omitempty"`
}

// MonitoringConfigBaseType defines model for MonitoringConfigBase.Type.
type MonitoringConfigBaseType string

// MonitoringConfigBaseWithName defines model for MonitoringConfigBaseWithName.
type MonitoringConfigBaseWithName struct {
	// Name A user defined string name of the storage in the DNS name format https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-label-names
	Name string                           `json:"name,omitempty"`
	Type MonitoringConfigBaseWithNameType `json:"type,omitempty"`
	Url  string                           `json:"url,omitempty"`

	// VerifyTLS VerifyTLS is set to ensure TLS/SSL verification.
	VerifyTLS *bool `json:"verifyTLS,omitempty"`
}

// MonitoringConfigBaseWithNameType defines model for MonitoringConfigBaseWithName.Type.
type MonitoringConfigBaseWithNameType string

// MonitoringConfigCreateParams defines model for MonitoringConfigCreateParams.
type MonitoringConfigCreateParams struct {
	// Name A user defined string name of the storage in the DNS name format https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-label-names
	Name string                           `json:"name,omitempty"`
	Pmm  *MonitoringConfigPMMSpec         `json:"pmm,omitempty"`
	Type MonitoringConfigCreateParamsType `json:"type,omitempty"`
	Url  string                           `json:"url,omitempty"`

	// VerifyTLS VerifyTLS is set to ensure TLS/SSL verification.
	VerifyTLS *bool `json:"verifyTLS,omitempty"`
}

// MonitoringConfigPMMSpec defines model for .
type MonitoringConfigPMMSpec struct {
	ApiKey   string `json:"apiKey,omitempty"`
	Password string `json:"password,omitempty"`
	User     string `json:"user,omitempty"`
}

// MonitoringConfigCreateParamsType defines model for MonitoringConfigCreateParams.Type.
type MonitoringConfigCreateParamsType string

// MonitoringConfigPMM MonitoringConfigPMM contains PMM-specific fields for monitoring config
type MonitoringConfigPMM struct {
	Pmm *MonitoringConfigPMMSpec `json:"pmm,omitempty"`
}

// MonitoringConfigUpdateParams defines model for MonitoringConfigUpdateParams.
type MonitoringConfigUpdateParams struct {
	Pmm  *MonitoringConfigPMMSpec         `json:"pmm,omitempty"`
	Type MonitoringConfigUpdateParamsType `json:"type,omitempty"`
	Url  string                           `json:"url,omitempty"`

	// VerifyTLS VerifyTLS is set to ensure TLS/SSL verification.
	VerifyTLS *bool `json:"verifyTLS,omitempty"`
}

// MonitoringConfigUpdateParamsType defines model for MonitoringConfigUpdateParams.Type.
type MonitoringConfigUpdateParamsType string

// NamespaceList defines model for NamespaceList.
type NamespaceList = []string

// OIDCConfig Everest OIDC provider configuration
type OIDCConfig struct {
	// ClientId OIDC application clientID
	ClientId string `json:"clientId"`

	// IssuerURL OIDC provider url
	IssuerURL string `json:"issuerURL"`

	// Scopes OIDC scopes
	Scopes []string `json:"scopes"`
}

// Settings Everest global settings
type Settings struct {
	// OidcConfig Everest OIDC provider configuration
	OidcConfig OIDCConfig `json:"oidcConfig"`
}

// StorageClass StorageClass describes the parameters for a class of storage for which PersistentVolumes can be dynamically provisioned.
//
// StorageClasses are non-namespaced; the name of the storage class according to etcd is in ObjectMeta.Name.
type StorageClass struct {
	// AllowVolumeExpansion allowVolumeExpansion shows whether the storage class allow volume expand.
	AllowVolumeExpansion *bool `json:"allowVolumeExpansion,omitempty"`

	// Metadata Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
}

// UserCredentials defines model for UserCredentials.
type UserCredentials struct {
	Password *string `json:"password,omitempty"`
	Username *string `json:"username,omitempty"`
}

// UserPermissions defines model for UserPermissions.
type UserPermissions struct {
	Enabled     bool        `json:"enabled"`
	Permissions *[][]string `json:"permissions,omitempty"`
}

// Version Everest version info
type Version struct {
	FullCommit  string `json:"fullCommit"`
	ProjectName string `json:"projectName"`
	Version     string `json:"version"`
}

// bearerAuthContextKey is the context key for BearerAuth security scheme
type bearerAuthContextKey string

// DeleteBackupParams defines parameters for DeleteBackup.
type DeleteBackupParams struct {
	// DeletionPolicy Override the backup's spec.deletionPolicy before deletion.
	// "Delete" (default) removes both the engine backup resource and the data in S3.
	// "Retain" removes the engine backup resource but preserves the data in S3.
	// When omitted, the existing value on the Backup CR is used.
	DeletionPolicy *DeleteBackupParamsDeletionPolicy `form:"deletionPolicy,omitempty" json:"deletionPolicy,omitempty"`
}

// DeleteBackupParamsDeletionPolicy defines parameters for DeleteBackup.
type DeleteBackupParamsDeletionPolicy string

// DeleteInstanceParams defines parameters for DeleteInstance.
type DeleteInstanceParams struct {
	// DeletionPolicy Override the instance's spec.deletionPolicy before deletion.
	// "Cascade" (default) deletes all Backup and Restore CRs referencing this instance.
	// "Orphan" leaves Backup and Restore CRs in place.
	// When omitted, the existing value on the Instance CR is used.
	DeletionPolicy *DeleteInstanceParamsDeletionPolicy `form:"deletionPolicy,omitempty" json:"deletionPolicy,omitempty"`
}

// DeleteInstanceParamsDeletionPolicy defines parameters for DeleteInstance.
type DeleteInstanceParamsDeletionPolicy string

// CreateBackupStorageJSONRequestBody defines body for CreateBackupStorage for application/json ContentType.
type CreateBackupStorageJSONRequestBody = BackupStorage

// UpdateBackupStorageJSONRequestBody defines body for UpdateBackupStorage for application/json ContentType.
type UpdateBackupStorageJSONRequestBody = BackupStorage

// CreateBackupJSONRequestBody defines body for CreateBackup for application/json ContentType.
type CreateBackupJSONRequestBody = Backup

// CreateInstanceJSONRequestBody defines body for CreateInstance for application/json ContentType.
type CreateInstanceJSONRequestBody = Instance

// UpdateInstanceJSONRequestBody defines body for UpdateInstance for application/json ContentType.
type UpdateInstanceJSONRequestBody = Instance

// CreateMonitoringConfigJSONRequestBody defines body for CreateMonitoringConfig for application/json ContentType.
type CreateMonitoringConfigJSONRequestBody = MonitoringConfigCreateParams

// UpdateMonitoringConfigJSONRequestBody defines body for UpdateMonitoringConfig for application/json ContentType.
type UpdateMonitoringConfigJSONRequestBody = MonitoringConfigUpdateParams

// CreateRestoreJSONRequestBody defines body for CreateRestore for application/json ContentType.
type CreateRestoreJSONRequestBody = Restore

// CreateSessionJSONRequestBody defines body for CreateSession for application/json ContentType.
type CreateSessionJSONRequestBody = UserCredentials

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Cluster info
	// (GET /cluster-info)
	GetKubernetesClusterInfo(ctx echo.Context) error
	// List clusters
	// (GET /clusters)
	ListClusters(ctx echo.Context) error
	// List backup classes
	// (GET /clusters/{cluster}/backup-classes)
	ListBackupClasses(ctx echo.Context, cluster string) error
	// Get backup class
	// (GET /clusters/{cluster}/backup-classes/{backupClass})
	GetBackupClass(ctx echo.Context, cluster string, backupClass string) error
	// Managed namespaces
	// (GET /clusters/{cluster}/namespaces)
	ListNamespaces(ctx echo.Context, cluster string) error
	// List backup storages
	// (GET /clusters/{cluster}/namespaces/{namespace}/backup-storages)
	ListBackupStorages(ctx echo.Context, cluster string, namespace string) error
	// Create backup storage
	// (POST /clusters/{cluster}/namespaces/{namespace}/backup-storages)
	CreateBackupStorage(ctx echo.Context, cluster string, namespace string) error
	// Delete backup storage
	// (DELETE /clusters/{cluster}/namespaces/{namespace}/backup-storages/{name})
	DeleteBackupStorage(ctx echo.Context, cluster string, namespace string, name string) error
	// Get backup storage
	// (GET /clusters/{cluster}/namespaces/{namespace}/backup-storages/{name})
	GetBackupStorage(ctx echo.Context, cluster string, namespace string, name string) error
	// Update backup storage
	// (PUT /clusters/{cluster}/namespaces/{namespace}/backup-storages/{name})
	UpdateBackupStorage(ctx echo.Context, cluster string, namespace string, name string) error
	// Create backup
	// (POST /clusters/{cluster}/namespaces/{namespace}/backups)
	CreateBackup(ctx echo.Context, cluster string, namespace string) error
	// Delete backup
	// (DELETE /clusters/{cluster}/namespaces/{namespace}/backups/{backup})
	DeleteBackup(ctx echo.Context, cluster string, namespace string, backup string, params DeleteBackupParams) error
	// Get backup
	// (GET /clusters/{cluster}/namespaces/{namespace}/backups/{backup})
	GetBackup(ctx echo.Context, cluster string, namespace string, backup string) error
	// List instances
	// (GET /clusters/{cluster}/namespaces/{namespace}/instances)
	ListInstances(ctx echo.Context, cluster string, namespace string) error
	// Create instance
	// (POST /clusters/{cluster}/namespaces/{namespace}/instances)
	CreateInstance(ctx echo.Context, cluster string, namespace string) error
	// Delete instance
	// (DELETE /clusters/{cluster}/namespaces/{namespace}/instances/{instance})
	DeleteInstance(ctx echo.Context, cluster string, namespace string, instance string, params DeleteInstanceParams) error
	// Get instance
	// (GET /clusters/{cluster}/namespaces/{namespace}/instances/{instance})
	GetInstance(ctx echo.Context, cluster string, namespace string, instance string) error
	// Update instance
	// (PUT /clusters/{cluster}/namespaces/{namespace}/instances/{instance})
	UpdateInstance(ctx echo.Context, cluster string, namespace string, instance string) error
	// List backups for an instance
	// (GET /clusters/{cluster}/namespaces/{namespace}/instances/{instance}/backups)
	ListInstanceBackups(ctx echo.Context, cluster string, namespace string, instance string) error
	// Get instance connection details
	// (GET /clusters/{cluster}/namespaces/{namespace}/instances/{instance}/connection)
	GetInstanceConnection(ctx echo.Context, cluster string, namespace string, instance string) error
	// List restores performed for an instance
	// (GET /clusters/{cluster}/namespaces/{namespace}/instances/{instance}/restores)
	ListInstanceRestores(ctx echo.Context, cluster string, namespace string, instance string) error
	// List monitoring configs
	// (GET /clusters/{cluster}/namespaces/{namespace}/monitoring-configs)
	ListMonitoringConfigs(ctx echo.Context, cluster string, namespace string) error
	// Create monitoring config
	// (POST /clusters/{cluster}/namespaces/{namespace}/monitoring-configs)
	CreateMonitoringConfig(ctx echo.Context, cluster string, namespace string) error
	// Delete monitoring config
	// (DELETE /clusters/{cluster}/namespaces/{namespace}/monitoring-configs/{name})
	DeleteMonitoringConfig(ctx echo.Context, cluster string, namespace string, name string) error
	// Get monitoring config
	// (GET /clusters/{cluster}/namespaces/{namespace}/monitoring-configs/{name})
	GetMonitoringConfig(ctx echo.Context, cluster string, namespace string, name string) error
	// Update monitoring config
	// (PATCH /clusters/{cluster}/namespaces/{namespace}/monitoring-configs/{name})
	UpdateMonitoringConfig(ctx echo.Context, cluster string, namespace string, name string) error
	// Create restore
	// (POST /clusters/{cluster}/namespaces/{namespace}/restores)
	CreateRestore(ctx echo.Context, cluster string, namespace string) error
	// Delete restore
	// (DELETE /clusters/{cluster}/namespaces/{namespace}/restores/{restore})
	DeleteRestore(ctx echo.Context, cluster string, namespace string, restore string) error
	// Get restore
	// (GET /clusters/{cluster}/namespaces/{namespace}/restores/{restore})
	GetRestore(ctx echo.Context, cluster string, namespace string, restore string) error
	// List providers
	// (GET /clusters/{cluster}/providers)
	ListProviders(ctx echo.Context, cluster string) error
	// Get provider
	// (GET /clusters/{cluster}/providers/{provider})
	GetProvider(ctx echo.Context, cluster string, provider string) error
	// Get cluster
	// (GET /clusters/{name})
	GetCluster(ctx echo.Context, name string) error
	// Get user permissions
	// (GET /permissions)
	GetUserPermissions(ctx echo.Context) error
	// Cluster resources
	// (GET /resources)
	GetKubernetesClusterResources(ctx echo.Context) error
	// Everest API Logout
	// (DELETE /session)
	DeleteSession(ctx echo.Context) error
	// Everest API Login
	// (POST /session)
	CreateSession(ctx echo.Context) error
	// Settings
	// (GET /settings)
	GetSettings(ctx echo.Context) error
	// Version
	// (GET /version)
	VersionInfo(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetKubernetesClusterInfo converts echo context to params.
func (w *ServerInterfaceWrapper) GetKubernetesClusterInfo(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetKubernetesClusterInfo(ctx)
	return err
}

// ListClusters converts echo context to params.
func (w *ServerInterfaceWrapper) ListClusters(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListClusters(ctx)
	return err
}

// ListBackupClasses converts echo context to params.
func (w *ServerInterfaceWrapper) ListBackupClasses(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListBackupClasses(ctx, cluster)
	return err
}

// GetBackupClass converts echo context to params.
func (w *ServerInterfaceWrapper) GetBackupClass(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "backupClass" -------------
	var backupClass string

	err = runtime.BindStyledParameterWithOptions("simple", "backupClass", ctx.Param("backupClass"), &backupClass, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter backupClass: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetBackupClass(ctx, cluster, backupClass)
	return err
}

// ListNamespaces converts echo context to params.
func (w *ServerInterfaceWrapper) ListNamespaces(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListNamespaces(ctx, cluster)
	return err
}

// ListBackupStorages converts echo context to params.
func (w *ServerInterfaceWrapper) ListBackupStorages(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListBackupStorages(ctx, cluster, namespace)
	return err
}

// CreateBackupStorage converts echo context to params.
func (w *ServerInterfaceWrapper) CreateBackupStorage(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateBackupStorage(ctx, cluster, namespace)
	return err
}

// DeleteBackupStorage converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteBackupStorage(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", ctx.Param("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteBackupStorage(ctx, cluster, namespace, name)
	return err
}

// GetBackupStorage converts echo context to params.
func (w *ServerInterfaceWrapper) GetBackupStorage(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", ctx.Param("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetBackupStorage(ctx, cluster, namespace, name)
	return err
}

// UpdateBackupStorage converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateBackupStorage(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", ctx.Param("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateBackupStorage(ctx, cluster, namespace, name)
	return err
}

// CreateBackup converts echo context to params.
func (w *ServerInterfaceWrapper) CreateBackup(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateBackup(ctx, cluster, namespace)
	return err
}

// DeleteBackup converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteBackup(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	// ------------- Path parameter "backup" -------------
	var backup string

	err = runtime.BindStyledParameterWithOptions("simple", "backup", ctx.Param("backup"), &backup, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter backup: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteBackupParams
	// ------------- Optional query parameter "deletionPolicy" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "deletionPolicy", ctx.QueryParams(), &params.DeletionPolicy, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter deletionPolicy: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteBackup(ctx, cluster, namespace, backup, params)
	return err
}

// GetBackup converts echo context to params.
func (w *ServerInterfaceWrapper) GetBackup(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	// ------------- Path parameter "backup" -------------
	var backup string

	err = runtime.BindStyledParameterWithOptions("simple", "backup", ctx.Param("backup"), &backup, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter backup: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetBackup(ctx, cluster, namespace, backup)
	return err
}

// ListInstances converts echo context to params.
func (w *ServerInterfaceWrapper) ListInstances(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListInstances(ctx, cluster, namespace)
	return err
}

// CreateInstance converts echo context to params.
func (w *ServerInterfaceWrapper) CreateInstance(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateInstance(ctx, cluster, namespace)
	return err
}

// DeleteInstance converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteInstance(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	// ------------- Path parameter "instance" -------------
	var instance string

	err = runtime.BindStyledParameterWithOptions("simple", "instance", ctx.Param("instance"), &instance, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter instance: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteInstanceParams
	// ------------- Optional query parameter "deletionPolicy" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "deletionPolicy", ctx.QueryParams(), &params.DeletionPolicy, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter deletionPolicy: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteInstance(ctx, cluster, namespace, instance, params)
	return err
}

// GetInstance converts echo context to params.
func (w *ServerInterfaceWrapper) GetInstance(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	// ------------- Path parameter "instance" -------------
	var instance string

	err = runtime.BindStyledParameterWithOptions("simple", "instance", ctx.Param("instance"), &instance, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter instance: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetInstance(ctx, cluster, namespace, instance)
	return err
}

// UpdateInstance converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateInstance(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	// ------------- Path parameter "instance" -------------
	var instance string

	err = runtime.BindStyledParameterWithOptions("simple", "instance", ctx.Param("instance"), &instance, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter instance: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateInstance(ctx, cluster, namespace, instance)
	return err
}

// ListInstanceBackups converts echo context to params.
func (w *ServerInterfaceWrapper) ListInstanceBackups(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	// ------------- Path parameter "instance" -------------
	var instance string

	err = runtime.BindStyledParameterWithOptions("simple", "instance", ctx.Param("instance"), &instance, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter instance: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListInstanceBackups(ctx, cluster, namespace, instance)
	return err
}

// GetInstanceConnection converts echo context to params.
func (w *ServerInterfaceWrapper) GetInstanceConnection(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	// ------------- Path parameter "instance" -------------
	var instance string

	err = runtime.BindStyledParameterWithOptions("simple", "instance", ctx.Param("instance"), &instance, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter instance: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetInstanceConnection(ctx, cluster, namespace, instance)
	return err
}

// ListInstanceRestores converts echo context to params.
func (w *ServerInterfaceWrapper) ListInstanceRestores(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	// ------------- Path parameter "instance" -------------
	var instance string

	err = runtime.BindStyledParameterWithOptions("simple", "instance", ctx.Param("instance"), &instance, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter instance: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListInstanceRestores(ctx, cluster, namespace, instance)
	return err
}

// ListMonitoringConfigs converts echo context to params.
func (w *ServerInterfaceWrapper) ListMonitoringConfigs(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListMonitoringConfigs(ctx, cluster, namespace)
	return err
}

// CreateMonitoringConfig converts echo context to params.
func (w *ServerInterfaceWrapper) CreateMonitoringConfig(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateMonitoringConfig(ctx, cluster, namespace)
	return err
}

// DeleteMonitoringConfig converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteMonitoringConfig(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", ctx.Param("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteMonitoringConfig(ctx, cluster, namespace, name)
	return err
}

// GetMonitoringConfig converts echo context to params.
func (w *ServerInterfaceWrapper) GetMonitoringConfig(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", ctx.Param("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetMonitoringConfig(ctx, cluster, namespace, name)
	return err
}

// UpdateMonitoringConfig converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateMonitoringConfig(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", ctx.Param("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateMonitoringConfig(ctx, cluster, namespace, name)
	return err
}

// CreateRestore converts echo context to params.
func (w *ServerInterfaceWrapper) CreateRestore(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateRestore(ctx, cluster, namespace)
	return err
}

// DeleteRestore converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteRestore(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	// ------------- Path parameter "restore" -------------
	var restore string

	err = runtime.BindStyledParameterWithOptions("simple", "restore", ctx.Param("restore"), &restore, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter restore: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteRestore(ctx, cluster, namespace, restore)
	return err
}

// GetRestore converts echo context to params.
func (w *ServerInterfaceWrapper) GetRestore(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	// ------------- Path parameter "restore" -------------
	var restore string

	err = runtime.BindStyledParameterWithOptions("simple", "restore", ctx.Param("restore"), &restore, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter restore: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetRestore(ctx, cluster, namespace, restore)
	return err
}

// ListProviders converts echo context to params.
func (w *ServerInterfaceWrapper) ListProviders(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListProviders(ctx, cluster)
	return err
}

// GetProvider converts echo context to params.
func (w *ServerInterfaceWrapper) GetProvider(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "provider" -------------
	var provider string

	err = runtime.BindStyledParameterWithOptions("simple", "provider", ctx.Param("provider"), &provider, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter provider: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetProvider(ctx, cluster, provider)
	return err
}

// GetCluster converts echo context to params.
func (w *ServerInterfaceWrapper) GetCluster(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", ctx.Param("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCluster(ctx, name)
	return err
}

// GetUserPermissions converts echo context to params.
func (w *ServerInterfaceWrapper) GetUserPermissions(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUserPermissions(ctx)
	return err
}

// GetKubernetesClusterResources converts echo context to params.
func (w *ServerInterfaceWrapper) GetKubernetesClusterResources(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetKubernetesClusterResources(ctx)
	return err
}

// DeleteSession converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteSession(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteSession(ctx)
	return err
}

// CreateSession converts echo context to params.
func (w *ServerInterfaceWrapper) CreateSession(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateSession(ctx)
	return err
}

// GetSettings converts echo context to params.
func (w *ServerInterfaceWrapper) GetSettings(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetSettings(ctx)
	return err
}

// VersionInfo converts echo context to params.
func (w *ServerInterfaceWrapper) VersionInfo(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.VersionInfo(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/cluster-info", wrapper.GetKubernetesClusterInfo, options.OperationMiddlewares["getKubernetesClusterInfo"]...)
	router.GET(options.BaseURL+"/clusters", wrapper.ListClusters, options.OperationMiddlewares["listClusters"]...)
	router.GET(options.BaseURL+"/clusters/:cluster/backup-classes", wrapper.ListBackupClasses, options.OperationMiddlewares["listBackupClasses"]...)
	router.GET(options.BaseURL+"/clusters/:cluster/backup-classes/:backupClass", wrapper.GetBackupClass, options.OperationMiddlewares["getBackupClass"]...)
	router.GET(options.BaseURL+"/clusters/:cluster/namespaces", wrapper.ListNamespaces, options.OperationMiddlewares["listNamespaces"]...)
	router.GET(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/backup-storages", wrapper.ListBackupStorages, options.OperationMiddlewares["listBackupStorages"]...)
	router.POST(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/backup-storages", wrapper.CreateBackupStorage, options.OperationMiddlewares["createBackupStorage"]...)
	router.DELETE(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/backup-storages/:name", wrapper.DeleteBackupStorage, options.OperationMiddlewares["deleteBackupStorage"]...)
	router.GET(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/backup-storages/:name", wrapper.GetBackupStorage, options.OperationMiddlewares["getBackupStorage"]...)
	router.PUT(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/backup-storages/:name", wrapper.UpdateBackupStorage, options.OperationMiddlewares["updateBackupStorage"]...)
	router.POST(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/backups", wrapper.CreateBackup, options.OperationMiddlewares["createBackup"]...)
	router.DELETE(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/backups/:backup", wrapper.DeleteBackup, options.OperationMiddlewares["deleteBackup"]...)
	router.GET(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/backups/:backup", wrapper.GetBackup, options.OperationMiddlewares["getBackup"]...)
	router.GET(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/instances", wrapper.ListInstances, options.OperationMiddlewares["listInstances"]...)
	router.POST(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/instances", wrapper.CreateInstance, options.OperationMiddlewares["createInstance"]...)
	router.DELETE(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/instances/:instance", wrapper.DeleteInstance, options.OperationMiddlewares["deleteInstance"]...)
	router.GET(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/instances/:instance", wrapper.GetInstance, options.OperationMiddlewares["getInstance"]...)
	router.PUT(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/instances/:instance", wrapper.UpdateInstance, options.OperationMiddlewares["updateInstance"]...)
	router.GET(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/instances/:instance/backups", wrapper.ListInstanceBackups, options.OperationMiddlewares["listInstanceBackups"]...)
	router.GET(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/instances/:instance/connection", wrapper.GetInstanceConnection, options.OperationMiddlewares["getInstanceConnection"]...)
	router.GET(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/instances/:instance/restores", wrapper.ListInstanceRestores, options.OperationMiddlewares["listInstanceRestores"]...)
	router.GET(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/monitoring-configs", wrapper.ListMonitoringConfigs, options.OperationMiddlewares["listMonitoringConfigs"]...)
	router.POST(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/monitoring-configs", wrapper.CreateMonitoringConfig, options.OperationMiddlewares["createMonitoringConfig"]...)
	router.DELETE(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/monitoring-configs/:name", wrapper.DeleteMonitoringConfig, options.OperationMiddlewares["deleteMonitoringConfig"]...)
	router.GET(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/monitoring-configs/:name", wrapper.GetMonitoringConfig, options.OperationMiddlewares["getMonitoringConfig"]...)
	router.PATCH(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/monitoring-configs/:name", wrapper.UpdateMonitoringConfig, options.OperationMiddlewares["updateMonitoringConfig"]...)
	router.POST(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/restores", wrapper.CreateRestore, options.OperationMiddlewares["createRestore"]...)
	router.DELETE(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/restores/:restore", wrapper.DeleteRestore, options.OperationMiddlewares["deleteRestore"]...)
	router.GET(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/restores/:restore", wrapper.GetRestore, options.OperationMiddlewares["getRestore"]...)
	router.GET(options.BaseURL+"/clusters/:cluster/providers", wrapper.ListProviders, options.OperationMiddlewares["listProviders"]...)
	router.GET(options.BaseURL+"/clusters/:cluster/providers/:provider", wrapper.GetProvider, options.OperationMiddlewares["getProvider"]...)
	router.GET(options.BaseURL+"/clusters/:name", wrapper.GetCluster, options.OperationMiddlewares["getCluster"]...)
	router.GET(options.BaseURL+"/permissions", wrapper.GetUserPermissions, options.OperationMiddlewares["getUserPermissions"]...)
	router.GET(options.BaseURL+"/resources", wrapper.GetKubernetesClusterResources, options.OperationMiddlewares["getKubernetesClusterResources"]...)
	router.DELETE(options.BaseURL+"/session", wrapper.DeleteSession, options.OperationMiddlewares["deleteSession"]...)
	router.POST(options.BaseURL+"/session", wrapper.CreateSession, options.OperationMiddlewares["createSession"]...)
	router.GET(options.BaseURL+"/settings", wrapper.GetSettings, options.OperationMiddlewares["getSettings"]...)
	router.GET(options.BaseURL+"/version", wrapper.VersionInfo, options.OperationMiddlewares["versionInfo"]...)

}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7L39cty4tTj4KridW2VpbnfLHueXvVFqKmXLjlcz9ozKspPf3qE3RpNQN8YkwACg5J4ZV+1D7BPuk2zh",
	"HAAESbDVLX/JceePjNUk8XFwzsH5Pr9NclnVUjBh9OT4t4nOV6yi8M+TstGGKfvPWsmaKcMZPBC0Yva/",
	"Zl2zyfFEG8XFcvJuOtFMXeIHvUfvphPF/tVwxYrJ8c84QHj91dS/Lhe/sNzYkdzcT7k2w/m5YVX3H/+p",
	"2MXkePKHo3YzR24nR34b78I0VCm6HiwKB0st5rFSEnZVMJ0rXhsuxeQYfyaK6VoKbffTXWXFtKZLlobG",
	"YI4fmgVTghmm3XpPxYUczvkmvEZyfI9w+2J/cvfwBUyTOikjFV2yk5Jq/SOt8KOC1Yrl1Fh4GNWwaW9y",
	"expEXhD3Mcnt18QepiZmRQ2hihF6SXlJFyUjXBCzYn6d80xMphP2llZ1ySy8l/W3k+lkWd+3MA8nOVhp",
	"98y6K2fbY8F59Nm1qBBDLwWrV9sc4HOmZaNyD9prTlGFt/tHGQA6JIS8bp7xsuQx5ERTLZiaTCdvZ0s5",
	"cz82XJg//dEus+D6zTn/lW3/RcUqqdYP14ZtPc0AwaPXZsg9JgE8D8L+3k0nOa1pzs3633SvJ357A4zz",
	"D6bReafQ7JkU3EhLHCdSXPDlQ6rZEMFSb5FcCkO50CSXVSUFueCsLDS5kIpU4X371gVfDrDQOE7CRFPZ",
	"BddVFa3PkWu8df2G1zMJC6LlrJZcwF1i+cq76aRRJfBILp4ysTSryfG9mw92yRS/WL94ej4ExN/9I8I1",
	"0cwQIwkTulGMvHh6fnR+/pTA1zyn9ov5JKxiIWXJqEhz6xR8/8HN6kd3M9Ky/OlicvzzZp6UPMt307Hr",
	"truzB6TRTJGCXXDBCoJAA2ZsWbRlvJ5NOz786MdzfHwhVUUNWRlT6+Ojo5YZzbk8KmSuj3IpclYbfSQv",
	"mbrk7OroSqo3XCxnV9ysZggHfQSc/+gPhdCzki5YCeiuYy5v0WTGhTZU5JaVfojzHp7Hq+kW6O+PZycy",
	"IHa/CDUqCrzqagpbuRYnThSjhp1RRfF2ujlOBMyyuLHLx2fPnm0BnXihLXRq+zczTCFocvuSBQxNMouY",
	"lxm8Ni2JTxF5XyXAY9d2Ld86e/asXdHZs2czXbPcUutuzMsyq8GFQmv+A4OLpkVXWvM3bP2BEHU6qanW",
	"V1IV3UnCr+/BPjWK2dHKi4qLyQejqcQlljib85rl2zHIl3XxgYjhIxFBvMBRImjsS2NE8G46+dHzB6+3",
	"bC/W/nT66ARXklA0Lpli2hD7DqmVvOQFU27aRsHFlVAAOBPmtBiOBqPQui7dnUfcq48G2PNuOuFaN0y9",
	"fP50ZJywGqT2oZ6RyzolAcPH7uH20v9ATHd7jNcZ5kxJT+fM2PPT4zBelnJBSysq4It9uEpe5O05bcLD",
	"6ET7C48GSa4y1lUGK42fEny0AAWM9dGVOg0tUtnsz1crnq/IGVOaa8OE+bssG6vC5VSQBSPFWtCK57Qs",
	"13i8mkvBinkmMnHeUb5A3xNSzMK9WPwF1pGSQnApNM+lKizVWEHM5IWVy7ggP8HmnzFD55aI5kMtqCzl",
	"Fa708duaCg3A6MMm9RbRK3mlydWKmRVTqTXZj8glfEWY/axIyYFWOzC0oIamzoSKgqqC4CHe0cS/OyfP",
	"pGKgpB8HkWvJzfzNf4O8ZYWQRnCztkKXUXzRGKn0UcEuWXmk+XJGVb7ihuWmUeyI1nyWS3HJhJ1Yz6vi",
	"D2FRA0RK8eWXmqkTxQo7AC318FaMr6wBNdprZ8T4MzbZGVMV1/YcEpMxYfWceK4I2nX3y6HR51qeupF5",
	"+LlTBPh3Sxsp/PJc4hJfSNteLpqyPJFVxc1wlTvIDkra5fyYBPdOupHfyo1Fgxhs8bLa0afxplMQzVWh",
	"//mQ5m+aeghV/N1yAkuc58A/gVPZPxfwUJMHZ6cJrlDz0bN6cHbqnjklCYd3S7YqE04EfIprolitmGbC",
	"4K0oLwgVjp7nmTgHW6W2zKQpCwJEqAxRLJdLwX8Nw2nL2Ow8JTUWUwCUgpbkkpYNm1o1IhMVXRPF7Mik",
	"EdEQ8I6eZ+Ij84zY2DSgojdcJKSGH7gAXk29pglrbYEGLH3FyPPH5y+CMQsBizBsX9UROC0kuLgAvsw1",
	"uVCygmGYKAANnQXR3vNEN4uKG3tQ/2qYNhbS80ycUCGksRcXSGdwUZ0KckIrVp5QzT4+NC0E9cyCLQnP",
	"+NYY0IXVZ8YIwkrXHdQtmLZkSLShBu5XfG9IFkgzwWA5NkF4wZNe9DMadP3sK3mFBxRINRPsLcsbC2/y",
	"YuWu0jua4K9cimeyQF1byRJHV40wvLJSilkdk+/lIhN5JEhYOhA5L1lBFmv4gIuZN4+6eX+RCz9mydRf",
	"MnHm5M9nVNAlK8jmAb20ekf7xcxTJ5aPyOEosnlgIZBnsKWOLG5JgwMqErq0agRgcSYi6N7RZG6Pfo4f",
	"zmXNhOVX95H5zScpfaw11MyAktQlmzXijZBXYobqcOD6BSuZXcqZLHm+7ipc3oL3nFkdZzKdPLIvg5K+",
	"6SFoUBe0Kc3k2P/aV6oedaZtT//K4tKK1jUTgT82omCqXFu+gZAklkgyccDmy/kUXnGMw0prrLBS4vn9",
	"QyvHiQ4unjy3JwI7BuLHtZEDt9pDYk9ANbnRHRyw61CskpeMLKRZ4RExseTCaryGX/oTbrkZFQXSITU0",
	"eDfcybPCH7CTkecEYXj99FvMvGjAclkyiu/H0HOryURd0pxNiZaEGy/MWxqwMksB95EisjEzeTFbWBnX",
	"CvSWdAF3LAyrxoDjRgpCSWnX4UBsp0fu/CsTRIqcEY9hmVhRbTmSMqw4JvqKm3xll1VbHOCWFC/sxPMg",
	"EPsvX/CKaUOrGodYMCbAQgtXsT14y+mkuwAYFU0NnMPuzDJ8RXMG5rlMcKNZeZEkZW97TLPB0+ipJ+tY",
	"d/HPLeztkZCmRm4XHlSNNpkAWDmE0Pb7oBARKxC0yDpP68grVjTlyBrPo6dTxH7NzJRwkOEvuLsb/Ioc",
	"DrqPgItnolayaHJWdJbi/qvRtGelD05hqAdnp0Qq8trym9yUYCtYv86Exz6LCYAyrKrNmhxIMStYRUVx",
	"iMCJuGzFlUIjSSllnQnNjLbYidto1AXN7UN7d1Ej1Sws1MOkCPIf9QvPxMlznQYkUt4IHNuHRLELppjI",
	"LXaSDtWOnCKC0d+GVyumWHQHOBLU5EpxY5iYk79JRUaupkzAXehXUARl1KISoaVitFgj6S6tfm5pV4ou",
	"Ol5ymgm8QHAFczeI9hSD7AS4gF0UYDA3Caj1xPu+5NCjoC6MU4K+lU0aPSrSwNOOUCMXcJNtIdXksqqB",
	"yT8wqbs5PPSUDDezuy7CUYVBiG7ynGltFZe1nQzdIpPjib264VofkQ0KbgZK6UBQwJdaS2JhL4MS7TJS",
	"WL5Q27vNMZq8UQpEXA8DoDJLiN51OARHSbV5oajQ3HPT4UKG73jg2CcIIXeLuQWb8DYrUBy3q8VTtUhE",
	"hTQr8Oa/sEt06tAiAnR0NbXD5isqllZWJKcXKFpyTSwbB/EFrntBGu21iO7RWTggx3HDgCKS56yG+2r7",
	"w4tCMrpwcg9QwVk1FRXE0iHchuGZKMBiaq9cd5h0IRtUUVqwechYzWZhZQbHJnEVdq0Vfet9C/e//T/+",
	"9N+JhXqieMIEcwbewZqH70QqFiyqvXOX7TsA/O6ZX1H0jS6oZgVpatiEZWGe9qeEX6RH49rjbrkm976d",
	"oqRi50aUmbf08vPbV/PEmrkmf572FmSVxgaIwx5nJsALpxiSjJMfEyTDwoI7KIGOevDp8MqKt3cDxK12",
	"vsTYIMWoToEZf28Jmdr7baloVVHD8/YaVjGCIIuHD70dI+zujnbEF6PMGV58Co213skVkaXVMQGnkHcS",
	"9rZGEQltBiCbVowKLpbazenv6Wkm7NPYAOo/UrAuba8pq62QZUMVFYaxAuwtKB+ipt9SOm2Va4/VDueR",
	"SO0qnUoOqN/D+Xt3v/1j38FWU2OYsuD+v39+MPsfOvv11YH7x93Zn/85PX71TfTnq8O//mf6/k/fPY57",
	"eV7rgToF1iYvyAvVsCn5Gy01m5KXqFHZRXtlyD6fTCfwwmQ6cW8Mwx+CybG/APurnSjC8MhCQYDSyIWU",
	"c+fPm+eyOmotGD2ece9PHYAd/IxgeXXw88z96xv/0+FfD7JsvvGFw2+ODv96EEH71c+zFtTzV98c/jV6",
	"dvif14oQiXup5byBzsJpueFSskTHftvTgEuuzayi9ewNW+vgdX6VessNU9HaDtoxUCQsvB37hbssrR5W",
	"WhklfEwq+9hx0nCNegHVqUNWBcylKuxNaq99YH50wUuOROHxqycpTqaT7+UiiV6/yEVauv0eH7QLduKl",
	"55bfy0W4dlUjhGdSTnzMxJmsmxLUACnKNazXfuOE1qS4bQ/6py0uqqfJ9zqCSBACo6vFkWvQ8pM8fcjH",
	"R+/4Z4M7fja449sLvXO9JLfvlRZc4HN2kfBy9l8hYNTUHnGC3jOi9oNloHX4Oj3NWUjOmMqloGhJfSbF",
	"Uj56iBMdzkn3ODNxMa6QJK3qT5RMWeofnJ3CE394S/jDX3GtuYJZ/Gp1nHkmTi9I/LG9H9w1xwq8/sOf",
	"BGzNoA4t2ihSqVAQhCmdfELFmkh3qXFVzGqqzBrvymlnOs+f5rsbvIHAHf8e3WBq2HTYVsrUsMOwPV4L",
	"S/dBNtfYDC2z9BzVyIrncGW68Miersx/DYu0b3hajNVdCh4TafmcN6+i0jmimgNHTGlu5/7RRr3Ns9St",
	"ZX0g3ORsJuwtKUMuxiw171Ie1vg0wJh/jfdrxKkfW943+cG8ffvB2eneGbZ3hn09zjAgjW09YvByyoC0",
	"0a8TVDw78k/okSGX9z1puFCbruQE7CcTXf8PmiY8X7QqMqzHG7Yixw9SQNp2G15RzkORcitx7ZY33G3P",
	"p5SUTuIXPN8Z7rzL/XMP3B08UqnokM5ifht4ksJffl3RC2MrGqBbwXVd0nVaZn7UPkwKhT5YerupdtIr",
	"NCtZbjRZMHPFmCC/yMUMrS9WU/cS36xykloY+2Zag7eKnEihjaLcpXqlfSHRS4HUclnV1HDUXLwwVTk7",
	"EzVeVsuEpoZrkOEWa3tjBIv1gl1I5VhgDErvp2rs3sHMg1bqLir7S/ZvDqf6a3/eeR7bakqXsuTChePV",
	"orOpZ1kH2szEY5qvyBu2Rrz4/vynH9H3xN5aPIeYJBzLyfNGEur9aOkRrbjqtPspySbIBJzAZA8smxCp",
	"wgPLIs/R7mv/eVpZQcs7i7WsGOw0m8x3C54c0OAvcpHUJVsQthovGj2BIDrI/F1mv8gmc/LMAbYRmplM",
	"gAg30KezPuLiLvrRq+Dw+14uzpN3wknnuecQPoIpGNBa4SW4EH/xirBqhHZrdKGT9lp12qZU5DkDv3PP",
	"vZxySlQ0JSOc4IMgaro/jbQzJ1nK9oFtvEpquKeV02/BFAp/bMcoU6jhIi968Xv9Y+i/gyZF/HkGgbgF",
	"wWiA503JNFmCeRF9jTQTTt1nBfFJc7JEP3v090MuCmc6H/G3tDOQlbR0buUbqyQEg3cbJ0vRM70mqrGk",
	"uGgMKSRDjdRhffx5JtAmcLWSLojFLrCuS3C8ShLiaWNn4eC1cR1bjyvZOuWSDlotbKsjsgRBFr0sVVMa",
	"XpeR1oynE6ndVn+muXMdgBwZCRdoHEV3pb1z3EGFWSynswOE4ckVL0swEJelvGLFnGSTbNJ3SnQVeTjr",
	"bPJN9z1altGqd6CNDea/VucVUniv2svnTxMH8GP3BSfpM7hIaqoMpyVpVOmTXjERy+lCK3rJQADUcO6E",
	"fINQdzBBhAMTG0V4XDRlOSUXHPiWYbW/QOx9k4lzbu8QIa1Y4tQIWBJGXpsW68CIEkzwVtGAOTDM30oz",
	"lm9HRKVjFzRoGjRFc5lAurXXNONgaoFwAIv69oRabDjQTb6ym8omtSy0v880yxUzOpsc2r/7G4Fddr61",
	"OkU2OZwSABQoM9KsPjQK+DVEqc9deSJ6DMcv2svlyuo/QbCIsp9TdE/Ig+AAZAY8NO5tdsnU2kCoDNeB",
	"ZD7SPjfs0aG33097oGgH6O/nzjd3+pTa8p0PvPpLphY6mdO56K0af0JyDOj59Ckq4W55VmkPsiFzgprb",
	"YnJfMP2H3VPPYIQbvNb1gYJaWhLqiUADySe6/bFYAQg1v8jFVyTK1JtkmL7wEjjqJvHFmbWsMFnLAuNx",
	"KGmlmSDG7OWXvfyyl1/28steftnLL1+v/NL7zAszqQ/rnlVzeFf2vdj+ClmBJS5lnhoanMiLFcuEDnZv",
	"Lgz6MCDrVdZMHAcrLPplMFiZkZzWLoIjE/Et7ZzyPsjq7PQF2I10U6OPdBpCmiMjYiYKTkuWm0Owfdp7",
	"+kKqHDPMT54/cvGOPcsa+EYzkbCsoR1uGCnKK54y+T6F3+2WMMOnstehjySewh5mLk0y+tneeH4vmtRM",
	"ZcKHMMcWX4xVy0vL6SEklMQBy1EaR+6cnplAq7i9eF/CPp3R1jIdkk0aAfuw50cOtLF3tW7Qm+ZDAqVi",
	"mXhG355ahCc54yWEw0nRD4+vWe6C1X1SErNniWyDaZYJAAq4XSxNFk5ERN/0QQjJcC4ZCKJki5WUbw4B",
	"Pmjutsera+oSIk58pgiu4S89BKNF4RzoocgF+JWCMd7OLmuwnJ1IYdhbM4+8XXiWB4fD06/oW3uSj/Eg",
	"XZx7AhueJd/zMlxF3/KqqQjWQopSymFh0cFbgYsapBlmyLzmRs0dFn1nVBOipiDEHnKwyGPYt2OAjmSs",
	"QK25WJYMiUkbxWiFdEbOzp89ejglZ//75DAg2T2yYqo3WCbAX3nJyD8ePIWUc3trQeCCH+nJIYkSG4DA",
	"+pFG97+9Nnq0om+9306fMeWglwRy4r1xICuWNwpczIHkMuEuW0t7kZ/BDcWEUesb7mATblyPEHZmSPhx",
	"y+OidW0mkxU2r/LecJVJ5Y4bhaQ15ue06BO/0SuaoFcUo3tqpmYeioByeaONrFyKVyYOekwEX7VvznF4",
	"x1KCCHuhGJvZDQJPkDX9V2PJQ8bZkH/pZoV5H68mKcjBsjJR03UpaaGDqsMN4RDFS/7uvj/w7I1ZbZ2J",
	"wqILfobyYCaGft4LRZcVBBfgEl+egtysGLBvSirPyuyeQBPIhL0ygr8yBC67a81OBcq3MZ3Yq5slNTrG",
	"oC0QEoE90VMfis3isg/hqvHjoPNuxgXmcLpUufU8Ey81ejC9Dyhm8/becr8PfHUWF12hsW0riTmLzFjp",
	"l+fx4x0jFNzQO4UodHaWh3zXEHqQiX+L2AMHmu9T7s/n4dk1XtAIxmAJ4n2hbMQzSpKO0UzsPaN7z+je",
	"M7q3LO4ti3vL4t6yuLcs7i2Le8/o3jO6l1/28steftnLL3v5ZS+/fNWe0eBK9FYiPWoEjd4JadYOnsHS",
	"3EHvXlZGJryNtFvuCs2CYQisWFTXjKoAc5jHWcdcfT+onsVIo31xMZj0NCrVsb1Q1PAxi+LLU2dKDDdn",
	"a35HC7YlyNZJDBxaSWGYgPT8ynuMQkU3B5Kplw3R9Qn2ZaiuHDk7feWaYEjFyhneuWgUo0bHbJxq5w/4",
	"C7Jzb26XQkMtZm6cjzo24KOnwl34zjnqUm8rWdDSme9gs3DqlSunRzJX2CmbTC0X50bhv9zOgC23tbo8",
	"8uBxe5C/p/2+X363ky61eyUpzAfcvpzUeErgvpzTvpzTvpzTvpzTvpzTvpzTvpzTl1XO6cOV5PAdW0Zl",
	"DWh+6BRGF3U2sNN4IRsMK2+5Nm11YxAL9eerYE8+YM0Ock3JDvI5K3bs1hx0UJkloXN8ghog5EOVACHD",
	"CiCkUwCE3J76H9t0uYPiDFWInuD/arDoMxeEtiayOTltazyhoBn6lQVkmRJampVsliuiZRUZVTH8EprA",
	"UA9bqM4NYMU6V52yZFRYrVfJWnErrGB7uMZIECFoWa7nxBeVqBWvqOLlGkOMfSk4XJ29OApW1dJAqTZL",
	"Wd0oHaB6lClS5/aenfv+4Nv1bVPnaBMD3cQ735Nt7jnmLeaYe2a5Z5ZfO7PE4nvYFDR5IOg5jLkR/uIO",
	"Bl2MjDo/Y+/45q2TofVCck3s6V3S0gHfDpr57hzZpH0V9ff4kXdUUyGFBX+PA34MyNmFfIhbZjSmvlfA",
	"f1MXKR/Dvm8mta+f95U1k0LUv76CXq8hBnSJeUAGNEaJYujRmUau6m7h4VbmQy+DODCyoGv0eJzfn/my",
	"YiU7JHXZONbUdickgrHCxZTQ8o3rYZGJU9ckJni5F2tXrE3J6tgumJAZ2Zh68vMr/8/n7ALfj6vzRV0u",
	"8OFYxD97ixTZ/SITj1gum7qExB3fetOiIxcFv+RFQ8u2sLFF3DdMD8q+ZcL3PnGpSg+fTUm9tN/Z5RyS",
	"WtEcLtHjbhIJJm1g9xBCM3HB39oTxjCHOG0r6hTi8w/B31Q3ngQrF0GQCdcWNAjr7fKHnFTfT7gm77dC",
	"f+fs226c8XU+z8TzjozyYl27LEd9PxUYj5EZP7B1quftg/DwESIvNEWZASIiAXJAWi7qxszJP0KXHerz",
	"+jDJETxzPo7jHAIgAPMABaO+mvjoR983PC8ZVdD5xVtV5wSRWLBLpkjterGGTi9dcnP3RoofLJr8DUsp",
	"X/B7Kszo/D7Bj9Ktz1J7SHjEkltNzYYwSnbVcZmCGNcFjqF/nP/zwcnJ4/Pzf/7w+P/65+kjAJ799fzx",
	"yfPHL6KH5A1bj9RhdMw+2bP4cfvQrzZcDva3AKMOfloRJ0/UNe5ZJ9ssIQ2N1oJ7Kl5TEPAoJtUQ7Fms",
	"GujizfXL508PNCsvDifvXr0Dr0fOzqhZnZt16Q7CNWG7AAN3b4N/67xPXE5rTc1qpuEXiDE6QAzAk+pE",
	"JXGhDaOFB8RKanM4J49wThBHYNp0f1zLc1LC03P4va1Nv4wiMDejI8YYBepNcJXuC9sQ9zljJOIHyXkv",
	"meIX6xdPzzsQN6oZAPzv/k2COa6a2H/nli9BsCnIiCHuFNrTtbC0A44kinWaMiGRj1FnF+fDMYyb4PtA",
	"9Ky113PPsh77wZy8aK9tZL+d1PbYt6LvJ/wove2MOgiu6x2FEsw2Pv++EDP5EH4CN9gma1f0yvsYvaL8",
	"2L3t63bavrw2ujeB7U1gexPY3gT2kU1gXpkdr9s9YvjyITT7lhF7k9dXY/LyNHG9tSvQVbqF+pic17Z9",
	"jnuBkwtG7SbbgK1gg0KTgiuDM8XUm7gbuW9VDuUjlvzShUqGxmNxfxgowITiRyZAjGxbPrfBy5Fth+a5",
	"VAUXy3JNDjQvWE6Vvd6WTJheYYgpYSafH85JML6kOkdFq2H6L91W7oXE9BUGzQywHA1U5iELltNGw8rW",
	"EI9JCq5Ybso14K1VPhPGsVQJBKp1st/WiXsSN/hN9rXvmMscS4KlyTj+O+pp1Pa4x+sJkoG6xR76xRsg",
	"Sg+OJ+4HcKe181nN29LjMGh/uOfrm0nFe7Rvz7unlCg/cH03YDHW5dchcsrAguXCjFwuy92IAwwLmDbg",
	"4+b1G17rfuGsg8PQiF0xr0NZfRS6rEM1t6WQ3WZfkZFCjxY5ChWOvO1Ud7XInsl0TqBLBCJ4RWtNaCZK",
	"uQSZAgSZg0uuwYJkOk2Z7eoVa1yNmcgMHLV1jszJh9hdomsS9DfEnIRyUm12AlVRvRdXJ8or9L7Jt8CU",
	"wLnufI4VbDBuf0NWZrIQUgS2/mr7/avhEs+pUryLIi5/8yAsCovQHTqipWqJ/cNvQh+dk4lOo7HEEXBS",
	"++b9aJ6lpZbIrPG6hnVEJ4ZLAqAOzq0X5/mn+4m7zYI7XbAqmJNiKZ+N1SwCkxeIEBL2EUryBUaeYISS",
	"0MIKYVz7EmvIiGI87JVjTJdqcxmJiXJtPv8krtfmGAyhhlTSZaPqEUQxkkArkWEVub/geVlFACv3hS50",
	"fslTjFpeu0wkK8M4ifXg7Akp2ZIbXlHD7NKxSJzuVomLKEixWh7u3FAKLdvD6lgAIMw6dAlWbSVKlFbs",
	"ZhDv4hNr0ax/LO9bWmtrfh6ynzrUcr0J00+QNPt5ak+w5MCdWubSlsRzXMNQ/cYhZOh131leJtpxaozM",
	"j4n4wPPESCBrk6FKKetDzGXBE+k37fTLV+T/+3/+37i0m3Pu6JpeCU1OlBTfywXwGkgQGJeoWqbusvR6",
	"Bg2aK6mxDuDAnZdMq9vIvf1UEZOhaSB37z9sKhpViAos50UsXUFeBChzqOKHMqjcVcLLBI53x8otPYhG",
	"3MOB6AXVb6xYD8wkE2f/+8RvoOjuJ3aVhhEP58T3ZJ05TIjcrFZEwoO3BEjzN7jGCFUGLEavqHKqWyY8",
	"ZjiY3XGC2K5sw9VVs+udxbkjkaEn1QqOZSLCojva30huKBx83qvM5mQvrEvWbTd7QcsS00KBJeJt6cwo",
	"A7YVvHvUIXii192iMS7huMBaix4TFHWZLFTAA9daTzXivRlbrlKmDUuLXhmnoqCqIP9r5lLS7KO2Qm8P",
	"mVvDQya6vcCCPBFKTrjLcT7pZ8ckXJY7SNMeanPygBRcu+q8gagsf6zkpcv28zUeOi7+UkJiHvcN3jCF",
	"JcE/hsLzBjELeVO5blOo+uvtQBLELm5crQSsxQw7eMPWvdAEKwG5kgoohYXogy6GY+yFFC0NR1ok+XGc",
	"k5IeI0WoxZDoyXHXnKdirpr0iax5OkO/80JwnMdlXy1H9YzJSPKGsTpcvC245uR/mJLkQCqk4UNXiCCb",
	"wAe0LLPJnPzIlshZ20SxTCAe91rqblMrtne1A4m1SDwd1xorV5l5cnzv7tBt0sbjjKpmPdW+r2Ykoww2",
	"6QrOrzuZTFMY7ZxzbkLTzYqzgufFBcstWMvQE9FVASkaEELs8V1RVfQbKPKohi/mxmNiXUA5HZRaSDWD",
	"fMmQeYo0ABYVOEdaghidM2Uot4L4lZKQw/fh7dhHW6cMXN97OmVq6CDBrhjUR0tvJZqOC59bB3DoLeSx",
	"DhdpQzr+Y0U1RHSE2LND8vvvpPPLnJblgb43JfjyvVYrx3ejH/DVfHVv2hvigpeGqQP97ZTAIN/Gg2TN",
	"3bvf/gn/n8SP5uB61nbEb6FE/bdzUJC/+87+cQ/+ODyca/4rO8Bh7uffkXu9AeP1+XVsGtCP99135N6h",
	"i3Rp3a3gmCgws5KWZx3a3UmQ8vWQQnEunICkhaoxOe0ZTTf3fypzWv4EiPQ8RD22FWMFeA475aokKZkh",
	"a9mQUkJoCBq72jhGZ+l3tZz3vOxL4WXTyRsMThoJYNrjzx5/rrkLh25fKD4/UuQ5PPMCNcQaQWENqVzd",
	"eh7VpPGsz5UAsC+mTE59K8iJ/w6VRf3e6tjGmoYtu6aC2BNQFouDIxveMdJqDvNMeLW1LXnH0WLbmBBW",
	"ASHPwSUaNuO82toq/rqNufXO7jDkfCzUYUQDCgUJPLAnSd0A6rYllQJ80ru2YqXAvRDsb52pBjJ8qijG",
	"FkXDOu2901MN/HE8WTYHfgcXWBsYrDulyKYB+TgCfu4f4cdTFyMMTWR0XK7eFftSkJ8Q8aKC1UwU3hyW",
	"iUcYtu6396AE1mnP2fujltSw/ihcE15VDdajIafoWwUrt+sbDmTm17DJVfI83k+svEjhenXYrZ/JwlLz",
	"vPP2bm5AkEmhQ0MnCLszTS2LeQLKoRjkmYRoKN+oPcDCgh7AgIkKrsyUi1Ggl5SXFlAQPWxJlkbHk6YB",
	"CEBI93Fnuhu2nq+kZlh3hYYYKy7i68hefYCE80ycXuDVMI3L8AUeAG8RKOdTRCufEqiCdMU1GBBcPS7F",
	"dFOaKL4F5n4Pr+lOBTD8KJsLYEyj5k5jMjMV658uQKEZcISBxPKqW4sky/7r9xnUE7k7+/Or/4LqI1Bw",
	"5PCvh7+Hv/7r8PDg4Ocfnj15cfb4FT/8/WfRVG/wr98PfmaPX20/ziHWgulsmgszk2rmluivkmQrq25n",
	"F9+ihlayEQYrtlR1Y+JYPl+ecWcRoaM7HGHKTqiAqWctcziaJBtQYAzO135uz30sUu/k0Py08eQ8ySHR",
	"h4G4JhIbzjieEU4CRIQiCr93SMPbEmbsrb1iubGyQ5AsMhG4g8tq41VdwgUJhz/zdxhIo/N2KTmGVrG3",
	"OWOFm+3TItq7ZJT9SB5t68ffLABgMTEIoSqZjp7oaXDKxmVVMeFpmCTGf2X/vmjuoIxFZYaa4bvdkjP6",
	"omV7o4VajSNpLOnYTi/rpscdSMpbVhMf1EZ3aNEJwWvnakNTWyTDACWnptir0BU189+gCOmaLWYT54nE",
	"qpZKvl3jP9Fu/gDi2yaHoC3wfBUhKoyK+VddgZH4HoTEyFqWcrmeT5I7LZndJpYnBywuS4fFPhXmhOqc",
	"Fmwynfyk6hUVk1cWoTc8fTWN1PD2eReqjzozA3NTstTkClLpaF0zAbzNuT6g0nro1+NLnEZZunEgVlui",
	"MQ4q9g1+MuHWRA7cMg/hCFWTO/k+lDuV7iMXSNGuJRN+MVz0w+La6O4rK/I596VHEpRxrXjLfCJlWCR2",
	"WySGoS+2kFeJOK2H3icrr4SPbukeI1at5AIxAmsgRvDFcnvc6ExENTELaqjfzCBJum7U0iqYiiiGtYnn",
	"mcDzHgcddiMcOT8uMlGXNMe+cdCW9JJfsu6h+W1h7BAVEEutsAYvYLbFAH8MEFwm2FW5nkGWAStazxdq",
	"RV10WIFOgBt+wVTFBeZN1CuqGbHbKF3taC+be2ewPnI70Rg+uWBMeOwiBw65oJg4jhKHGrTXfvupkUrg",
	"YR9Ao06IHuNMH4Z1BwXGqXLQqpKUFmAt8jQGe/XJX5nV8SL4ZWJl1XFDlWHFMdFX3PW/8zMRemEB25bS",
	"9F++4BXThlY1DgHL1cylraPbzTfZyx1R1dSsvMSgfHZEJrgBM3+Kuy9LuaDlkLk/gd9bU2IIQCrZJSt7",
	"kQShsrbreoBAN7yNFnXMWMd5BbFyOG4+woXErRff24DkRx/vC5zKQrZns7DoGdzP4QapdVUs3AUitVkq",
	"pv9V2ksjBXF/JyRuafekF21el3JdYYqKew7dQozezvUw6tloMwnduCOBIjc/O7+hR21KUSYeYz1LfQxx",
	"LwXJQTq3w8Lf0a059dYqNLXQ3EiFseXviwHXp7AGWGMQrj9pt0Rf+BptacwJCBZKwRzgR+AubHoESqh4",
	"OGVj2geguyPb1Xg7ynay1LWiGwoqroAt0nfQQ9wri0YUJZu6LAKs4Oyz2jPh3kLpy3LsWDzqZqedMTVr",
	"ZbDwIYRmckEiSc/QNxYKLGcFyBfy0pWoxbV0QBbCuANVeuKhAXp+C8Cm8I8dATmWVBxyRLbJJ45jQQat",
	"gSK35agE7EOkeqVr2+eiy6g8740Ni92Ja1lsqlm+9y7tvUvBO9kPtVGMFnCJbeEzABpI92aQBsWPa0d5",
	"t0Ufr30l/n0l/n0l/n0l/n0l/n0l/n0l/i+uEj9c4IJBy8Hz8aCnk+FLvppgVDgwqhzm2IO79Ny3/p5w",
	"dOSLjKHeMmubTfYUtpm3skXp1sABvb0gE9nkN8/qZvaXdzM7azYBNiCvIi0wGJAOYFJvx7IcDRuqt2Yo",
	"tz4Ieb9iZTkDNEfzNhe6hjxrN+w5Fhsjrk1ft23pMRYjzOBMsgmx/5uRR15pAGoI+m4lxVImbRt+FA+X",
	"bEJmwZHQ05prpnIp6AyuFzULg4ZBVlKbsJT/U2qDhhdFTs8ILQrFtA7zSdW+eiaVccEt/nmjmYJjmMS7",
	"Cr/6UajWV1IV3bfCr34sxd1UZEb+1oB6G9Dn5fNTwkVeNgDiqKrWXoO5pRoMWJcTRj8wOvetfJHy7G+a",
	"MwbkNJminVBzKfDPU8HtyfNf8c/noBlNJy/rAgSOyXQSGbnhruKY5YC2bPzxvNF1mMD94V9qKvvzq5t4",
	"53yFQo87PcNOEPdbQdGnV4U04DbH/icU+S+40iYwQO5F1wSThFxK7a0Arg5F1y6DvALRSxTI4AAVXZ6O",
	"cA4g3Sw0+1cD5SZ6U4MuAs6Yy3bXDsWBhJjQrswGdGT1bCoTTb1U4I3C+kFWOEItxtle44Ue+lxMXiKg",
	"jOLLJaSqi0w0IhRbCjjkR4dsMFedLZAccPYn3PwEuTmy1OTggVrKk0dT8reyeXtI2FvLXIJ6B+pewS8u",
	"SE7LvCkxxwByfN06p+gOaMPYQuNiKJmh60Zx2YD0PpMXM70WOaElU2Y73+xO1e78Ntu7+hFet5uCVXq1",
	"gxJvuXTodoBEZvTwik+Jo2MihVtmVFHUflokRnWhIeG0g3pDXqyYBmYJ+G+Y2EaIAB/aD4GF+QsfCoCA",
	"6w2qnUAqpRsNInDhSsUcd3UZ7AV+qb6ED6xpTS4kVBxLyQh9mQJD+NoOwUMTh720h6dmb2/PdFbJm9wu",
	"1i2RGJk6G38PJ3i1e+Jn8G/iWTRmZe9glHOSA0tlUv3BVVhy3UoUW6xza0dSm8lsORDG3zg2x9vqQVsq",
	"LB0/hVNeAhY6ocvJWFPSCm1TUq31v8rD1ESN4oluqFbCQZ2azRYNL01P/kmO5CStxHDuiV+6f3Ors7u2",
	"qFm6omb89EbFNEN8yb6O5m2soxlKb+1LaO5LaO5LaO5LaH7kEprPpOCosZ2MBFf03xgpqVmF1xB19u1k",
	"9rU1v57amvrampoDQutTRl1VCbH72bNWpjt79qxVClt6u6ZFiAktQuqqSvUI+RDdLQaGaj0wVHsF7w1b",
	"Y7easK/XtOY/sPVrqHISTM/uXZc/kJbxy5SMH5pYRL0rLBxRs/xgnQ04ejGhCpBuFCMvnp4fnZ8/7bc2",
	"OL3oZmTGdhgkSbvc7XoejLU6sJC4WWcDHxAYoZORsoxM3RZpDmOroUXUG7Yz2Lq0RF1VDq0J70tUHqHt",
	"OkJBCYgHhSf/8R25U1fVHfL77yRUmair6hBSJ8amwGJ9zqQ8Ps1/dEYMJSvg3e/cxFi5IfYOOnz6bcLF",
	"S81ck5KByUZvE3N1LRtxU1zXEuXUvobXw0VJl85qii5lBtk/VKxbd44zYrIh20mXRCqpNj9tEVXwNPme",
	"R04wy7uqP7Hk66ESHM99qCQd8kMn/I4s1x1QFB+WyN8BJjMq4pzHj61ocqV7/MmLO/ObiXU72TT7YEub",
	"HFJv3cj0MBAR9yaI22iCGLCYvSlib4rYmyL2poiPbIo429r50DM9eF/EvpvH3uLw1VgcPE1c380j0NVo",
	"loZVCHcoMOdTXTpiRd1zfAedZ6gchHpHm4I/tk4Njyodjr0RMZqb1NMLdaWQ72yqPOU4U+tr/wkrC5PL",
	"+4N8s7CWO5q0I3ywVLDtAdj+sBzkJo4lUsbvbLFdRpYh/7Kb4fd+ew0pabuUR9wdBXzVhhQ+b4l3m0C6",
	"GzCvSW58P5hutZuGj+3k5elgFy9PibJSHtwIK+7LZ4AsNF5OYEdEiFlSMmystavkDYbBdsPGNNSpx67F",
	"mhntq6sApkRpgaHwFkaWYPBh1ZgGSqu1mYRz8lJjXX5nGM0E9fFhl5y2uXNA826Rc0xXwUiCqGY2M4T6",
	"9bo2SW4oLArguqe2gZUWKj4jsCeGjxflcot4GPIJaYCV65KdyHZMgSETMRzO2jzGS1ZaqvJnEUDPY7H+",
	"yI89X9OqvC63cIx+rw2PCkmG0KSmX0sDBTQerDFOoolyHULq5g9sreM6Y/2holpu8Z09b5cwUkwj3KD9",
	"Whd42BVVb3S8Fl8OnFdYrofkK8l9/QoqWmOerKBeQ4x5LrvdqmmP31LoPiXDAXmBFooMuOmPR03W0y3a",
	"zjitNcpm6cHV9TjIJv89vzu/9y2mIyNFWVxMUk/ocOG60kiXDRxn2n6gMmU75dSGU9/GvhtXrhkkv+9T",
	"AfepgPtUwH0q4D4VcJ8KuE8F/LJSAd/TVeflgrSLLn56I9dcPd5kc++S+/wuuWDC27vi9q64r9wVt4NH",
	"yVXWS9Yfx0J/SX+S8gX59hGse3/S1+JPciRxvTvJvXiTBo4RcWGn3hv3b3SjjLRvfF9rsgXdOWBTwvwW",
	"ngUw+eYAoWMzlD8FHo1sBlCMa1dCLFH1Gb9Lx90+DM86Xd6iDNzQ0C/d661T2tQuBZsOjjTPB9UsZDZ7",
	"4uiUPHNtBlOIx94i60l0bXRPoprmNLRRxTK9mghJcqmsvi0xibO/tUy4NHYfoNqOQd8wYZV3qMMmL8B7",
	"8viS2Y0fjkEcdr8J7OGFVAHNQQN9jxAredUBOvAZDxq34CT4riehC6mufFHJ/iLu6IBxXZcQ9u3ORJLA",
	"EFvcxUR1oO+oSel7E1TUAHy0wnofwxO1g9PYDcWbW6xqqbEHcVeVuEOGmxXKPpJ0N5LS1Ta0LvfIMdKr",
	"PHS+7rQm94TY4YKbm5SPN8PuuehdBbsBe2tTcbGPe1gi3o72FHjV9lB3Eu2LkGYAlrPJ9rbR7XOC06A7",
	"DnMSqUg2QSkIV+ANKbDZqXt00+j1pKAZl+IeT9cdYyFxT/e4+jSyaP80E6Bj0BJKFCLjH6EGV3EiKoAK",
	"Cj/4nwa90+9oco6Iw4qz2AKwGTrR9djb/6sd3CJe4NjGK7JB5qhqKDH0wKQrjbqHAZM65v2WW7oXiW7y",
	"nGl90ThX6XYYvHfN7F0ze9fM3jWzd83sXTN718wXWKWRvWV5Y1f2TBYspbtGjyNDBurI4WNS2ceOk4Zr",
	"1MkumXAtM6zgnEvlba3I/SgWtusUZ+sK8JPp5Hu5SOLXL3KRlj6/xwejSbrfy0W4d1UjRMulUNzKxJms",
	"m5JiCcdyDQu2H0EbcaaTOuyHSf0DbhgEwa6BO4IqOXm+Za7f6DX/bHDNzwbXfHund26Y5P6tOEaNVG6F",
	"yYKfPw3eQd1Ge+zxg8wEhRp3XlKNrJwsE0HE9z1qnFHkDMtTosHzmRRL+eihm+pwTrpnmgl7qD1kiw94",
	"YP1+omRTJ23f8MSf4BL+iGzquPAFQ7eHtyZhhnT8MYQ8dvOlw58EbMLe4+JUoNxCxsqDMKUTU6hYY/9K",
	"e+mpYlZTZdZ4ZU4704WOebsbpmPddHSDO/bL7SmJOwzbY7mw9OlIQNs21SUdv0ppVuf+0Wa9ynO8rWXx",
	"UFZ/MF1rlUjKeKpVED9s2T9HNmm3e/TwRl5372jaO91vo9Pdew/3Pve9z32f/rpPf/1Y6a/23mN5o7hZ",
	"g/8Skf8ho4qpB43V7n6bAGOCMHv4uZ3ILn/y7h0Yoi/k8HD+QB50ClFm4gG0IQz8gTgfGQhQjmDIa/uR",
	"VPxXLLBOcDEka+7evZ8b+YYJ+Cd7TVaMFr5gPHXNQ+EF6KxeUi5mhr01oeo7PsupsMcvF9j/kSzWzs73",
	"muFqclO6V+25mdcOg+AP38/sDcNejrUCyZkHLNG5YkzMM6i6yQ0Ubom8ge5Gm0TphpN787vzu056F7Tm",
	"k+PJ/fnd+bcT0KpXcCJHzvU485BesoRM8MIbaZd+pd5jCZKi7+7lva1O0I7arHmhNvQZnHidgktxWkyO",
	"J0+YacvqnuB7p3ZNVrDRtRQaUejbu3edX94wYVCsCO3njn5xli0dUrk23YjpCQHxerJasKCTsGoL2D9+",
	"wMU8Vkqq1OQvhR6Z/n99iulPvVDkSrkw9+J0opuqomo9OZ448AH3sfhJl2CpaOE7eWU/8MimRxENpE7o",
	"UOfeBJzCRCOH6fMB6tiPTvzIHxFd3BwgNu+AJLfmlAC4eQuo5DFZJcrxq9B6fIZCyyR8G5/l0W/uX++O",
	"0LU8c+R/PTex+gP05ffObM84vBswaMgbGIfdVeT+gwurpopWDDHt5+H0XXelGxvcfpNjYI1exQxbnsTq",
	"FZZQaw+sfz2++og4CEJ8tN0xZHzqVLMuYHs5eB8XJR+PoWBvTS0i4r6uQcIekm2Fike/RVEP73a45uKl",
	"RujoSru/jkZ9jTg1wNzXbkmvRy696Cw/O+JOr5sxBkd62kVnO7eTZlLI+jA+aN+QAG74P358SulMbtXa",
	"C9mI4rMT6xNm+if+ESg10jSupUvFTKPANelNT+3Xrl4/EKcXFUauix9j5ebf964I29xNYunggLedd/VB",
	"hwXo4ShR7NuMC9H31+LB0W/h34GRO9XiJkKF/3TIm7sRRlvJGOd+HbeWV+OGugxbt6tOTN+aQW4hx3YA",
	"31Xo3mtmQ4ErwoIuHycOyEDDdbJhTCAv9MpZFizYVW/k96CwExi2c+S3ncQGEfIeClfcMh/mHZgfnOjA",
	"zPVQYl/nj0RvKXx7Mdyqdw3J7n67G3o34BT3PvHK91ziGvsNnFzvcDeziWvFvsBt3uu+x2fvkCGVLOVI",
	"DawJX9ApkhyqbnbY1wl1LSzlNbCsjerbI5jwi2JaSbngQ3KobXXIa6d+T2Hkj2PZLwEnfB/XODz6FjCF",
	"z6ryIUbvxAh2s6R8XIIM9pQ9Nd4uarx7ay78T2fO8ah+Kw06W5F23WwibQy8+ITUDZ1699ftbSHw26qG",
	"uICgLdSQu3s1ZM8UkavcIt0HS/XewArzYawvX5zZ5Ys2t1zD4G6TfWWT58qF6vdVqc9K2B2jxs18Vzck",
	"YO9uvrnZYsTTPOpkvqnV4osj9rbSwWeQoja5vN9vvp8umVK8iLd6BwMO5oAeXIozWfJ8TRbsQipnvMCM",
	"ysydaDYhB47gDolilbxkmiyk6zzIxBKqUyMYQ6C2D93DMhKCnN+HEZ8zQ7nIJmGcDUMsGkN8rQw9HOwf",
	"KyagOrPxiS8hVQBDyaWIymJAVRSs8Y24CwD/V8PUuoV4FySTGNI+0QxBMpm6naSqI3wiLXUD2xyzQG2y",
	"Xo1brT6dEHd7hLeOvSrN43e0T31MzhvMU3u2+1nY7m2g+M8SWXQbTVCfRiLzdRJ2Chyx99eC6rbKwvvG",
	"jpyGVXwRhN9umyr2MQj/oxOiB/h14bEtetyKyFge4YknDr+V3YMzBmj83haCsJYv5v4KW/9CrQQB4iN2",
	"grC/G1oK7n665YayYGPWgg9ut3iv1dwG2wVv6S3JDsZvyw5ju8l9efSb/+fuVowh4xmK1f7RBzRpfMHc",
	"6TPJ1xF+JSaNnn4o04YfcgfjxgnVOS261g2PbFZYcyKuxZG2fkrbowzz07luK2bZQX9S9YqKbEJKRi+Z",
	"HhsE0z3hm23NGIGvfCBDhtv+ZOrW/FksGVsx0p2sGdd+9UnUo7CKW2fRuI7zb2nV+OSc+AkzezZ8C9jw",
	"bWEJn9bccQvp+Qkz1xLz9nE2n5ye0Tu+J+nbQtK3Ss38bJE2WzEft7q9ZNENdLkdOmUc67JbPp8O5fe2",
	"5oGZeD8mGJtwH7p17znhv7Fwg4e8XW2FIT5+7UkEUc4hAoeKFNf5FF6fmOPkUgiW+7qt2yWauzLK7rtO",
	"bfubiWM7sSLol5CYnou8bJxFZSW1mZJaKjOFDut2sGkmaqr1lVQFFjGkpFZstmh4aeLxXj4/hTk0awu9",
	"K0bqUEvV7SGUZJUi7zKVTERVdu1M0MzhGsXwpD2IPRf9ClTE9rwfeX3wXaJ5/SiVdfnqpxTepEqR3+1U",
	"LhMr/cwinq8Eu4uMF9oU1kxdSFW5QpKfTdx77vew51T/xpwqLoi8QeALyLmX+BIS3wjppoU/X4d4MzsK",
	"HGQ3blRJwY20yDPDQrM7saD2a1emFvxAlCz5JRNRMd4k33gWPj5xM986xvFjPzttuOEvKtanD/J9qZj3",
	"KBWTxAVPtC2kdw9GGgwM1XMfDH9vy4a7loGvLUa9diZHzcw8Ew+hf5PzuPrnWDG/tiLQJSNv2BoL+HZL",
	"TQvGCt0Z67zJV4Rq6PwEQx2Tuqpeu05dr+2/YbD4S6cQFb5EcLcz5Wj4VB9Tv0Te8AUETvXBjMA/s5DW",
	"YwbuZ2No+JkDqgYos2dsN61uk0LlEc42LpEkRIv3lU1uWuJmyDlH0u7nI/FSXwY7ugEn+uJ44HWVa77m",
	"xPEhZ+7YX24Nl3GBOztwmS1jeN6Dzp8wsyfyW0nkezFhz0RGDLo7cJCamny1ZejQe7ARjBzYc5KvR2XC",
	"E9+sMlWbVSbfl2uvM+2Z4c2YoQtYuh16W+zM2snw5ftGvm/unbeYfzGOKL/xLzTzLnRKTHM/v7vbUaFn",
	"w2J9PsttznNTAbc/iX/If3b0m/vX7saX0A12IEO5Jx8wr+2LpfzP5IFusSkxZ/vw9vmfN5HvTtlV1330",
	"ScQMv4hbl1u1mdtsaZX5NAzgCTN76t9T/ydPpLp9tPuEmY8mJvj41psViQlf79y28CzM+2/fstBv9boQ",
	"q/YobkVMUx2dkMc5v5VrkK6zk41Yd/Sb/+curQkH+Je4ivyjmzYnDFu99Z0J63aliSmjp7eQJlIY6Z99",
	"cs4fJr5drD86wQ9Eh8HpnqQ3OycNXa4X2MQ96WA7Cei8kUR+3JY8blW3Bb+529ZiwTecvr1enPaM36/N",
	"cs1UxbXmUtyoP2b0eYhabjSz/6DGiuh5oxQTplyTUi6X0GkbIvO+efyWVnXJjr/JxAOtmwqF+wtZlvKK",
	"iyV5/vDBCamhcAkmGdlhNXlNSx5Um4VcvD7OxOvXrzNRT4mSJTsu2OU0aic5hZShKfmm94a/3mZYdVZP",
	"yTdT8s3R6GseaJ33FnKx8ZXllMBy2xHdYu31YgEKtkuEam/7fcC6ffvd/pYJQrJJ9FY2OSY/21+J/4/9",
	"XzaB77LJNP6tBU/vgYVV76dvsgn++Wq65eh90A4H7P599B5TeJjvMIf9z6tMvHOQfOAqFG8AfYxm2wN+",
	"IRcfb9Wpm+KlZuosIuePyLf7U+2jBm/ExIFT1p0j89z8QWNWTBi3MJI1d+9++ydif5WK/4rbeWVHPPLs",
	"Xe8g3Oe0pjk3a8zevKS8pIuShZrb2ksS7Z2ySdd8wkz7ors6n4dVfUQ03DDrHiN3j2N1Qo+Kji4pXFis",
	"0wxQdivHBheXtOQYKuJaZ8Pv3//jBTHyDRPjvolzN817RTF+++ePD+AXUpKKijWhxrCqNvpWHW0M9ady",
	"KRuzM6u5Nh+Da90Er3Q4WrhBrehnb1YuyIWSFbCWaElzFIhC1gOwxarRhqzoJcqFr0u55OI1MK4FL7lZ",
	"j3uyY5z58M5be/WdKFZYiNFyNHoF9pBH733oMJVa2b0bjl8DrJOWDf8LOpK/pFiVr5ZsWd4obtaT459f",
	"bSBiLm4kLmhmDBdLvVuRCv+VFwz8WiD1siwxMSklGJz76T6iGBDm2Bq5N0A5WrAH7hMmmKIl4eJCOihe",
	"MqV3rvThPurD0L6GSJDiaX/Hj07t3B8Rhm6a3UAYgOa/HodZF+K/TR4yqpiyCGoP4J09AgAB2rYaVU6O",
	"J0eX9yb2iRuzD2MLv7VZ2YtFMSwoYmRfbD3xxo5gAItEmaHdN162qpCY6EI2ZhTr24E7Wx4OnV4u7RIu",
	"yOMdqg3Db0Pi284a+x3c8K21eMsx4mLyboy2btqWYyxCtSs3gu9wseX3qi2f4AYIzs6dVhD15essJLTl",
	"23a4Ng6wHSoKInz36t3/HwAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
