// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes bearerAuthContextKey = "BearerAuth.Scopes"
)

// Defines values for MonitoringConfigBaseType.
const (
	MonitoringConfigBaseTypePmm MonitoringConfigBaseType = "pmm"
)

// Valid indicates whether the value is a known member of the MonitoringConfigBaseType enum.
func (e MonitoringConfigBaseType) Valid() bool {
	switch e {
	case MonitoringConfigBaseTypePmm:
		return true
	default:
		return false
	}
}

// Defines values for MonitoringConfigBaseWithNameType.
const (
	MonitoringConfigBaseWithNameTypePmm MonitoringConfigBaseWithNameType = "pmm"
)

// Valid indicates whether the value is a known member of the MonitoringConfigBaseWithNameType enum.
func (e MonitoringConfigBaseWithNameType) Valid() bool {
	switch e {
	case MonitoringConfigBaseWithNameTypePmm:
		return true
	default:
		return false
	}
}

// Defines values for MonitoringConfigCreateParamsType.
const (
	MonitoringConfigCreateParamsTypePmm MonitoringConfigCreateParamsType = "pmm"
)

// Valid indicates whether the value is a known member of the MonitoringConfigCreateParamsType enum.
func (e MonitoringConfigCreateParamsType) Valid() bool {
	switch e {
	case MonitoringConfigCreateParamsTypePmm:
		return true
	default:
		return false
	}
}

// Defines values for MonitoringConfigUpdateParamsType.
const (
	MonitoringConfigUpdateParamsTypePmm MonitoringConfigUpdateParamsType = "pmm"
)

// Valid indicates whether the value is a known member of the MonitoringConfigUpdateParamsType enum.
func (e MonitoringConfigUpdateParamsType) Valid() bool {
	switch e {
	case MonitoringConfigUpdateParamsTypePmm:
		return true
	default:
		return false
	}
}

// Defines values for DeleteBackupParamsDeletionPolicy.
const (
	DeleteBackupParamsDeletionPolicyDelete DeleteBackupParamsDeletionPolicy = "Delete"
	DeleteBackupParamsDeletionPolicyRetain DeleteBackupParamsDeletionPolicy = "Retain"
)

// Valid indicates whether the value is a known member of the DeleteBackupParamsDeletionPolicy enum.
func (e DeleteBackupParamsDeletionPolicy) Valid() bool {
	switch e {
	case DeleteBackupParamsDeletionPolicyDelete:
		return true
	case DeleteBackupParamsDeletionPolicyRetain:
		return true
	default:
		return false
	}
}

// Defines values for DeleteInstanceParamsDeletionPolicy.
const (
	DeleteInstanceParamsDeletionPolicyCascade DeleteInstanceParamsDeletionPolicy = "Cascade"
	DeleteInstanceParamsDeletionPolicyOrphan  DeleteInstanceParamsDeletionPolicy = "Orphan"
)

// Valid indicates whether the value is a known member of the DeleteInstanceParamsDeletionPolicy enum.
func (e DeleteInstanceParamsDeletionPolicy) Valid() bool {
	switch e {
	case DeleteInstanceParamsDeletionPolicyCascade:
		return true
	case DeleteInstanceParamsDeletionPolicyOrphan:
		return true
	default:
		return false
	}
}

// Cluster defines model for Cluster.
type Cluster struct {
	Name   string `json:"name"`
	Server string `json:"server"`
}

// ClusterList defines model for ClusterList.
type ClusterList struct {
	Items []Cluster `json:"items"`
}

// Error Error response
type Error struct {
	Message *string `json:"message,omitempty"`
}

// KubernetesClusterInfo kubernetes cluster info
type KubernetesClusterInfo struct {
	ClusterType string `json:"clusterType"`

	// StorageClassNames List of storage class names that are available in the cluster.
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	StorageClassNames []string        `json:"storageClassNames"`
	StorageClasses    *[]StorageClass `json:"storageClasses,omitempty"`
}

// KubernetesClusterResources kubernetes cluster resources
type KubernetesClusterResources struct {
	Available ResourcesAvailable `json:"available"`
	Capacity  ResourcesCapacity  `json:"capacity"`
}

// ResourcesAvailable defines model for .
type ResourcesAvailable struct {
	CpuMillis   *uint64 `json:"cpuMillis,omitempty"`
	DiskSize    *uint64 `json:"diskSize,omitempty"`
	MemoryBytes *uint64 `json:"memoryBytes,omitempty"`
}

// ResourcesCapacity defines model for .
type ResourcesCapacity struct {
	CpuMillis   *uint64 `json:"cpuMillis,omitempty"`
	DiskSize    *uint64 `json:"diskSize,omitempty"`
	MemoryBytes *uint64 `json:"memoryBytes,omitempty"`
}

// MonitoringConfigBase MonitoringConfigBase contains common fields for monitoring config
type MonitoringConfigBase struct {
	Type MonitoringConfigBaseType `json:"type,omitempty"`
	Url  string                   `json:"url,omitempty"`

	// VerifyTLS VerifyTLS is set to ensure TLS/SSL verification.
	VerifyTLS *bool `json:"verifyTLS,omitempty"`
}

// MonitoringConfigBaseType defines model for MonitoringConfigBase.Type.
type MonitoringConfigBaseType string

// MonitoringConfigBaseWithName defines model for MonitoringConfigBaseWithName.
type MonitoringConfigBaseWithName struct {
	// Name A user defined string name of the storage in the DNS name format https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-label-names
	Name string                           `json:"name,omitempty"`
	Type MonitoringConfigBaseWithNameType `json:"type,omitempty"`
	Url  string                           `json:"url,omitempty"`

	// VerifyTLS VerifyTLS is set to ensure TLS/SSL verification.
	VerifyTLS *bool `json:"verifyTLS,omitempty"`
}

// MonitoringConfigBaseWithNameType defines model for MonitoringConfigBaseWithName.Type.
type MonitoringConfigBaseWithNameType string

// MonitoringConfigCreateParams defines model for MonitoringConfigCreateParams.
type MonitoringConfigCreateParams struct {
	// Name A user defined string name of the storage in the DNS name format https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-label-names
	Name string                           `json:"name,omitempty"`
	Pmm  *MonitoringConfigPMMSpec         `json:"pmm,omitempty"`
	Type MonitoringConfigCreateParamsType `json:"type,omitempty"`
	Url  string                           `json:"url,omitempty"`

	// VerifyTLS VerifyTLS is set to ensure TLS/SSL verification.
	VerifyTLS *bool `json:"verifyTLS,omitempty"`
}

// MonitoringConfigPMMSpec defines model for .
type MonitoringConfigPMMSpec struct {
	ApiKey   string `json:"apiKey,omitempty"`
	Password string `json:"password,omitempty"`
	User     string `json:"user,omitempty"`
}

// MonitoringConfigCreateParamsType defines model for MonitoringConfigCreateParams.Type.
type MonitoringConfigCreateParamsType string

// MonitoringConfigPMM MonitoringConfigPMM contains PMM-specific fields for monitoring config
type MonitoringConfigPMM struct {
	Pmm *MonitoringConfigPMMSpec `json:"pmm,omitempty"`
}

// MonitoringConfigUpdateParams defines model for MonitoringConfigUpdateParams.
type MonitoringConfigUpdateParams struct {
	Pmm  *MonitoringConfigPMMSpec         `json:"pmm,omitempty"`
	Type MonitoringConfigUpdateParamsType `json:"type,omitempty"`
	Url  string                           `json:"url,omitempty"`

	// VerifyTLS VerifyTLS is set to ensure TLS/SSL verification.
	VerifyTLS *bool `json:"verifyTLS,omitempty"`
}

// MonitoringConfigUpdateParamsType defines model for MonitoringConfigUpdateParams.Type.
type MonitoringConfigUpdateParamsType string

// NamespaceList defines model for NamespaceList.
type NamespaceList = []string

// OIDCConfig Everest OIDC provider configuration
type OIDCConfig struct {
	// ClientId OIDC application clientID
	ClientId string `json:"clientId"`

	// IssuerURL OIDC provider url
	IssuerURL string `json:"issuerURL"`

	// Scopes OIDC scopes
	Scopes []string `json:"scopes"`
}

// Settings Everest global settings
type Settings struct {
	// OidcConfig Everest OIDC provider configuration
	OidcConfig OIDCConfig `json:"oidcConfig"`
}

// StorageClass StorageClass describes the parameters for a class of storage for which PersistentVolumes can be dynamically provisioned.
//
// StorageClasses are non-namespaced; the name of the storage class according to etcd is in ObjectMeta.Name.
type StorageClass struct {
	// AllowVolumeExpansion allowVolumeExpansion shows whether the storage class allow volume expand.
	AllowVolumeExpansion *bool `json:"allowVolumeExpansion,omitempty"`

	// Metadata Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
}

// UserCredentials defines model for UserCredentials.
type UserCredentials struct {
	Password *string `json:"password,omitempty"`
	Username *string `json:"username,omitempty"`
}

// UserPermissions defines model for UserPermissions.
type UserPermissions struct {
	Enabled     bool        `json:"enabled"`
	Permissions *[][]string `json:"permissions,omitempty"`
}

// Version Everest version info
type Version struct {
	FullCommit  string `json:"fullCommit"`
	ProjectName string `json:"projectName"`
	Version     string `json:"version"`
}

// bearerAuthContextKey is the context key for BearerAuth security scheme
type bearerAuthContextKey string

// DeleteBackupParams defines parameters for DeleteBackup.
type DeleteBackupParams struct {
	// DeletionPolicy Override the backup's spec.deletionPolicy before deletion.
	// "Delete" (default) removes both the engine backup resource and the data in S3.
	// "Retain" removes the engine backup resource but preserves the data in S3.
	// When omitted, the existing value on the Backup CR is used.
	DeletionPolicy *DeleteBackupParamsDeletionPolicy `form:"deletionPolicy,omitempty" json:"deletionPolicy,omitempty"`
}

// DeleteBackupParamsDeletionPolicy defines parameters for DeleteBackup.
type DeleteBackupParamsDeletionPolicy string

// DeleteInstanceParams defines parameters for DeleteInstance.
type DeleteInstanceParams struct {
	// DeletionPolicy Override the instance's spec.deletionPolicy before deletion.
	// "Cascade" (default) deletes all Backup and Restore CRs referencing this instance.
	// "Orphan" leaves Backup and Restore CRs in place.
	// When omitted, the existing value on the Instance CR is used.
	DeletionPolicy *DeleteInstanceParamsDeletionPolicy `form:"deletionPolicy,omitempty" json:"deletionPolicy,omitempty"`
}

// DeleteInstanceParamsDeletionPolicy defines parameters for DeleteInstance.
type DeleteInstanceParamsDeletionPolicy string

// CreateBackupStorageJSONRequestBody defines body for CreateBackupStorage for application/json ContentType.
type CreateBackupStorageJSONRequestBody = BackupStorage

// UpdateBackupStorageJSONRequestBody defines body for UpdateBackupStorage for application/json ContentType.
type UpdateBackupStorageJSONRequestBody = BackupStorage

// CreateBackupJSONRequestBody defines body for CreateBackup for application/json ContentType.
type CreateBackupJSONRequestBody = Backup

// CreateInstanceJSONRequestBody defines body for CreateInstance for application/json ContentType.
type CreateInstanceJSONRequestBody = Instance

// UpdateInstanceJSONRequestBody defines body for UpdateInstance for application/json ContentType.
type UpdateInstanceJSONRequestBody = Instance

// CreateMonitoringConfigJSONRequestBody defines body for CreateMonitoringConfig for application/json ContentType.
type CreateMonitoringConfigJSONRequestBody = MonitoringConfigCreateParams

// UpdateMonitoringConfigJSONRequestBody defines body for UpdateMonitoringConfig for application/json ContentType.
type UpdateMonitoringConfigJSONRequestBody = MonitoringConfigUpdateParams

// CreateRestoreJSONRequestBody defines body for CreateRestore for application/json ContentType.
type CreateRestoreJSONRequestBody = Restore

// CreateSessionJSONRequestBody defines body for CreateSession for application/json ContentType.
type CreateSessionJSONRequestBody = UserCredentials

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Cluster info
	// (GET /cluster-info)
	GetKubernetesClusterInfo(ctx echo.Context) error
	// List clusters
	// (GET /clusters)
	ListClusters(ctx echo.Context) error
	// List backup classes
	// (GET /clusters/{cluster}/backup-classes)
	ListBackupClasses(ctx echo.Context, cluster string) error
	// Get backup class
	// (GET /clusters/{cluster}/backup-classes/{backupClass})
	GetBackupClass(ctx echo.Context, cluster string, backupClass string) error
	// Managed namespaces
	// (GET /clusters/{cluster}/namespaces)
	ListNamespaces(ctx echo.Context, cluster string) error
	// List backup storages
	// (GET /clusters/{cluster}/namespaces/{namespace}/backup-storages)
	ListBackupStorages(ctx echo.Context, cluster string, namespace string) error
	// Create backup storage
	// (POST /clusters/{cluster}/namespaces/{namespace}/backup-storages)
	CreateBackupStorage(ctx echo.Context, cluster string, namespace string) error
	// Delete backup storage
	// (DELETE /clusters/{cluster}/namespaces/{namespace}/backup-storages/{name})
	DeleteBackupStorage(ctx echo.Context, cluster string, namespace string, name string) error
	// Get backup storage
	// (GET /clusters/{cluster}/namespaces/{namespace}/backup-storages/{name})
	GetBackupStorage(ctx echo.Context, cluster string, namespace string, name string) error
	// Update backup storage
	// (PUT /clusters/{cluster}/namespaces/{namespace}/backup-storages/{name})
	UpdateBackupStorage(ctx echo.Context, cluster string, namespace string, name string) error
	// Create backup
	// (POST /clusters/{cluster}/namespaces/{namespace}/backups)
	CreateBackup(ctx echo.Context, cluster string, namespace string) error
	// Delete backup
	// (DELETE /clusters/{cluster}/namespaces/{namespace}/backups/{backup})
	DeleteBackup(ctx echo.Context, cluster string, namespace string, backup string, params DeleteBackupParams) error
	// Get backup
	// (GET /clusters/{cluster}/namespaces/{namespace}/backups/{backup})
	GetBackup(ctx echo.Context, cluster string, namespace string, backup string) error
	// List instances
	// (GET /clusters/{cluster}/namespaces/{namespace}/instances)
	ListInstances(ctx echo.Context, cluster string, namespace string) error
	// Create instance
	// (POST /clusters/{cluster}/namespaces/{namespace}/instances)
	CreateInstance(ctx echo.Context, cluster string, namespace string) error
	// Delete instance
	// (DELETE /clusters/{cluster}/namespaces/{namespace}/instances/{instance})
	DeleteInstance(ctx echo.Context, cluster string, namespace string, instance string, params DeleteInstanceParams) error
	// Get instance
	// (GET /clusters/{cluster}/namespaces/{namespace}/instances/{instance})
	GetInstance(ctx echo.Context, cluster string, namespace string, instance string) error
	// Update instance
	// (PUT /clusters/{cluster}/namespaces/{namespace}/instances/{instance})
	UpdateInstance(ctx echo.Context, cluster string, namespace string, instance string) error
	// List backups for an instance
	// (GET /clusters/{cluster}/namespaces/{namespace}/instances/{instance}/backups)
	ListInstanceBackups(ctx echo.Context, cluster string, namespace string, instance string) error
	// Get instance connection details
	// (GET /clusters/{cluster}/namespaces/{namespace}/instances/{instance}/connection)
	GetInstanceConnection(ctx echo.Context, cluster string, namespace string, instance string) error
	// List restores performed for an instance
	// (GET /clusters/{cluster}/namespaces/{namespace}/instances/{instance}/restores)
	ListInstanceRestores(ctx echo.Context, cluster string, namespace string, instance string) error
	// List monitoring configs
	// (GET /clusters/{cluster}/namespaces/{namespace}/monitoring-configs)
	ListMonitoringConfigs(ctx echo.Context, cluster string, namespace string) error
	// Create monitoring config
	// (POST /clusters/{cluster}/namespaces/{namespace}/monitoring-configs)
	CreateMonitoringConfig(ctx echo.Context, cluster string, namespace string) error
	// Delete monitoring config
	// (DELETE /clusters/{cluster}/namespaces/{namespace}/monitoring-configs/{name})
	DeleteMonitoringConfig(ctx echo.Context, cluster string, namespace string, name string) error
	// Get monitoring config
	// (GET /clusters/{cluster}/namespaces/{namespace}/monitoring-configs/{name})
	GetMonitoringConfig(ctx echo.Context, cluster string, namespace string, name string) error
	// Update monitoring config
	// (PATCH /clusters/{cluster}/namespaces/{namespace}/monitoring-configs/{name})
	UpdateMonitoringConfig(ctx echo.Context, cluster string, namespace string, name string) error
	// Create restore
	// (POST /clusters/{cluster}/namespaces/{namespace}/restores)
	CreateRestore(ctx echo.Context, cluster string, namespace string) error
	// Delete restore
	// (DELETE /clusters/{cluster}/namespaces/{namespace}/restores/{restore})
	DeleteRestore(ctx echo.Context, cluster string, namespace string, restore string) error
	// Get restore
	// (GET /clusters/{cluster}/namespaces/{namespace}/restores/{restore})
	GetRestore(ctx echo.Context, cluster string, namespace string, restore string) error
	// List providers
	// (GET /clusters/{cluster}/providers)
	ListProviders(ctx echo.Context, cluster string) error
	// Get provider
	// (GET /clusters/{cluster}/providers/{provider})
	GetProvider(ctx echo.Context, cluster string, provider string) error
	// Get cluster
	// (GET /clusters/{name})
	GetCluster(ctx echo.Context, name string) error
	// Get user permissions
	// (GET /permissions)
	GetUserPermissions(ctx echo.Context) error
	// Cluster resources
	// (GET /resources)
	GetKubernetesClusterResources(ctx echo.Context) error
	// Everest API Logout
	// (DELETE /session)
	DeleteSession(ctx echo.Context) error
	// Everest API Login
	// (POST /session)
	CreateSession(ctx echo.Context) error
	// Settings
	// (GET /settings)
	GetSettings(ctx echo.Context) error
	// Version
	// (GET /version)
	VersionInfo(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetKubernetesClusterInfo converts echo context to params.
func (w *ServerInterfaceWrapper) GetKubernetesClusterInfo(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetKubernetesClusterInfo(ctx)
	return err
}

// ListClusters converts echo context to params.
func (w *ServerInterfaceWrapper) ListClusters(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListClusters(ctx)
	return err
}

// ListBackupClasses converts echo context to params.
func (w *ServerInterfaceWrapper) ListBackupClasses(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListBackupClasses(ctx, cluster)
	return err
}

// GetBackupClass converts echo context to params.
func (w *ServerInterfaceWrapper) GetBackupClass(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "backupClass" -------------
	var backupClass string

	err = runtime.BindStyledParameterWithOptions("simple", "backupClass", ctx.Param("backupClass"), &backupClass, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter backupClass: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetBackupClass(ctx, cluster, backupClass)
	return err
}

// ListNamespaces converts echo context to params.
func (w *ServerInterfaceWrapper) ListNamespaces(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListNamespaces(ctx, cluster)
	return err
}

// ListBackupStorages converts echo context to params.
func (w *ServerInterfaceWrapper) ListBackupStorages(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListBackupStorages(ctx, cluster, namespace)
	return err
}

// CreateBackupStorage converts echo context to params.
func (w *ServerInterfaceWrapper) CreateBackupStorage(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateBackupStorage(ctx, cluster, namespace)
	return err
}

// DeleteBackupStorage converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteBackupStorage(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", ctx.Param("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteBackupStorage(ctx, cluster, namespace, name)
	return err
}

// GetBackupStorage converts echo context to params.
func (w *ServerInterfaceWrapper) GetBackupStorage(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", ctx.Param("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetBackupStorage(ctx, cluster, namespace, name)
	return err
}

// UpdateBackupStorage converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateBackupStorage(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", ctx.Param("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateBackupStorage(ctx, cluster, namespace, name)
	return err
}

// CreateBackup converts echo context to params.
func (w *ServerInterfaceWrapper) CreateBackup(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateBackup(ctx, cluster, namespace)
	return err
}

// DeleteBackup converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteBackup(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	// ------------- Path parameter "backup" -------------
	var backup string

	err = runtime.BindStyledParameterWithOptions("simple", "backup", ctx.Param("backup"), &backup, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter backup: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteBackupParams
	// ------------- Optional query parameter "deletionPolicy" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "deletionPolicy", ctx.QueryParams(), &params.DeletionPolicy, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter deletionPolicy: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteBackup(ctx, cluster, namespace, backup, params)
	return err
}

// GetBackup converts echo context to params.
func (w *ServerInterfaceWrapper) GetBackup(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	// ------------- Path parameter "backup" -------------
	var backup string

	err = runtime.BindStyledParameterWithOptions("simple", "backup", ctx.Param("backup"), &backup, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter backup: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetBackup(ctx, cluster, namespace, backup)
	return err
}

// ListInstances converts echo context to params.
func (w *ServerInterfaceWrapper) ListInstances(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListInstances(ctx, cluster, namespace)
	return err
}

// CreateInstance converts echo context to params.
func (w *ServerInterfaceWrapper) CreateInstance(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateInstance(ctx, cluster, namespace)
	return err
}

// DeleteInstance converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteInstance(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	// ------------- Path parameter "instance" -------------
	var instance string

	err = runtime.BindStyledParameterWithOptions("simple", "instance", ctx.Param("instance"), &instance, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter instance: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteInstanceParams
	// ------------- Optional query parameter "deletionPolicy" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "deletionPolicy", ctx.QueryParams(), &params.DeletionPolicy, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter deletionPolicy: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteInstance(ctx, cluster, namespace, instance, params)
	return err
}

// GetInstance converts echo context to params.
func (w *ServerInterfaceWrapper) GetInstance(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	// ------------- Path parameter "instance" -------------
	var instance string

	err = runtime.BindStyledParameterWithOptions("simple", "instance", ctx.Param("instance"), &instance, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter instance: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetInstance(ctx, cluster, namespace, instance)
	return err
}

// UpdateInstance converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateInstance(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	// ------------- Path parameter "instance" -------------
	var instance string

	err = runtime.BindStyledParameterWithOptions("simple", "instance", ctx.Param("instance"), &instance, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter instance: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateInstance(ctx, cluster, namespace, instance)
	return err
}

// ListInstanceBackups converts echo context to params.
func (w *ServerInterfaceWrapper) ListInstanceBackups(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	// ------------- Path parameter "instance" -------------
	var instance string

	err = runtime.BindStyledParameterWithOptions("simple", "instance", ctx.Param("instance"), &instance, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter instance: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListInstanceBackups(ctx, cluster, namespace, instance)
	return err
}

// GetInstanceConnection converts echo context to params.
func (w *ServerInterfaceWrapper) GetInstanceConnection(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	// ------------- Path parameter "instance" -------------
	var instance string

	err = runtime.BindStyledParameterWithOptions("simple", "instance", ctx.Param("instance"), &instance, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter instance: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetInstanceConnection(ctx, cluster, namespace, instance)
	return err
}

// ListInstanceRestores converts echo context to params.
func (w *ServerInterfaceWrapper) ListInstanceRestores(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	// ------------- Path parameter "instance" -------------
	var instance string

	err = runtime.BindStyledParameterWithOptions("simple", "instance", ctx.Param("instance"), &instance, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter instance: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListInstanceRestores(ctx, cluster, namespace, instance)
	return err
}

// ListMonitoringConfigs converts echo context to params.
func (w *ServerInterfaceWrapper) ListMonitoringConfigs(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListMonitoringConfigs(ctx, cluster, namespace)
	return err
}

// CreateMonitoringConfig converts echo context to params.
func (w *ServerInterfaceWrapper) CreateMonitoringConfig(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateMonitoringConfig(ctx, cluster, namespace)
	return err
}

// DeleteMonitoringConfig converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteMonitoringConfig(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", ctx.Param("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteMonitoringConfig(ctx, cluster, namespace, name)
	return err
}

// GetMonitoringConfig converts echo context to params.
func (w *ServerInterfaceWrapper) GetMonitoringConfig(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", ctx.Param("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetMonitoringConfig(ctx, cluster, namespace, name)
	return err
}

// UpdateMonitoringConfig converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateMonitoringConfig(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", ctx.Param("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateMonitoringConfig(ctx, cluster, namespace, name)
	return err
}

// CreateRestore converts echo context to params.
func (w *ServerInterfaceWrapper) CreateRestore(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateRestore(ctx, cluster, namespace)
	return err
}

// DeleteRestore converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteRestore(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	// ------------- Path parameter "restore" -------------
	var restore string

	err = runtime.BindStyledParameterWithOptions("simple", "restore", ctx.Param("restore"), &restore, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter restore: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteRestore(ctx, cluster, namespace, restore)
	return err
}

// GetRestore converts echo context to params.
func (w *ServerInterfaceWrapper) GetRestore(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	// ------------- Path parameter "restore" -------------
	var restore string

	err = runtime.BindStyledParameterWithOptions("simple", "restore", ctx.Param("restore"), &restore, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter restore: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetRestore(ctx, cluster, namespace, restore)
	return err
}

// ListProviders converts echo context to params.
func (w *ServerInterfaceWrapper) ListProviders(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListProviders(ctx, cluster)
	return err
}

// GetProvider converts echo context to params.
func (w *ServerInterfaceWrapper) GetProvider(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "provider" -------------
	var provider string

	err = runtime.BindStyledParameterWithOptions("simple", "provider", ctx.Param("provider"), &provider, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter provider: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetProvider(ctx, cluster, provider)
	return err
}

// GetCluster converts echo context to params.
func (w *ServerInterfaceWrapper) GetCluster(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", ctx.Param("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCluster(ctx, name)
	return err
}

// GetUserPermissions converts echo context to params.
func (w *ServerInterfaceWrapper) GetUserPermissions(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUserPermissions(ctx)
	return err
}

// GetKubernetesClusterResources converts echo context to params.
func (w *ServerInterfaceWrapper) GetKubernetesClusterResources(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetKubernetesClusterResources(ctx)
	return err
}

// DeleteSession converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteSession(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteSession(ctx)
	return err
}

// CreateSession converts echo context to params.
func (w *ServerInterfaceWrapper) CreateSession(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateSession(ctx)
	return err
}

// GetSettings converts echo context to params.
func (w *ServerInterfaceWrapper) GetSettings(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetSettings(ctx)
	return err
}

// VersionInfo converts echo context to params.
func (w *ServerInterfaceWrapper) VersionInfo(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.VersionInfo(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/cluster-info", wrapper.GetKubernetesClusterInfo, options.OperationMiddlewares["getKubernetesClusterInfo"]...)
	router.GET(options.BaseURL+"/clusters", wrapper.ListClusters, options.OperationMiddlewares["listClusters"]...)
	router.GET(options.BaseURL+"/clusters/:cluster/backup-classes", wrapper.ListBackupClasses, options.OperationMiddlewares["listBackupClasses"]...)
	router.GET(options.BaseURL+"/clusters/:cluster/backup-classes/:backupClass", wrapper.GetBackupClass, options.OperationMiddlewares["getBackupClass"]...)
	router.GET(options.BaseURL+"/clusters/:cluster/namespaces", wrapper.ListNamespaces, options.OperationMiddlewares["listNamespaces"]...)
	router.GET(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/backup-storages", wrapper.ListBackupStorages, options.OperationMiddlewares["listBackupStorages"]...)
	router.POST(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/backup-storages", wrapper.CreateBackupStorage, options.OperationMiddlewares["createBackupStorage"]...)
	router.DELETE(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/backup-storages/:name", wrapper.DeleteBackupStorage, options.OperationMiddlewares["deleteBackupStorage"]...)
	router.GET(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/backup-storages/:name", wrapper.GetBackupStorage, options.OperationMiddlewares["getBackupStorage"]...)
	router.PUT(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/backup-storages/:name", wrapper.UpdateBackupStorage, options.OperationMiddlewares["updateBackupStorage"]...)
	router.POST(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/backups", wrapper.CreateBackup, options.OperationMiddlewares["createBackup"]...)
	router.DELETE(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/backups/:backup", wrapper.DeleteBackup, options.OperationMiddlewares["deleteBackup"]...)
	router.GET(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/backups/:backup", wrapper.GetBackup, options.OperationMiddlewares["getBackup"]...)
	router.GET(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/instances", wrapper.ListInstances, options.OperationMiddlewares["listInstances"]...)
	router.POST(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/instances", wrapper.CreateInstance, options.OperationMiddlewares["createInstance"]...)
	router.DELETE(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/instances/:instance", wrapper.DeleteInstance, options.OperationMiddlewares["deleteInstance"]...)
	router.GET(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/instances/:instance", wrapper.GetInstance, options.OperationMiddlewares["getInstance"]...)
	router.PUT(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/instances/:instance", wrapper.UpdateInstance, options.OperationMiddlewares["updateInstance"]...)
	router.GET(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/instances/:instance/backups", wrapper.ListInstanceBackups, options.OperationMiddlewares["listInstanceBackups"]...)
	router.GET(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/instances/:instance/connection", wrapper.GetInstanceConnection, options.OperationMiddlewares["getInstanceConnection"]...)
	router.GET(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/instances/:instance/restores", wrapper.ListInstanceRestores, options.OperationMiddlewares["listInstanceRestores"]...)
	router.GET(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/monitoring-configs", wrapper.ListMonitoringConfigs, options.OperationMiddlewares["listMonitoringConfigs"]...)
	router.POST(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/monitoring-configs", wrapper.CreateMonitoringConfig, options.OperationMiddlewares["createMonitoringConfig"]...)
	router.DELETE(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/monitoring-configs/:name", wrapper.DeleteMonitoringConfig, options.OperationMiddlewares["deleteMonitoringConfig"]...)
	router.GET(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/monitoring-configs/:name", wrapper.GetMonitoringConfig, options.OperationMiddlewares["getMonitoringConfig"]...)
	router.PATCH(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/monitoring-configs/:name", wrapper.UpdateMonitoringConfig, options.OperationMiddlewares["updateMonitoringConfig"]...)
	router.POST(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/restores", wrapper.CreateRestore, options.OperationMiddlewares["createRestore"]...)
	router.DELETE(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/restores/:restore", wrapper.DeleteRestore, options.OperationMiddlewares["deleteRestore"]...)
	router.GET(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/restores/:restore", wrapper.GetRestore, options.OperationMiddlewares["getRestore"]...)
	router.GET(options.BaseURL+"/clusters/:cluster/providers", wrapper.ListProviders, options.OperationMiddlewares["listProviders"]...)
	router.GET(options.BaseURL+"/clusters/:cluster/providers/:provider", wrapper.GetProvider, options.OperationMiddlewares["getProvider"]...)
	router.GET(options.BaseURL+"/clusters/:name", wrapper.GetCluster, options.OperationMiddlewares["getCluster"]...)
	router.GET(options.BaseURL+"/permissions", wrapper.GetUserPermissions, options.OperationMiddlewares["getUserPermissions"]...)
	router.GET(options.BaseURL+"/resources", wrapper.GetKubernetesClusterResources, options.OperationMiddlewares["getKubernetesClusterResources"]...)
	router.DELETE(options.BaseURL+"/session", wrapper.DeleteSession, options.OperationMiddlewares["deleteSession"]...)
	router.POST(options.BaseURL+"/session", wrapper.CreateSession, options.OperationMiddlewares["createSession"]...)
	router.GET(options.BaseURL+"/settings", wrapper.GetSettings, options.OperationMiddlewares["getSettings"]...)
	router.GET(options.BaseURL+"/version", wrapper.VersionInfo, options.OperationMiddlewares["versionInfo"]...)

}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7L3tctw4sij4Krg1J8JSn6qS3Z47e44mOiZs2eNVt91WWPbM3dv0jlEkVIU2CXAAUHJ1jyP2IfYJ90k2",
	"kAmAIAmWquQveVzzY9oqkvhIZCbyO3+f5LKqpWDC6Mnx7xOdr1hF4Z8nZaMNU/aftZI1U4YzeCBoxex/",
	"zbpmk+OJNoqL5eT9dKKZusQPeo/eTyeK/bPhihWT419wgPD666l/XS5+ZbmxI7m5n3JthvNzw6ruP/5D",
	"sYvJ8eQPR+1mjtxOjvw23odpqFJ0PVgUDpZazGOlJOyqYDpXvDZciskx/kwU07UU2u6nu8qKaU2XLA2N",
	"wRw/NQumBDNMu/Weigs5nPNteI3k+B7h9sX+5O7hS5gmdVJGKrpkJyXV+mda4UcFqxXLqbHwMKph097k",
	"9jSIvCDuY5Lbr4k9TE3MihpCFSP0kvKSLkpGuCBmxfw655mYTCfsHa3qkll4L+vvJ9PJsr5vYR5OcrDS",
	"7pl1V862x4Lz6LNrUSGGXgpWr7c5wBdMy0blHrTXnKIKb/ePMgB0SAh53TzjZcljyImmWjA1mU7ezZZy",
	"5n5suDB/+qNdZsH123P+G9v+i4pVUq0frg3bepoBgkevzZB7TAJ4HoT9vZ9OclrTnJv1v+leT/z2Bhjn",
	"H0yj806h2TMpuJGWOE6kuODLh1SzIYKl3iK5FIZyoUkuq0oKcsFZWWhyIRWpwvv2rQu+HGChcZyEiaay",
	"C66rKlqfI9d46/otr2cSFkTLWS25gLvE8pX300mjSuCRXDxlYmlWk+N7Nx/skil+sX759HwIiL/5R4Rr",
	"opkhRhImdKMYefn0/Oj8/CmBr3lO7RfzSVjFQsqSUZHm1in4/p2b1c/uZqRl+fxicvzLZp6UPMv307Hr",
	"truzB6TRTJGCXXDBCoJAA2ZsWbRlvJ5NOz786OdzfHwhVUUNWRlT6+Ojo5YZzbk8KmSuj3IpclYbfSQv",
	"mbrk7OroSqq3XCxnV9ysZggHfQSc/+gPhdCzki5YCeiuYy5v0WTGhTZU5JaVfozzHp7H6+kW6O+PZycy",
	"IHa/CDUqCrzqagpbuRYnThSjhp1RRfF2ujlOBMyyuLHLx2fPnm0BnXihLXRq+zczTCFocvuSBQxNMouY",
	"lxm8Ni2JTxF5XyfAY9d2Ld86e/asXdHZs2czXbPcUutuzMsyq8GFQmv+E4OLpkVXWvO3bP2REHU6qanW",
	"V1IV3UnCrx/APjWK2dHKi4qLyUejqcQlljib85rl2zHIV3XxkYjhExFBvMBRImjsS2NE8H46+dnzB6+3",
	"bC/WPj99dIIrSSgal0wxbYh9h9RKXvKCKTdto+DiSigAnAlzWgxHg1FoXZfuziPu1UcD7Hk/nXCtG6Ze",
	"vXg6Mk5YDVL7UM/IZZ2SgOFj93B76X8gprs9xusMc6akp3Nm7PnpcRgvS7mgpRUV8MU+XCUv8vacNuFh",
	"dKL9hUeDJFcZ6yqDlcZPCT5agALG+uhKnYYWqWz256sVz1fkjCnNtWHC/E2WjVXhcirIgpFiLWjFc1qW",
	"azxezaVgxTwTmTjvKF+g7wkpZuFeLP4M60hJIbgUmudSFZZqrCBm8sLKZVyQ57D5Z8zQuSWi+VALKkt5",
	"hSt9/K6mQgMw+rBJvUX0Sl5pcrViZsVUak32I3IJXxFmPytScqDVDgwtqKGpM6GioKogeIh3NPHvzskz",
	"qRgo6cdB5FpyM3/7XyBvWSGkEdysrdBlFF80Rip9VLBLVh5pvpxRla+4YblpFDuiNZ/lUlwyYSfW86r4",
	"Q1jUAJFSfPmVZupEscIOQEs9vBXjK2tAjfbaGTH+jE12xlTFtT2HxGRMWD0nniuCdt39cmj0uZanbmQe",
	"fu4UAf7N0kYKvzyXuMQX0raXi6YsT2RVcTNc5Q6yg5J2OT8nwb2TbuS3cmPRIAZbvKx29Gm86RREc1Xo",
	"fzyk+dumHkIVf7ecwBLnOfBP4FT2zwU81OTB2WmCK9R89KwenJ26Z05JwuHdkq3KhBMBn+KaKFYrppkw",
	"eCvKC0KFo+d5Js7BVqktM2nKggARKkMUy+VS8N/CcNoyNjtPSY3FFACloCW5pGXDplaNyERF10QxOzJp",
	"RDQEvKPnmfjEPCM2Ng2o6C0XCanhJy6AV1OvacJaW6ABS18x8uLx+ctgzELAIgzbV3UETgsJLi6AL3NN",
	"LpSsYBgmCkBDZ0G09zzRzaLixh7UPxumjYX0PBMnVAhp7MUF0hlcVKeCnNCKlSdUs08PTQtBPbNgS8Iz",
	"vjUGdGH1mTGCsNJ1B3ULpi0ZEm2ogfsV3xuSBdJMMFiOTRBe8KQX/YwGXT/7Sl7hAQVSzQR7x/LGwpu8",
	"XLmr9I4m+CuX4pksUNdWssTRVSMMr6yUYlbH5Ee5yEQeCRKWDkTOS1aQxRo+4GLmzaNu3l/lwo9ZMvXn",
	"TJw5+fMZFXTJCrJ5QC+t3tF+MfPUieUjcjiKbB5YCOQZbKkji1vS4ICKhC6tGgFYnIkIunc0mdujn+OH",
	"c1kzYfnVfWR+80lKH2sNNTOgJHXJZo14K+SVmKE6HLh+wUpml3ImS56vuwqXt+C9YFbHmUwnj+zLoKRv",
	"egga1AVtSjM59r/2lapHnWnb07+yuLSidc1E4I+NKJgq15ZvICSJJZJMHLD5cj6FVxzjsNIaK6yUeH7/",
	"0MpxooOLJy/sicCOgfhxbeTArfaQ2BNQTW50BwfsOhSr5CUjC2lWeERMLLmwGq/hl/6EW25GRYF0SA0N",
	"3g138qzwB+xk5DlBGF4//RYzLxqwXJaM4vsx9NxqMlGXNGdToiXhxgvzlgaszFLAfaSIbMxMXswWVsa1",
	"Ar0lXcAdC8OqMeC4kYJQUtp1OBDb6ZE7/8YEkSJnxGNYJlZUW46kDCuOib7iJl/ZZdUWB7glxQs78TwI",
	"xP7Ll7xi2tCqxiEWjAmw0MJVbA/ecjrpLgBGRVMD57A7swxf0ZyBeS4T3GhWXiRJ2dse02zwNHrqyTrW",
	"XfxzC3t7JKSpkduFB1WjTSYAVg4htP0+KETECgQtss7TOvKKFU05ssbz6OkUsV8zMyUcZPgL7u4GvyKH",
	"g+4j4OKZqJUsmpwVnaW4/2o07Vnpg1MY6sHZKZGKvLH8Jjcl2ArWbzLhsc9iAqAMq2qzJgdSzApWUVEc",
	"InAiLltxpdBIUkpZZ0Izoy124jYadUFz+9DeXdRINQsL9TApgvxH/cIzcfJCpwGJlDcCx/YhUeyCKSZy",
	"i52kQ7Ujp4hg9Lfh1YopFt0BjgQ1uVLcGCbm5K9SkZGrKRNwF/oVFEEZtahEaKkYLdZIukurn1valaKL",
	"jpecZgIvEFzB3A2iPcUgOwEuYBcFGMxNAmo98b4vOfQoqAvjlKBvZZNGj4o08LQj1MgF3GRbSDW5rGpg",
	"8g9M6m4ODz0lw83srotwVGEQops8Z1pbxWVtJ0O3yOR4Yq9uuNZHZIOCm4FSOhAU8KXWkljYy6BEu4wU",
	"li/U9m5zjCZvlAIR18MAqMwSoncdDsFRUm1eKio099x0uJDhOx449glCyN1ibsEmvM0KFMftavFULRJR",
	"Ic0KvPkv7RKdOrSIAB1dTe2w+YqKpZUVyekFipZcE8vGQXyB616QRnstont0Fg7IcdwwoIjkOavhvtr+",
	"8KKQjC6c3ANUcFZNRQWxdAi3YXgmCrCY2ivXHSZdyAZVlBZsHjJWs1lYmcGxSVyFXWtF33nfwv3v/48/",
	"/VdioZ4onjDBnIF3sObhO5GKBYtq79xl+w4Av3vmVxR9owuqWUGaGjZhWZin/SnhF+nRuPa4W67Jve+n",
	"KKnYuRFl5i29/PLu9TyxZq7Jf097C7JKYwPEYY8zE+CFUwxJxsmPCZJhYcEdlEBHPfh0eGXF27sB4lY7",
	"X2JskGJUp8CMv7eETO39tlS0qqjheXsNqxhBkMXDh96OEXZ3Rzvii1HmDC8+hcZa7+SKyNLqmIBTyDsJ",
	"e1ejiIQ2A5BNK0YFF0vt5vT39DQT9mlsAPUfKViXtteU1VbIsqGKCsNYAfYWlA9R028pnbbKtcdqh/NI",
	"pHaVTiUH1O/h/L273/+x72CrqTFMWXD/3788mP1vOvvt9YH7x93Zf/9jevz6u+jP14d/+Y/0/Z++exz3",
	"8rzWA3UKrE1ekJeqYVPyV1pqNiWvUKOyi/bKkH0+mU7ghcl04t4Yhj8Ek2N/AfZXO1GE4ZGFggClkQsp",
	"586fN89lddRaMHo8496fOgA7+AXB8vrgl5n713f+p8O/HGTZfOMLh98dHf7lIIL2619mLajnr787/Ev0",
	"7PA/rhUhEvdSy3kDnYXTcsOlZImO/banAZdcm1lF69lbttbB6/w69ZYbpqK1HbRjoEhYeDv2C3dZWj2s",
	"tDJK+JhU9rHjpOEa9QKqU4esCphLVdib1F77wPzogpccicLjV09SnEwnP8pFEr1+lYu0dPsjPmgX7MRL",
	"zy1/lItw7apGCM+knPiYiTNZNyWoAVKUa1iv/cYJrUlx2x708y0uqqfJ9zqCSBACo6vFkWvQ8pM8fcjH",
	"R+/4Z4M7fja449sLvXO9JLfvlRZc4At2kfBy9l8hYNTUHnGC3jOi9oNloHX4Oj3NWUjOmMqloGhJfSbF",
	"Uj56iBMdzkn3ODNxMa6QJK3qT5RMWeofnJ3CE394S/jDX3GtuYJZ/Gp1nHkmTi9I/LG9H9w1xwq8/sOf",
	"BGzNoA4t2ihSqVAQhCmdfELFmkh3qXFVzGqqzBrvymlnOs+f5rsbvIHAHf8e3WBq2HTYVsrUsMOwPV4L",
	"S/dBNtfYDC2z9BzVyIrncGW68Miersx/C4u0b3hajNVdCh4TafmcN6+i0jmimgNHTGlu5/7RRr3Ns9St",
	"ZX0g3ORsJuwtKUMuxiw171Me1vg0wJh/jfdrxKkfW943+cG8ffvB2eneGbZ3hn07zjAgjW09YvByyoC0",
	"0a8TVDw78nP0yJDL+540XKhNV3IC9pOJrv8HTROeL1oVGdbjDVuR4wcpIG27Da8o56FIuZW4dssb7rbn",
	"U0pKJ/ELnu8Md97l/rkH7g4eqVR0SGcxvw88SeEvv67ohbEVDdCt4Lou6TotMz9qHyaFQh8svd1UO+kV",
	"mpUsN5osmLliTJBf5WKG1herqXuJb1Y5SS2MfTOtwVtFTqTQRlHuUr3SvpDopUBquaxqajhqLl6Yqpyd",
	"iRovq2VCU8M1yHCLtb0xgsV6wS6kciwwBqX3UzV272DmQSt1F5X9JftXh1P9tb/oPI9tNaVLWXLhwvFq",
	"0dnUs6wDbWbiMc1X5C1bI178eP78Z/Q9sXcWzyEmCcdy8ryRhHo/WnpEK6467X5KsgkyAScw2QPLJkSq",
	"8MCyyHO0+9p/nlZW0PLOYi0rBjvNJvPdgicHNPirXCR1yRaErcaLRk8giA4y/5DZL7LJnDxzgG2EZiYT",
	"IMIN9Omsj7i4i370Kjj8fpSL8+SdcNJ57jmEj2AKBrRWeAkuxF+9Iqwaod0aXeikvVadtikVecHA79xz",
	"L6ecEhVNyQgn+CCImu5PI+3MSZayfWAbr5Ia7mnl9FswhcIf2zHKFGq4yIte/F7/GPrvoEkRf55BIG5B",
	"MBrgRVMyTZZgXkRfI82EU/dZQXzSnCzRzx79/ZCLwpnOR/wt7QxkJS2dW/nGKgnB4N3GyVL0TK+Jaiwp",
	"LhpDCslQI3VYH3+eCbQJXK2kC2KxC6zrEhyvkoR42thZOHhtXMfW40q2Trmkg1YL2+qILEGQRS9L1ZSG",
	"12WkNePpRGq31Z9p7lwHIEdGwgUaR9Fdae8cd1BhFsvp7ABheHLFyxIMxGUpr1gxJ9kkm/SdEl1FHs46",
	"m3zXfY+WZbTqHWhjg/mv1XmFFN6r9urF08QB/Nx9wUn6DC6SmirDaUkaVfqkV0zEcrrQil4yEAA1nDsh",
	"3yHUHUwQ4cDERhEeF01ZTskFB75lWO0vEHvfZOKc2ztESCuWODUCloSR16bFOjCiBBO8VTRgDgzzt9KM",
	"5dsRUenYBQ2aBk3RXCaQbu01zTiYWiAcwKK+PaEWGw50k6/sprJJLQvt7zPNcsWMziaH9u/+RmCXnW+t",
	"TpFNDqcEAAXKjDSrj40Cfg1R6nNXnogew/GL9nK5svpPECyi7OcU3RPyIDgAmQEPjXubXTK1NhAqw3Ug",
	"mU+0zw17dOjt99MeKNoB+vu5892dPqW2fOcjr/6SqYVO5nQueqvGn5AcA3o+fYpKuFueVdqDbMicoOa2",
	"mNwXTP9x99QzGOEGr3V9oKCWloR6ItBA8olufyxWAELNr3LxDYky9SYZpi+8BI66SXxxZi0rTNaywHgc",
	"SlppJogxe/llL7/s5Ze9/LKXX/byy7crv/Q+88JM6sO6Z9Uc3pV9L7a/QlZgiUuZp4YGJ/JyxTKhg92b",
	"C4M+DMh6lTUTx8EKi34ZDFZmJKe1i+DIRHxLO6e8D7I6O30JdiPd1OgjnYaQ5siImImC05Ll5hBsn/ae",
	"vpAqxwzzkxePXLxjz7IGvtFMJCxraIcbRoryiqdMvk/hd7slzPCp7HXoI4mnsIeZS5OMfrY3nt+LJjVT",
	"mfAhzLHFF2PV8tJyeggJJXHAcpTGkTunZybQKm4v3lewT2e0tUyHZJNGwD7s+ZEDbexdrRv0pvmQQKlY",
	"Jp7Rd6cW4UnOeAnhcFL0w+NrlrtgdZ+UxOxZIttgmmUCgAJuF0uThRMR0Td9EEIynEsGgijZYiXl20OA",
	"D5q77fHqmrqEiBOfKYJr+HMPwWhROAd6KHIBfqVgjLezyxosZydSGPbOzCNvF57lweHw9Cv6zp7kYzxI",
	"F+eewIZnyfe8DFfRd7xqKoK1kKKUclhYdPBW4KIGaYYZMq+5UXOHRT8Y1YSoKQixhxws8hj27RigIxkr",
	"UGsuliVDYtJGMVohnZGz82ePHk7J2f86OQxIdo+smOoNlgnwV14y8vcHTyHl3N5aELjgR3pySKLEBiCw",
	"fqTR/e+vjR6t6Dvvt9NnTDnoJYGceG8cyIrljQIXcyC5TLjL1tJe5GdwQzFh1PqGO9iEG9cjhJ0ZEn7c",
	"8rhoXZvJZIXNq7w3XGVSueNGIWmN+Tkt+sRv9Iom6BXF6J6aqZmHIqBc3mgjK5filYmDHhPBV+2bcxze",
	"sZQgwl4oxmZ2g8ATZE3/2VjykHE25J+7WWHex6tJCnKwrEzUdF1KWuig6nBDOETxkr+57w88e2NWW2ei",
	"sOiCn6E8mImhn/dC0WUFwQW4xFenIDcrBuybksqzMrsn0AQyYa+M4K8MgcvuWrNTgfJtTCf26mZJjY4x",
	"aAuERGBP9NSHYrO47EO4avw46LybcYE5nC5Vbj3PxCuNHkzvA4rZvL233O8DX53FRVdobNtKYs4iM1b6",
	"5UX8eMcIBTf0TiEKnZ3lId81hB5k4t8i9sCB5seU+/NFeHaNFzSCMViCeF8oG/GMkqRjNBN7z+jeM7r3",
	"jO4ti3vL4t6yuLcs7i2Le8vi3jO694zu5Ze9/LKXX/byy15+2csv37RnNLgSvZVIjxpBo3dCmrWDZ7A0",
	"d9C7l5WRCW8j7Za7QrNgGAIrFtU1oyrAHOZx1jFX3w+qZzHSaF9cDCY9jUp1bC8UNXzMovjq1JkSw83Z",
	"mt/Rgm0JsnUSA4dWUhgmID2/8h6jUNHNgWTqZUN0fYJ9GaorR85OX7kmGFKxcoZ3LhrFqNExG6fa+QP+",
	"jOzcm9ul0FCLmRvno44N+OipcBe+c4661NtKFrR05jvYLJx65crpkcwVdsomU8vFuVH4L7czYMttrS6P",
	"PHjcHuQfaL/vl9/tpEvtXkkK8wG3Lyc1nhK4L+e0L+e0L+e0L+e0L+e0L+e0L+f0dZVz+nglOXzHllFZ",
	"A5ofOoXRRZ0N7DReyAbDyjuuTVvdGMRC/eUq2JOPWLODXFOyg3zJih27NQcdVGZJ6ByfoQYI+VglQMiw",
	"AgjpFAAht6f+xzZd7qA4QxWiJ/g/Gyz6zAWhrYlsTk7bGk8oaIZ+ZQFZpoSWZiWb5YpoWUVGVQy/hCYw",
	"1MMWqnMDWLHOVacsGRVW61WyVtwKK9gerjESRAhalus58UUlasUrqni5xhBjXwoOV2cvjoJVtTRQqs1S",
	"VjdKB6geZYrUuX1g574/+HZ929Q52sRAN/HOD2Sbe455iznmnlnumeW3ziyx+B42BU0eCHoOY26Ev7iD",
	"QRcjo87P2Du+eetkaL2QXBN7epe0dMC3g2a+O0c2aV9F/T1+5B3VVEhhwd/jgJ8CcnYhH+OWGY2p7xXw",
	"39RFysew75tJ7evnfWPNpBD1r6+g12uIAV1iHpABjVGiGHp0ppGrult4uJX50MsgDows6Bo9Huf3Z76s",
	"WMkOSV02jjW13QmJYKxwMSW0fOt6WGTi1DWJCV7uxdoVa1OyOrYLJmRGNqae/PLa//MFu8D34+p8UZcL",
	"O9wjlsumLiENxzfStMjFRcEvedHQsi1TbNHwLdODIm6Z8J1MXOLRw2dTUi/tdy+YNoekVjSHK/G4mxKC",
	"KRjYC4TQTFzwd/a8MGghTsKK+n74bELwHtWNJ6jKxQNkwjX5DKJ3u/whX9T3E47G+60I3znJtrdmfDnP",
	"M/GiI3G8XNcuZ1HfT4W5Y5zFT2yd6mD7IDx8hKgILU5mgFZIThxQkIu6MXPy99Azh/osPUxZBD+bj8o4",
	"h3AGwCNAqKhLJj762XcBz0tGFfRx8TbSOUGUFOySKVK7zqqhb0uXeNwtkKLuRZO/ZSlVCn5PBQ2d3yf4",
	"UbqRWWoPCf9Wcqup2RBGyR45Lu8Po7TAzfP38388ODl5fH7+j58e/1//OH0EwLO/nj8+efH4ZfSQvGXr",
	"kaqKjnUnOxA/bh/61QZWb38LMOrgpxVY8kSV4p6tsc350dA2LTib4jUFcY1iigzBDsSqgZ7cXL968fRA",
	"s/LicPL+9XvwYeTsjJrVuVmX7iBcS7ULMFf3NvjXzvvEZajW1KxmGn6BiKEDxAA8qU6MERfaMFp4QKyk",
	"Nodz8gjnBOECpk13u7U8JyUKvYDf20rzyyiecjM6YsRQoN4EV+m+sA1xnzNGIn6QnPeSKX6xfvn0vANx",
	"o5oBwP/m3ySYsaqJ/Xdu+RKEjoLEF6JIodlcC0s74EjaV6fFEhL5GHV2cT4cw7hBvQ9Ez1p7HfQs67Ef",
	"zMnL9hJG9ttJVI89Jfp+wivyPtHt/yadoFAe2caD3xdJJh/D6u8G22S7il75EBNWlO26t2TdTkuW1y33",
	"Bq29QWtv0NobtD6xQcurpuNVuEfMWD4gZt8AYm/A+mYMWJ4mrrddBbpKN0Qfk/PaJs5xZ29ywajdZBt+",
	"FSxKaFJwRW2mmEgT9xb3jcehGMSSX7rAx9BGLO72AuWUUPzIBIiRbQPnNhQ5su3QPJeq4GJZrsmB5gXL",
	"qbLX25IJ0yvzMCXM5PPDOQnGl1QfqGg1TP+525i9kJiMwqA1ARaXgTo7ZMFy2mhY2RqiK0nBFctNuQa8",
	"tcpnwjiWKmhAtU52zzpxT+J2vcku9R1zmWNJsDQZR3NHHYrajvV4PUFqT7d0Q78UA8TcwfHE1f3vtHY+",
	"q3lbehyG4A/3fH1rqHiP9u1595QSxQSu7+0rxnr2OkROGViw+JeRy2W5G3GAYQGTAHwUvH7La90vg3Vw",
	"GNqqK+Z1KKuPQs90qM22FLLbuisyUujRkkWhXpG3nequFtkzmc4J9HxABK9orQnNRCmXIFOAIHNwyTVY",
	"kEynxbJdvWKNqxgTmYGjJs2ROfkQe0V0TYL+hpiTUByqzTWgKqre4qo+eYXet+wWmOA3153PsR4NRuFv",
	"yLFMljWKwNZfbb8bNVziOVWKd1HEZWMehEVhSblDR7RULbEb+E3oo3My0Wk0ljgCTmrfih/Ns7TUEpk1",
	"XtewjujEcEkA1MG59aI2/3Q/cbdZcKfLTwVzUizls7EKRGDyAhFCwj5Cgb3AyBOMUBJaWCGMa18wDRlR",
	"jIe94orpwmsuvzBRfM1nk8TV1xyDIdSQSrrcUj2CKEYSaAwyrAn3ZzwvqwhgHb7QU84veYoxyGuXV2Rl",
	"GCexHpw9ISVbcsMraphdOpZ8092abxEFKVbLw53bQ6Fle1jrCgCEOYQuXaqtK4nSit0M4l18Yi2a9Y/l",
	"Qwtlbc3PQy5Th1quN2H6CZJmP0/tCZYcuFPLXNoCd45rGKrfOoQMnes7y8tEO06NcfYxER94nhgJZG1q",
	"UyllfYiZKXgi/RacfvmK/H//z/8bF2pzzh1d0yuhyYmS4ke5AF4D4f7jElXL1F3OXc+gQXMlNVb1G7jz",
	"kklyG7m3nypiMjQN5O79hy1Co3pPgeW8jKUryHIAZQ5V/FDUlLu6dpnA8e5YuaUH0Yh7OBC9pPqtFeuB",
	"mWTi7H+d+A0U3f3ErtIw4uGc+A6rM4cJkZvVikh48JYAaf4W1xihyoDF6BVVTnXLhMcMB7M7ThDblW24",
	"Kml2vbM4EyQy9KQau7FMRFh0R/sbyQ2Fg897ddac7IVVxrrNYy9oWWKSJ7BEvC2dGWXAtoJ3jzoET3Su",
	"WzTGpQ8XWDnRY4KiLi+FCnjgGuWpRnwwY8tVyrRhadEr41QUVBXkf85cgpl91Nbb7SFza3jIRLezV5An",
	"QgEJdznOJ/1cl4TLcgdp2kNtTh6QgmtXazcQleWPlbx0uXu+YkPHxV9KSLPjvl0bJqQk+MdQeN4gZiFv",
	"KtdtQlR/vR1IgtjFjat8gJWVYQdv2boXmmAlIFcgAaWwEH3QxXCMvZCipeFIiyQ/j3NS0mOkCLUYEj05",
	"7przVMzVhj6RNU/n23deCI7zuIir5aieMRlJ3jJWh4u3Bdec/G+mJDmQCmn40JUVyCbwAS3LbDInP7Ml",
	"ctY27SsTiMe9BrnbVH7tXe1AYi0ST8e1xsrVWZ4c37s7dJu00TWjqllPte+rGckog026gvPrTibTFEY7",
	"55yb0HRz3KzgeXHBcgvWMnQ4dDU9igaEEHt8V1QV/XaIPKrIi5numCYXUE4HpRYSxyD7MeSRIg2ARQXO",
	"kZYgRudMGcqtIH6lJGTkfXw79tHWCQDXd5JOmRo6SLArBvXR0luJpuPC59YBHHoLeazDRdqQjv+xohoi",
	"OkIk2SH5179I55c5LcsDfW9K8OV7rVaO70Y/4Kv56t60N8QFLw1TB/r7KYFBvo8HyZq7d7//E/4/iR/N",
	"wfWs7YjfQ8H57+egIP/wg/3jHvxxeDjX/Dd2gMPcz38g93oDxuvz69g0oB/vhx/IvUMX6dK6W8ExUWCe",
	"JC3POrS7kyDlqxuFUls4AUkLVWNy2jOabtX/VOa0fA6I9CLEMLb1XwV4DjvFpyQpmSFr2ZBSQmgIGrva",
	"qERn6XeVmfe87GvhZdPJWwxOGglg2uPPHn+uuQuHbl8oJT9Ssjk88wI1xBpBmQypXBV6HlWY8azPJfTb",
	"F1Mmp74V5MR/h8qi/mB1bGOFwpZdU0HsCSiLxcGRDe8YaTWHeSa82toWsONosW1MCKuAkOfgEg2bcV5t",
	"bRV/3cbcemd3GHI+FuowogGF8gIe2JOkbgBV2JJKAT7pXVuxUuBeCPa3zlQDGT5V4mKLEmCdZt3pqQb+",
	"OJ4sggO/gwusDQzWncJi04B8HAE/94/w46mLEYaWMDouPu9KdynINoh4UcFqJgpvDsvEIwxb99t7UALr",
	"tOfs/VFLalh/FK4Jr6oGq8uQU/StgpXbdQEHMvNr2OQqeRHvJ1ZepHCdN+zWz2RhqXneeXs3NyDIpNBv",
	"oROE3ZmmlsU8AeVQ2vFMQjSUb7seYGFBD2DARAVXNMrFKNBLyksLKIgetiRLo+NJ0wAEIKS7sjPdDVvP",
	"V1IzrKJCQ4wVF/F1ZK8+QMJ5Jk4v8GqYxkX1Ag+AtwgU5ymilU8J1DS64hoMCK66lmK6KU0U3wJzf4DX",
	"dKdyFn6UzeUsplGrpjGZmYr18wtQaAYcYSCxvO5WFsmy//zXDKqD3J399+v/hFoiUD7k8C+H/wp//efh",
	"4cHBLz89e/Ly7PFrfvivX0RTvcW//nXwC3v8evtxDrGyS2fTXJiZVDO3RH+VJBtTdfu0+IYztJKNMFh/",
	"paobE8fy+WKLO4sIHd3hCFN2Qj1LPWuZw9Ek2U4CY3C+9XN74WOReieH5qeNJ+dJDok+DMQ1kdg+xvGM",
	"cBIgIhRR+L1DGt4WJGPv7BXLjZUdgmSRicAdXI4ar+oSLkg4/Jm/w0AanbdLyTG0ir3LGSvcbJ8X0d4n",
	"o+xHsmJbP/5mAQBLg0EIVcl09ERPg1M2LpKKCU/DJDH+G/v3RXMHZSwRM9QM3++WnNEXLdsbLVReHElj",
	"Scd2elk3Pe5AUt6yNvig0rlDi04IXjtXG5raIhkGKDk1xV6FrkSZ/wZFSNc6MZs4TyTWqFTy3Rr/iXbz",
	"BxDfNjkEbYHnqwhRYVTMv+oKjMR3FCRG1rKUy/U8xb7bDk5D2D4Kz/By0W1sOSWCXbXRDZhaKUL6h/ea",
	"kZMXGD4LfKd1RFgh9bmVTjZ6j7Gwd0jOcU29gqCE72bC2zCTRvOp/fm8yXNMpwVax2QOyzCj6dw414W5",
	"JULcor6PjTZWddcSw+qcx9n3kYRZRV42IFl2mtYR1zjQ5Cvm/UjueastMOIEVQdc16qsky3ri3SvGIEC",
	"h7uGg8ZOifY8W//TiGuin+Nq8ewH59oaWUI6H/NheJZKwrxuGdd7KDfEKV0fm+TaUHo52uVVu3q3qQBX",
	"rBK8a2xSy0XQjrSSQjYq1WeqoCZNtwF6Lq4rbAF2FgXF9jKSoUjlZPsypJ7T07J0V5/Pn4OlTScY/D55",
	"ba/AsUevp6mbAvmXhrqZM2ffUD6YPjSsm9wwR6+fmNii5I7Zhn6ZnuI8jb7lopNP6MoG3TCncGv/jmM5",
	"nieGlmvGHbFbRnDqgOsFHv7wA7mDT++Qv5Dg68EBD8kx5HiihwP6nnEpsENF+vxPqM5pYc/5uapXVHRR",
	"IPEUsMDbbtvnPdTuzAwSsZKlJleQf03rmgmgGscooNlGaNnmq1xHhRri6N22Sm+cieJ7vGXCrYkcuGUe",
	"wr2vGn/6oeK1dB+56Lt2LZZL4mK46F8ybUrQ1Upq5mJevGSBhhG8Hlz2fVgkNtwlhmEATyGvEsG9D30g",
	"j7wSnu10jxELF3OBYgSWwY3gixVXudGZiMoiA8bzVKo/16Ru1BKpVjEsTz/PBJ73OOiwIe3I+XGRibqk",
	"ObYOhc7Ul/ySdQ/NbwsDTqkAnqGwDDuIQxYD/DFARLJgV+V6BsINK7pSysseOqzAkIQbfslUxQUKRPWK",
	"akbsNkrXPsDLKV4W0kduJ9oJB4wJj13kwCEX9JPAUeL4tFZXbD81Ugk87APo1Qwhx5zpw7DuYPVy9j/o",
	"VkxKC7AWeRqD7Vrlb0wQGcMvEyuqrcRkxZ1joq+4a4HqZyL0wgK2rabsv3zJK6YNrWocAparmatcgrEa",
	"XnjJHVHV1Ky8mql8Sl0muAEmlLp6lqVc0HLIlZ/A763/KUStluySlb3ws9BcwTW+QaAb3qYYuOtdx8lo",
	"sUVx3OeAC4m7736w18GPPt4aPiU12bOxF2grKQa1o9ZVsXBah9RmqZj+Z2k1jeRl7xSJxE3onvRSlOpS",
	"rivMa3TPveC9lb961B3epp+7cUeiC29+dn5Dj9o81Ew8xpLG+hiCJQuSg0nHDgt/R6rW1Ls40D5PcyMV",
	"JiR9KAZcX/cgwBozN/xJuyX63gfogGFOq7RQCjZkPwJ3GtgIlNBa5SxU0z4A3R3ZrsYb37dTwK/V973Y",
	"RVv6DsYr98qiEUXJpk4yxyL+vhRKJtxbqLJbjh3r1N2U5jOmZq3iHj6EeH4uSGQeMPSthQLLWQHyhZVR",
	"MS0E1tIBWcj9CVTpiYcG6PktAJvCP3YB5PZRQd1mzt5whh48Xz+q08gevdfGXte9zIeUVgo5cpECu+hJ",
	"oW1oUbsICBg6GMih3Xid9olf3iFY28a3FjvE8L7TUJEkXoksi/ONi4kfDBcUzfbDDyQxGErRY0VCQs7n",
	"NvVB4tjOQeO+KAxp1KLlQ557heXb56J7h/hrMXYUdieuZbGpo8g+WmQfLRKijfqhs5ZRgHyxRQwA0EC6",
	"c5I0KBleO8r7Lbps7vvk7Pvk7Pvk7Pvk7Pvk7Pvk7PvkfHV9cuACFwwaAp+PBzGfDF/ytX6jsr5RJVDH",
	"Htyl577194SjI180FFXKWdsKuqdLz7wBNCqfAhzQm3IykU1+96xuZn95P7OzZhNgA/IqUtCDbe8AJvUm",
	"RsvRSkZFU7cWQrc+SGG7YmU5AzRHdzUXugYXkRv2HIuHEtdEt9tU/BjrCGdwJtmE2P/NyCOvNAA1BFNE",
	"JcVSJs1OfhQPl2xCZsFH3DNo1EzlUtAZXC9qFgYNg6ykNmEp/6fUBm1iipyeEVoUimkd5pOqffVMKuOC",
	"Vf3zRjMFxzCJdxV+9aNQra+kKrpvhV/9WIq7qciM/LUBy0NAn1cvTp2LGPCqrZK512BuqQYDhv+EPRb8",
	"AX0DbKQ8+5vmjAE5TaZowtVcCvzzVHB78vw3/PMFaEbTyau6AIFjMp1E/ge4qzhmLaKbAX88b3QdJnB/",
	"+Jeayv78+ibRNr7isMedns0tiPutoOjTpUNZj7ZmznMU+S+4co5dywC5F10TTBJqI2hvBXBu967JDHkF",
	"opcokMEBKrq8W+F8c7pZaPbPBspH9aYGXQSsR5ftrh2KAwkxoV3ZLOiX7tlUJpp6qcBRiPUArXCEWowz",
	"i8cLPfS1FXiJgDKKL5dQekZkohGheGLAIT+6jMIzAskBZ3/CzXPItZWlJgcP1FKePJqSv5bNu0PC3mH8",
	"iROQQN0r+MUFyWmZNyVaB6Fmh1vnFA16bVi6zwrHEli6bhSXDUjvM3kx02uRE1oyZbaLtdqpeq3fZntX",
	"P8LrdlPwaa8WYOItV96kHSBR6WR4xafE0TGRwi0zqhBuPy0So7pQz3DaQb0hL1dMA7ME/DdMbCNEgHvz",
	"p8DC/IUPBb3AKwqWWSiN4EaDjBq4UrFmjboM9gK/VF+SD9a0JhcSKoimZIS+TIEh+W3//qGJw17aw1Oz",
	"t7dnOqvkTW4X65ZIjEydjb+HE7zaPfEz+DfxLBqzsncwyjnJgaVKLBmkCD9gK1Fssc6tfXxtZRIMHhOQ",
	"9Y+Bq201wC0Vlo4LySkvAQud0OVkrClphbYpqdb6n+VhaqJG8USvcivhoE7NZouGl6Yn/yRHcpJWYjj3",
	"xC/dv7nV2V1bpDRdITt+eqPi2CFedF8X+zbWxQ6lNPclsfclsfclsfclsT9xSexnUnDU2E5G4l76b4yU",
	"yK7Ca4g6+2Zv+1rZ306tbH1tjewBofUpo66qhNj97Fkr0509e9YqhS29XdPyy4QA+7qqUj2/Pka3qoGh",
	"Wg8M1V7Be8vW2Esu7OsNrflPbP0GqpYF07N71+UDpmX8MiXjh6ZUUS8qC0fULD9apyKOXkyo6qcbxcjL",
	"p+dH5+dP+62KTi+6FRZiOwySpF3udj2MxloXWUjcrFORj9WM0MlIWUambos0h7HV0CLqp04lqKvKoTXh",
	"fYnKI7RdRyKX4H/8QO7UVXWH/OtfbSZBXVX94KzuFFh815mUx6f5H50RQwmqkMRgJx5GWDl8+n3CxSvN",
	"XNOxgclGbxNzdS0bcVNc1+Ls1L6G18NFSZfOaoouZQbZvFSsW3eOM2KyIdtJlzgsqTbPt4gqeJp8zyMn",
	"mOVdFb9Y8vVQCY7nPlSSDvmhE35HlusOKIoPS+TjApMZFXHO48dWNLnSPf7kxZ35zcS6nWyafbClTQ6p",
	"t25kehiIiHsTxG00QQxYzN4UsTdF7E0Re1PEJzZFnG3tfOiZHrwvYt+da29x+GYsDp4mru/OFehqNEvD",
	"KoQ7FIz1WUgdsaJXHKDVeYbKQahfuCn4Y+tSL1Hl4rE3IkZzk/q4oU4k8p1NlSQdZ2p97c+xUwC5vD9I",
	"BQxruaNJO8JHy9LbHoDtD8tB2uhYjmv8zhbbZWQZUmO7yZcftteQLbhLuePdUcBXYUrh85Z4twmkuwHz",
	"mrzTD4PpVrtp+NhOXp0OdvHqlCgr5cGNsOK+HBbIQuPlgXZEhJglJcPGWrtK3mAYbDdsTEPfGSvJFEQz",
	"o321NMCUKGMzFNLEyBIMPqwa00Cp1DbJc05eaeyz4wyjmaA+PuyS0zZ3DmjeLXKO6SoYSRD1wGCGUL9e",
	"1/bQDYX1Glw39DawEtIkXbJmTwwfL7LpFvEwpHrSACu7ghggbSJqCgyZiOFw1qaYXrLSUpU/iwB6Hov1",
	"R37s+ZpW5XW5hWP0e214VEgyhKZz/dpYKKDxYI1xEk2U6xCyan9iax3XDe0PFdVmje/sebuEdHGs9gbt",
	"lyHBw66oeqvjtfj2HrzC8nskX0nuS4tQ0RrzZAWlNGLMc4UHrJr2+B2FbpIyHJAXaKH+g5v+eNRkPd2i",
	"jZzTWqNslh5cXc+ibPJf87vze99jpjhSlMXFJPWEjlWuy5x0idpxEvRHKjs6UhIwnQ8STn0b+25ciW5Q",
	"l2CfCrhPBdynAu5TAfepgPtUwH0q4NeVCviBrjovF6RddPHTG7nm6vGm2XuX3Jd3yQUT3t4Vt3fFfeOu",
	"uB08Sq7oYbKfCNZgTPqTlK+VuI9g3fuTvhV/kiOJ691J7sWbNGSOiAurW9+4H7MbZaQd84dak7csTO/B",
	"5Jv9hKLrUJkWeDSyGUAxrl0JsWJfGH1fGH1fGH1fGP3jFkaPy3WP542OEXFwDkRsiwsrssdVqF2jClpC",
	"rTzkRGmq96UPoiKpoHmCIwRdWF2+nmhucS0aRXy6t//XO9jn/c23jXl+w+VX1VDr5oFJl7x0DwML6NiZ",
	"PcTDKEQ30EzjonE+u+0of+8j2PsI9j6CvY9g7yPY+wj2PoKvsFwge8fyxq7smSwSR/U4fhxp1KjkhI9J",
	"ZR87ThquUSe7ZMK11bAKRy6VN/oh96NYYa1TJayrCE2mkx/lIolfv8pFWvr8ER+MZov+KBfh3lWNEC2X",
	"QnErE2eybkqKtQTLNSzYfpRjt7ZkUufHyUEDbhgEwa6lNYIqOXmxZdLZ6DX/bHDNzwbXfHund26Y5P6t",
	"OEaNVG6FycqTzwfvoDKqPfb4QWaCQrE1L6lG5jaWibbgvutj49JHz7BOIlrenkmxlI8euqkO56R7ppmw",
	"h9pvyhcd8MAM+0TJlNHkwdkpPPEnuIQ/IuOu6wPA0P7uK7ljqm78McTedRN3w58EjJO99n+5hYyVB2FK",
	"J6ZQscbGyPbSU8Wspsqs8cqcdqYLrVh3t5DGhZNGN7hjI/aekrjDsD2WC0ufjkRWbVPm0PGrlGZ17h9t",
	"1qs8x9taFg/13QfTtVacpIynWgXx49afc2ST9v9GD2/k/vUej7339zZ6f70ba+/83Tt/93mY+zzMT5WH",
	"ae89ljeKmzU40hD5HzKqmHrQWO3u9wkwJrBpw8/tRHb5k/fvwRB9IYeH8wfyoFMRMRMPoFVh4A/k8SWz",
	"9xAIUI5gyBv7kVT8N6z0TXAx0Pfofm7kWybgn+wNWTFa+Mrl1HWlhhescFaXlIuZYe9MKD+Oz3Iq7PHL",
	"BfaIJIu1s/O9Ybia3JTuVXtu5o3DIPjD9zx7y7DfY61AcuYBS3SuGBPzDMo/cgO2/ec1E36nyOUnUd7b",
	"5N787vyuk94FrfnkeHJ/fnf+/QS06hWcyJEr5TzzkF6yhEzw0htpl36l7jOUFH0HMN86K/d9r0MrNi/U",
	"hl6EE69TcClOi8nx5AkzbX3XE3zv1K7JCja6lkIjCn1/965zEBsmDIoVoUXd0a/OsqVDTtGmGzE9ISBe",
	"T1YLFnQSVm0B+8ePuJjHSkmVmvyV0CPT/8/PMf2pF4pcTRHmXpxOdFNVVK0nxxMHPuA+Fj/pEiwVLXwn",
	"r+0HHtn0KKKB1Ald7NybgFOY8eIwfT5AHfvRiR/5E6KLmwPE5h2Q5NacEgA3bwGVPCarRDl+NfOiwwyF",
	"lkn4Nj7Lo9/dv94foStx5sj/em5i9QcNx+28mp5xeDdg0JA3MA67q067fWBvilYMMe2X4fRdd6UbG9x+",
	"k2NgjV7FDFuexOoV1vJqD6x/Pb7+hDgIQny03TFkfOpUsy5ge8lgnxYlH4+hYG9NLSJ6F/pGJOwh2Vao",
	"ePT7ogXZ+x2uuXipETq6GuNvolHfIE4NMPeNW9KbkUsvOssvjrjT62aMwZGedtHZzu2kmRSyPowP2lfG",
	"hxv+j5+eUjqTW7X2Qjai+OLE+oSZ/ol/AkqNNI1r6VIx0yhwTXrTU/u1KxwPxOlFhZHr4udYufn3vSvC",
	"NneTWDo44G3nXX3QYQF6OEoU+zbjQvT9tXhw9Hv4d2DkTrW4iVDhPx3y5m6E0VYyxrlfx63l1bihLsPW",
	"7aoT07dmkFvIsR3AdxW695rZUOCKsKDLx4kDMtBwnexcEsgLvXKWBQt21Rv5AyjsBIbtHPltJ7FBqLaH",
	"whW3zId5B+ZHJzowcz2U2GD4E9FbCt9eDrfqXUOyu9/uht4POMW9z7zyPZe4xn4DJ9c73M1s4lqxL3Cb",
	"D7rv8dl7ZEglSzlSA2vCF3SKJIeqmx32TUJdC0t5Ayxro/r2CCb8qphWUi74mBxqWx3y2qk/UBj542gG",
	"jMcJ31A0Do++BUzhi6p8iNE7MYLdLCmfliCDPWVPjbeLGu/emgv/85lzPKrfSoPOVqRdN5tIGwMvPiN1",
	"Q8vY/XV7Wwj8tqohLiBoCzXk7l4N2TNF5Cq3SPfBmrE3sMJ8HOvLV2d2+arNLdcwuNtkX9nkuXKh+n1V",
	"6osSdseocTPf1Q0J2Lubb262GPE0jzqZb2q1+OqIva188QWkqE0u7w+b7/klU4oX8VbvYMDBHNCDS3Em",
	"S56vyYJdSOWMF5hRmbkTzSbkwBHcIVGskpdMk4V0LfCYWEKZZF8FxAVq+9A9qGzABTm/DyO+YIZykU3C",
	"OBuGWDSG+CooejjY31dMQJlg4xNfQqoAhpJL0S/9gcWmEXcB4P9smFq3EO+CZBJD2ieaIUgmU7eTVFmG",
	"z6SlbmCbYxaoTdarcavV5xPibo/w1rFXpXn8jvapT8l5g3lqz3a/CNu9DRT/RSKLbqMJ6vNIZL5Owk6B",
	"I/b+WlDdVln40NiR07CKr4Lw221TxT4F4X9yQvQAvy48tkWPWxEZyyM88cTht7J7cMYAjT/YQhDW8tXc",
	"X2HrX6mVIEB8xE4Q9ndDS8Hdz7fcUBZszFrw0e0WH7Sa22C74C29JdnB+G3ZYWw3uS+Pfvf/3N2KMWQ8",
	"Q7HaP/qIJo2vmDt9Ifk6wq/EpNHTj2Xa8EPuYNw4oTqnRde64ZHNCmtOxLU40tZPaZtlYX46123FLDvo",
	"c1WvqMgmpGT0kumxQTDdE77Z1owR+MpHMmS47U+mbs1fxJKxFSPdyZpx7VefRT0Kq7h1Fo3rOP+WVo3P",
	"zomfMLNnw7eADd8WlvB5zR23kJ6fMHMtMW8fZ/PZ6Rm943uSvi0kfavUzC8WabMV83Gr20sW3UCX26FT",
	"xrEuu+Xz6VB+b2semIkPY4KxCfehW/eeE/4bCzd4yNvVVhji47eeRBDlHCJwqEhxnc/h9Yk5Ti6FYLmv",
	"27pdorkro+y+69S2v5k4thMrgn4Jiem5yMvGWVRWUpspqaUyU2j1bQebZqKmWl9JVWARQ0pqxWaLhpcm",
	"Hu/Vi1OYQ7O20LtipA61VN0eQklWKfIuU8lEVGXXzgTNHK5RDE/ag9hz0W9ARWzP+5HXB98nuqiPUlmX",
	"r35O4U2qFPndTuUysdIvLOL5SrC7yHihX17N1IVUVWiW9IXEvRd+D3tO9W/MqeKCyBsEvoCce4kvIfGN",
	"kG5a+PN1iDezo8BBduNGlRTcSIs8Myw0uxMLar92ZWrBD0TJkl8y0e1FN+Qbz8LHJ27mW8c4fu5npw03",
	"/FXF+vRBvi8V8wGlYpK44Im2hfTuwUiDgaF67oPh723ZcMAwTd5YjHrjTI6amXkmHmK3QLzl/XOsmF9b",
	"EeiSkbdsjQV8u6WmBWOF7ox13uQrQjV0foKhjkldVW9cp6439t8wWPylU4gKXyK4M8d4+FQfU79G3vAV",
	"BE71wYzAP7OQ1mMG7mdjaPiFA6oGKLNnbDetbpNC5RHONi6RJESLD5VNblriZsg5R9Lu5yPxUl8HO7oB",
	"J/rqeOB1lWu+5cTxIWfu2F9uDZdxgTs7cJktY3g+gM6fMLMn8ltJ5HsxYc9ERgy6O3CQmpp8tWXo0Aew",
	"EYwc2HOSb0dlwhPfrDJVm1Um35drrzPtmeHNmKELWLodelvszNrJ8OX7Rn5o7p23mH81jii/8a808y50",
	"SkxzP7+721GhZ8NifT7Lbc5zUwG3P4t/yH929Lv71+7Gl9ANdiBDuScfMa/tq6X8L+SBbrEpMWf78Pb5",
	"nzeR707ZVdd99FnEDL+IW5dbtZnbbGmV+TwM4Akze+rfU/9nT6S6fbT7hJlPJib4+NabFYkJX+/ctvAs",
	"zPtv37LQb/W6EKv2KG5FTFMdnZDHOb+Va5Cus5ONWHf0u//nLq0JB/iXuIr8o5s2JwxbvfWdCet2pYkp",
	"o6e3kCZSGOmffXbOHya+Xaw/OsGPRIfB6Z6kNzsnDV2uF9jEPelgOwnovJFEft6WPG5VtwW/udvWYsE3",
	"nL69Xpz2jD+szXLNVMW15lLcqD9m9HmIWm40s/+gxoroeaMUE6Zck1Iul9BpGyLzvnv8jlZ1yY6/y8QD",
	"rZsKhfsLWZbyioslefHwwQmpoXAJJhnZYTV5Q0seVJuFXLw5zsSbN28yUU+JkiU7LtjlNGonOYWUoSn5",
	"rveGv95mWHVWT8l3U/Ld0ehrHmid9xZysfGV5ZTActsR3WLt9WIBCrZLhGpv+33Aun373f6eCUKySfRW",
	"Njkmv9hfif+P/V82ge+yyTT+rQVP74GFVe+n77IJ/vl6uuXofdAOB+z+ffQBU3iY7zCH/c/rTLx3kHzg",
	"KhRvAH2MZtsDfiEXn27VqZvilWbqLCLnT8i3+1PtowZvxMSBU9adI/Pc/EFjVkwYtzCSNXfvfv8nYn+V",
	"iv+G23ltRzzy7F3vINzntKY5N2vM3rykvKSLkoWa29pLEu2dsknXfMJM+6K7Ol+EVX1CNNww6x4jd49j",
	"dUKPio4uKVxYrNMMUHYrxwYXl7TkGCriWmfD7z/+/SUx8i0T476JczfNB0Uxfv/fnx7AL6UkFRVrQo1h",
	"VW30rTraGOpP5VI2ZmdWc20+Bte6CV7pcLRwg1rRz96sXJALJStgLdGS5igQhawHYItVow1Z0UuUC9+U",
	"csnFG2BcC15ysx73ZMc48/Gdt/bqO1GssBCj5Wj0Cuwhj9772GEqtbJ7Nxy/BlgnLRv+F3Qkf02xKt8s",
	"2bK8UdysJ8e/vN5AxFzcSFzQzBgulnq3IhX+Ky8Y+LVA6mVZYmJSSjA499N9QjEgzLE1cm+AcrRgD9wn",
	"TDBFS8LFhXRQvGRK71zpw33Uh6F9DZEgxdP+hh+d2rk/IQzdNLuBMADNfz0Osy7Ef588ZFQxZRHUHsB7",
	"ewQAArRtNaqcHE+OLu9N7BM3Zh/GFn5rs7IXi2JYUMTIvth64o0dwQAWiTJDu2+8bFUhMdGFbMwo1rcD",
	"d7Y8HDq9XNolXJDHO1Qbht+GxLedNfY7uOFba/GWY8TF5N0Ybd20LcdYhGpXbgTf4WLL71VbPsENEJyd",
	"O60g6svXWUhoy7ftcG0cYDtUFET4/vX7/z8AAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
