// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes bearerAuthContextKey = "BearerAuth.Scopes"
)

// Defines values for MonitoringConfigBaseType.
const (
	MonitoringConfigBaseTypePmm MonitoringConfigBaseType = "pmm"
)

// Valid indicates whether the value is a known member of the MonitoringConfigBaseType enum.
func (e MonitoringConfigBaseType) Valid() bool {
	switch e {
	case MonitoringConfigBaseTypePmm:
		return true
	default:
		return false
	}
}

// Defines values for MonitoringConfigBaseWithNameType.
const (
	MonitoringConfigBaseWithNameTypePmm MonitoringConfigBaseWithNameType = "pmm"
)

// Valid indicates whether the value is a known member of the MonitoringConfigBaseWithNameType enum.
func (e MonitoringConfigBaseWithNameType) Valid() bool {
	switch e {
	case MonitoringConfigBaseWithNameTypePmm:
		return true
	default:
		return false
	}
}

// Defines values for MonitoringConfigCreateParamsType.
const (
	MonitoringConfigCreateParamsTypePmm MonitoringConfigCreateParamsType = "pmm"
)

// Valid indicates whether the value is a known member of the MonitoringConfigCreateParamsType enum.
func (e MonitoringConfigCreateParamsType) Valid() bool {
	switch e {
	case MonitoringConfigCreateParamsTypePmm:
		return true
	default:
		return false
	}
}

// Defines values for MonitoringConfigUpdateParamsType.
const (
	MonitoringConfigUpdateParamsTypePmm MonitoringConfigUpdateParamsType = "pmm"
)

// Valid indicates whether the value is a known member of the MonitoringConfigUpdateParamsType enum.
func (e MonitoringConfigUpdateParamsType) Valid() bool {
	switch e {
	case MonitoringConfigUpdateParamsTypePmm:
		return true
	default:
		return false
	}
}

// Defines values for DeleteBackupParamsDeletionPolicy.
const (
	DeleteBackupParamsDeletionPolicyDelete DeleteBackupParamsDeletionPolicy = "Delete"
	DeleteBackupParamsDeletionPolicyRetain DeleteBackupParamsDeletionPolicy = "Retain"
)

// Valid indicates whether the value is a known member of the DeleteBackupParamsDeletionPolicy enum.
func (e DeleteBackupParamsDeletionPolicy) Valid() bool {
	switch e {
	case DeleteBackupParamsDeletionPolicyDelete:
		return true
	case DeleteBackupParamsDeletionPolicyRetain:
		return true
	default:
		return false
	}
}

// Defines values for DeleteInstanceParamsDeletionPolicy.
const (
	DeleteInstanceParamsDeletionPolicyCascade DeleteInstanceParamsDeletionPolicy = "Cascade"
	DeleteInstanceParamsDeletionPolicyOrphan  DeleteInstanceParamsDeletionPolicy = "Orphan"
)

// Valid indicates whether the value is a known member of the DeleteInstanceParamsDeletionPolicy enum.
func (e DeleteInstanceParamsDeletionPolicy) Valid() bool {
	switch e {
	case DeleteInstanceParamsDeletionPolicyCascade:
		return true
	case DeleteInstanceParamsDeletionPolicyOrphan:
		return true
	default:
		return false
	}
}

// Cluster defines model for Cluster.
type Cluster struct {
	Name   string `json:"name"`
	Server string `json:"server"`
}

// ClusterList defines model for ClusterList.
type ClusterList struct {
	Items []Cluster `json:"items"`
}

// Error Error response
type Error struct {
	Message *string `json:"message,omitempty"`
}

// KubernetesClusterInfo kubernetes cluster info
type KubernetesClusterInfo struct {
	ClusterType string `json:"clusterType"`

	// StorageClassNames List of storage class names that are available in the cluster.
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	StorageClassNames []string        `json:"storageClassNames"`
	StorageClasses    *[]StorageClass `json:"storageClasses,omitempty"`
}

// KubernetesClusterResources kubernetes cluster resources
type KubernetesClusterResources struct {
	Available ResourcesAvailable `json:"available"`
	Capacity  ResourcesCapacity  `json:"capacity"`
}

// ResourcesAvailable defines model for .
type ResourcesAvailable struct {
	CpuMillis   *uint64 `json:"cpuMillis,omitempty"`
	DiskSize    *uint64 `json:"diskSize,omitempty"`
	MemoryBytes *uint64 `json:"memoryBytes,omitempty"`
}

// ResourcesCapacity defines model for .
type ResourcesCapacity struct {
	CpuMillis   *uint64 `json:"cpuMillis,omitempty"`
	DiskSize    *uint64 `json:"diskSize,omitempty"`
	MemoryBytes *uint64 `json:"memoryBytes,omitempty"`
}

// MonitoringConfigBase MonitoringConfigBase contains common fields for monitoring config
type MonitoringConfigBase struct {
	Type MonitoringConfigBaseType `json:"type,omitempty"`
	Url  string                   `json:"url,omitempty"`

	// VerifyTLS VerifyTLS is set to ensure TLS/SSL verification.
	VerifyTLS *bool `json:"verifyTLS,omitempty"`
}

// MonitoringConfigBaseType defines model for MonitoringConfigBase.Type.
type MonitoringConfigBaseType string

// MonitoringConfigBaseWithName defines model for MonitoringConfigBaseWithName.
type MonitoringConfigBaseWithName struct {
	// Name A user defined string name of the storage in the DNS name format https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-label-names
	Name string                           `json:"name,omitempty"`
	Type MonitoringConfigBaseWithNameType `json:"type,omitempty"`
	Url  string                           `json:"url,omitempty"`

	// VerifyTLS VerifyTLS is set to ensure TLS/SSL verification.
	VerifyTLS *bool `json:"verifyTLS,omitempty"`
}

// MonitoringConfigBaseWithNameType defines model for MonitoringConfigBaseWithName.Type.
type MonitoringConfigBaseWithNameType string

// MonitoringConfigCreateParams defines model for MonitoringConfigCreateParams.
type MonitoringConfigCreateParams struct {
	// Name A user defined string name of the storage in the DNS name format https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-label-names
	Name string                           `json:"name,omitempty"`
	Pmm  *MonitoringConfigPMMSpec         `json:"pmm,omitempty"`
	Type MonitoringConfigCreateParamsType `json:"type,omitempty"`
	Url  string                           `json:"url,omitempty"`

	// VerifyTLS VerifyTLS is set to ensure TLS/SSL verification.
	VerifyTLS *bool `json:"verifyTLS,omitempty"`
}

// MonitoringConfigPMMSpec defines model for .
type MonitoringConfigPMMSpec struct {
	ApiKey   string `json:"apiKey,omitempty"`
	Password string `json:"password,omitempty"`
	User     string `json:"user,omitempty"`
}

// MonitoringConfigCreateParamsType defines model for MonitoringConfigCreateParams.Type.
type MonitoringConfigCreateParamsType string

// MonitoringConfigPMM MonitoringConfigPMM contains PMM-specific fields for monitoring config
type MonitoringConfigPMM struct {
	Pmm *MonitoringConfigPMMSpec `json:"pmm,omitempty"`
}

// MonitoringConfigUpdateParams defines model for MonitoringConfigUpdateParams.
type MonitoringConfigUpdateParams struct {
	Pmm  *MonitoringConfigPMMSpec         `json:"pmm,omitempty"`
	Type MonitoringConfigUpdateParamsType `json:"type,omitempty"`
	Url  string                           `json:"url,omitempty"`

	// VerifyTLS VerifyTLS is set to ensure TLS/SSL verification.
	VerifyTLS *bool `json:"verifyTLS,omitempty"`
}

// MonitoringConfigUpdateParamsType defines model for MonitoringConfigUpdateParams.Type.
type MonitoringConfigUpdateParamsType string

// OIDCConfig Everest OIDC provider configuration
type OIDCConfig struct {
	// ClientId OIDC application clientID
	ClientId string `json:"clientId"`

	// IssuerURL OIDC provider url
	IssuerURL string `json:"issuerURL"`

	// Scopes OIDC scopes
	Scopes []string `json:"scopes"`
}

// Settings Everest global settings
type Settings struct {
	// OidcConfig Everest OIDC provider configuration
	OidcConfig OIDCConfig `json:"oidcConfig"`
}

// StorageClass StorageClass describes the parameters for a class of storage for which PersistentVolumes can be dynamically provisioned.
//
// StorageClasses are non-namespaced; the name of the storage class according to etcd is in ObjectMeta.Name.
type StorageClass struct {
	// AllowVolumeExpansion allowVolumeExpansion shows whether the storage class allow volume expand.
	AllowVolumeExpansion *bool `json:"allowVolumeExpansion,omitempty"`

	// Metadata Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
}

// UserCredentials defines model for UserCredentials.
type UserCredentials struct {
	Password *string `json:"password,omitempty"`
	Username *string `json:"username,omitempty"`
}

// UserPermissions defines model for UserPermissions.
type UserPermissions struct {
	Enabled     bool        `json:"enabled"`
	Permissions *[][]string `json:"permissions,omitempty"`
}

// Version Everest version info
type Version struct {
	FullCommit  string `json:"fullCommit"`
	ProjectName string `json:"projectName"`
	Version     string `json:"version"`
}

// bearerAuthContextKey is the context key for BearerAuth security scheme
type bearerAuthContextKey string

// DeleteBackupParams defines parameters for DeleteBackup.
type DeleteBackupParams struct {
	// DeletionPolicy Override the backup's spec.deletionPolicy before deletion.
	// "Delete" (default) removes both the engine backup resource and the data in S3.
	// "Retain" removes the engine backup resource but preserves the data in S3.
	// When omitted, the existing value on the Backup CR is used.
	DeletionPolicy *DeleteBackupParamsDeletionPolicy `form:"deletionPolicy,omitempty" json:"deletionPolicy,omitempty"`
}

// DeleteBackupParamsDeletionPolicy defines parameters for DeleteBackup.
type DeleteBackupParamsDeletionPolicy string

// DeleteInstanceParams defines parameters for DeleteInstance.
type DeleteInstanceParams struct {
	// DeletionPolicy Override the instance's spec.deletionPolicy before deletion.
	// "Cascade" (default) deletes all Backup and Restore CRs referencing this instance.
	// "Orphan" leaves Backup and Restore CRs in place.
	// When omitted, the existing value on the Instance CR is used.
	DeletionPolicy *DeleteInstanceParamsDeletionPolicy `form:"deletionPolicy,omitempty" json:"deletionPolicy,omitempty"`
}

// DeleteInstanceParamsDeletionPolicy defines parameters for DeleteInstance.
type DeleteInstanceParamsDeletionPolicy string

// CreateBackupStorageJSONRequestBody defines body for CreateBackupStorage for application/json ContentType.
type CreateBackupStorageJSONRequestBody = BackupStorage

// UpdateBackupStorageJSONRequestBody defines body for UpdateBackupStorage for application/json ContentType.
type UpdateBackupStorageJSONRequestBody = BackupStorage

// CreateBackupJSONRequestBody defines body for CreateBackup for application/json ContentType.
type CreateBackupJSONRequestBody = Backup

// CreateInstanceJSONRequestBody defines body for CreateInstance for application/json ContentType.
type CreateInstanceJSONRequestBody = Instance

// UpdateInstanceJSONRequestBody defines body for UpdateInstance for application/json ContentType.
type UpdateInstanceJSONRequestBody = Instance

// CreateMonitoringConfigJSONRequestBody defines body for CreateMonitoringConfig for application/json ContentType.
type CreateMonitoringConfigJSONRequestBody = MonitoringConfigCreateParams

// UpdateMonitoringConfigJSONRequestBody defines body for UpdateMonitoringConfig for application/json ContentType.
type UpdateMonitoringConfigJSONRequestBody = MonitoringConfigUpdateParams

// CreateRestoreJSONRequestBody defines body for CreateRestore for application/json ContentType.
type CreateRestoreJSONRequestBody = Restore

// CreateSessionJSONRequestBody defines body for CreateSession for application/json ContentType.
type CreateSessionJSONRequestBody = UserCredentials

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Cluster info
	// (GET /cluster-info)
	GetKubernetesClusterInfo(ctx echo.Context) error
	// List clusters
	// (GET /clusters)
	ListClusters(ctx echo.Context) error
	// List backup classes
	// (GET /clusters/{cluster}/backup-classes)
	ListBackupClasses(ctx echo.Context, cluster string) error
	// Get backup class
	// (GET /clusters/{cluster}/backup-classes/{backupClass})
	GetBackupClass(ctx echo.Context, cluster string, backupClass string) error
	// List backup storages
	// (GET /clusters/{cluster}/namespaces/{namespace}/backup-storages)
	ListBackupStorages(ctx echo.Context, cluster string, namespace string) error
	// Create backup storage
	// (POST /clusters/{cluster}/namespaces/{namespace}/backup-storages)
	CreateBackupStorage(ctx echo.Context, cluster string, namespace string) error
	// Delete backup storage
	// (DELETE /clusters/{cluster}/namespaces/{namespace}/backup-storages/{name})
	DeleteBackupStorage(ctx echo.Context, cluster string, namespace string, name string) error
	// Get backup storage
	// (GET /clusters/{cluster}/namespaces/{namespace}/backup-storages/{name})
	GetBackupStorage(ctx echo.Context, cluster string, namespace string, name string) error
	// Update backup storage
	// (PUT /clusters/{cluster}/namespaces/{namespace}/backup-storages/{name})
	UpdateBackupStorage(ctx echo.Context, cluster string, namespace string, name string) error
	// Create backup
	// (POST /clusters/{cluster}/namespaces/{namespace}/backups)
	CreateBackup(ctx echo.Context, cluster string, namespace string) error
	// Delete backup
	// (DELETE /clusters/{cluster}/namespaces/{namespace}/backups/{backup})
	DeleteBackup(ctx echo.Context, cluster string, namespace string, backup string, params DeleteBackupParams) error
	// Get backup
	// (GET /clusters/{cluster}/namespaces/{namespace}/backups/{backup})
	GetBackup(ctx echo.Context, cluster string, namespace string, backup string) error
	// List instances
	// (GET /clusters/{cluster}/namespaces/{namespace}/instances)
	ListInstances(ctx echo.Context, cluster string, namespace string) error
	// Create instance
	// (POST /clusters/{cluster}/namespaces/{namespace}/instances)
	CreateInstance(ctx echo.Context, cluster string, namespace string) error
	// Delete instance
	// (DELETE /clusters/{cluster}/namespaces/{namespace}/instances/{instance})
	DeleteInstance(ctx echo.Context, cluster string, namespace string, instance string, params DeleteInstanceParams) error
	// Get instance
	// (GET /clusters/{cluster}/namespaces/{namespace}/instances/{instance})
	GetInstance(ctx echo.Context, cluster string, namespace string, instance string) error
	// Update instance
	// (PUT /clusters/{cluster}/namespaces/{namespace}/instances/{instance})
	UpdateInstance(ctx echo.Context, cluster string, namespace string, instance string) error
	// List backups for an instance
	// (GET /clusters/{cluster}/namespaces/{namespace}/instances/{instance}/backups)
	ListInstanceBackups(ctx echo.Context, cluster string, namespace string, instance string) error
	// Get instance connection details
	// (GET /clusters/{cluster}/namespaces/{namespace}/instances/{instance}/connection)
	GetInstanceConnection(ctx echo.Context, cluster string, namespace string, instance string) error
	// List restores performed for an instance
	// (GET /clusters/{cluster}/namespaces/{namespace}/instances/{instance}/restores)
	ListInstanceRestores(ctx echo.Context, cluster string, namespace string, instance string) error
	// List monitoring configs
	// (GET /clusters/{cluster}/namespaces/{namespace}/monitoring-configs)
	ListMonitoringConfigs(ctx echo.Context, cluster string, namespace string) error
	// Create monitoring config
	// (POST /clusters/{cluster}/namespaces/{namespace}/monitoring-configs)
	CreateMonitoringConfig(ctx echo.Context, cluster string, namespace string) error
	// Delete monitoring config
	// (DELETE /clusters/{cluster}/namespaces/{namespace}/monitoring-configs/{name})
	DeleteMonitoringConfig(ctx echo.Context, cluster string, namespace string, name string) error
	// Get monitoring config
	// (GET /clusters/{cluster}/namespaces/{namespace}/monitoring-configs/{name})
	GetMonitoringConfig(ctx echo.Context, cluster string, namespace string, name string) error
	// Update monitoring config
	// (PATCH /clusters/{cluster}/namespaces/{namespace}/monitoring-configs/{name})
	UpdateMonitoringConfig(ctx echo.Context, cluster string, namespace string, name string) error
	// Create restore
	// (POST /clusters/{cluster}/namespaces/{namespace}/restores)
	CreateRestore(ctx echo.Context, cluster string, namespace string) error
	// Delete restore
	// (DELETE /clusters/{cluster}/namespaces/{namespace}/restores/{restore})
	DeleteRestore(ctx echo.Context, cluster string, namespace string, restore string) error
	// Get restore
	// (GET /clusters/{cluster}/namespaces/{namespace}/restores/{restore})
	GetRestore(ctx echo.Context, cluster string, namespace string, restore string) error
	// List providers
	// (GET /clusters/{cluster}/providers)
	ListProviders(ctx echo.Context, cluster string) error
	// Get provider
	// (GET /clusters/{cluster}/providers/{provider})
	GetProvider(ctx echo.Context, cluster string, provider string) error
	// Get cluster
	// (GET /clusters/{name})
	GetCluster(ctx echo.Context, name string) error
	// Get user permissions
	// (GET /permissions)
	GetUserPermissions(ctx echo.Context) error
	// Cluster resources
	// (GET /resources)
	GetKubernetesClusterResources(ctx echo.Context) error
	// Everest API Logout
	// (DELETE /session)
	DeleteSession(ctx echo.Context) error
	// Everest API Login
	// (POST /session)
	CreateSession(ctx echo.Context) error
	// Settings
	// (GET /settings)
	GetSettings(ctx echo.Context) error
	// Version
	// (GET /version)
	VersionInfo(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetKubernetesClusterInfo converts echo context to params.
func (w *ServerInterfaceWrapper) GetKubernetesClusterInfo(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetKubernetesClusterInfo(ctx)
	return err
}

// ListClusters converts echo context to params.
func (w *ServerInterfaceWrapper) ListClusters(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListClusters(ctx)
	return err
}

// ListBackupClasses converts echo context to params.
func (w *ServerInterfaceWrapper) ListBackupClasses(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListBackupClasses(ctx, cluster)
	return err
}

// GetBackupClass converts echo context to params.
func (w *ServerInterfaceWrapper) GetBackupClass(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "backupClass" -------------
	var backupClass string

	err = runtime.BindStyledParameterWithOptions("simple", "backupClass", ctx.Param("backupClass"), &backupClass, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter backupClass: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetBackupClass(ctx, cluster, backupClass)
	return err
}

// ListBackupStorages converts echo context to params.
func (w *ServerInterfaceWrapper) ListBackupStorages(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListBackupStorages(ctx, cluster, namespace)
	return err
}

// CreateBackupStorage converts echo context to params.
func (w *ServerInterfaceWrapper) CreateBackupStorage(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateBackupStorage(ctx, cluster, namespace)
	return err
}

// DeleteBackupStorage converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteBackupStorage(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", ctx.Param("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteBackupStorage(ctx, cluster, namespace, name)
	return err
}

// GetBackupStorage converts echo context to params.
func (w *ServerInterfaceWrapper) GetBackupStorage(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", ctx.Param("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetBackupStorage(ctx, cluster, namespace, name)
	return err
}

// UpdateBackupStorage converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateBackupStorage(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", ctx.Param("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateBackupStorage(ctx, cluster, namespace, name)
	return err
}

// CreateBackup converts echo context to params.
func (w *ServerInterfaceWrapper) CreateBackup(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateBackup(ctx, cluster, namespace)
	return err
}

// DeleteBackup converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteBackup(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	// ------------- Path parameter "backup" -------------
	var backup string

	err = runtime.BindStyledParameterWithOptions("simple", "backup", ctx.Param("backup"), &backup, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter backup: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteBackupParams
	// ------------- Optional query parameter "deletionPolicy" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "deletionPolicy", ctx.QueryParams(), &params.DeletionPolicy, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter deletionPolicy: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteBackup(ctx, cluster, namespace, backup, params)
	return err
}

// GetBackup converts echo context to params.
func (w *ServerInterfaceWrapper) GetBackup(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	// ------------- Path parameter "backup" -------------
	var backup string

	err = runtime.BindStyledParameterWithOptions("simple", "backup", ctx.Param("backup"), &backup, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter backup: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetBackup(ctx, cluster, namespace, backup)
	return err
}

// ListInstances converts echo context to params.
func (w *ServerInterfaceWrapper) ListInstances(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListInstances(ctx, cluster, namespace)
	return err
}

// CreateInstance converts echo context to params.
func (w *ServerInterfaceWrapper) CreateInstance(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateInstance(ctx, cluster, namespace)
	return err
}

// DeleteInstance converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteInstance(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	// ------------- Path parameter "instance" -------------
	var instance string

	err = runtime.BindStyledParameterWithOptions("simple", "instance", ctx.Param("instance"), &instance, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter instance: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteInstanceParams
	// ------------- Optional query parameter "deletionPolicy" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "deletionPolicy", ctx.QueryParams(), &params.DeletionPolicy, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter deletionPolicy: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteInstance(ctx, cluster, namespace, instance, params)
	return err
}

// GetInstance converts echo context to params.
func (w *ServerInterfaceWrapper) GetInstance(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	// ------------- Path parameter "instance" -------------
	var instance string

	err = runtime.BindStyledParameterWithOptions("simple", "instance", ctx.Param("instance"), &instance, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter instance: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetInstance(ctx, cluster, namespace, instance)
	return err
}

// UpdateInstance converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateInstance(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	// ------------- Path parameter "instance" -------------
	var instance string

	err = runtime.BindStyledParameterWithOptions("simple", "instance", ctx.Param("instance"), &instance, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter instance: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateInstance(ctx, cluster, namespace, instance)
	return err
}

// ListInstanceBackups converts echo context to params.
func (w *ServerInterfaceWrapper) ListInstanceBackups(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	// ------------- Path parameter "instance" -------------
	var instance string

	err = runtime.BindStyledParameterWithOptions("simple", "instance", ctx.Param("instance"), &instance, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter instance: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListInstanceBackups(ctx, cluster, namespace, instance)
	return err
}

// GetInstanceConnection converts echo context to params.
func (w *ServerInterfaceWrapper) GetInstanceConnection(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	// ------------- Path parameter "instance" -------------
	var instance string

	err = runtime.BindStyledParameterWithOptions("simple", "instance", ctx.Param("instance"), &instance, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter instance: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetInstanceConnection(ctx, cluster, namespace, instance)
	return err
}

// ListInstanceRestores converts echo context to params.
func (w *ServerInterfaceWrapper) ListInstanceRestores(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	// ------------- Path parameter "instance" -------------
	var instance string

	err = runtime.BindStyledParameterWithOptions("simple", "instance", ctx.Param("instance"), &instance, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter instance: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListInstanceRestores(ctx, cluster, namespace, instance)
	return err
}

// ListMonitoringConfigs converts echo context to params.
func (w *ServerInterfaceWrapper) ListMonitoringConfigs(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListMonitoringConfigs(ctx, cluster, namespace)
	return err
}

// CreateMonitoringConfig converts echo context to params.
func (w *ServerInterfaceWrapper) CreateMonitoringConfig(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateMonitoringConfig(ctx, cluster, namespace)
	return err
}

// DeleteMonitoringConfig converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteMonitoringConfig(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", ctx.Param("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteMonitoringConfig(ctx, cluster, namespace, name)
	return err
}

// GetMonitoringConfig converts echo context to params.
func (w *ServerInterfaceWrapper) GetMonitoringConfig(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", ctx.Param("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetMonitoringConfig(ctx, cluster, namespace, name)
	return err
}

// UpdateMonitoringConfig converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateMonitoringConfig(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", ctx.Param("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateMonitoringConfig(ctx, cluster, namespace, name)
	return err
}

// CreateRestore converts echo context to params.
func (w *ServerInterfaceWrapper) CreateRestore(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateRestore(ctx, cluster, namespace)
	return err
}

// DeleteRestore converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteRestore(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	// ------------- Path parameter "restore" -------------
	var restore string

	err = runtime.BindStyledParameterWithOptions("simple", "restore", ctx.Param("restore"), &restore, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter restore: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteRestore(ctx, cluster, namespace, restore)
	return err
}

// GetRestore converts echo context to params.
func (w *ServerInterfaceWrapper) GetRestore(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	// ------------- Path parameter "restore" -------------
	var restore string

	err = runtime.BindStyledParameterWithOptions("simple", "restore", ctx.Param("restore"), &restore, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter restore: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetRestore(ctx, cluster, namespace, restore)
	return err
}

// ListProviders converts echo context to params.
func (w *ServerInterfaceWrapper) ListProviders(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListProviders(ctx, cluster)
	return err
}

// GetProvider converts echo context to params.
func (w *ServerInterfaceWrapper) GetProvider(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "cluster" -------------
	var cluster string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", ctx.Param("cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cluster: %s", err))
	}

	// ------------- Path parameter "provider" -------------
	var provider string

	err = runtime.BindStyledParameterWithOptions("simple", "provider", ctx.Param("provider"), &provider, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter provider: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetProvider(ctx, cluster, provider)
	return err
}

// GetCluster converts echo context to params.
func (w *ServerInterfaceWrapper) GetCluster(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", ctx.Param("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCluster(ctx, name)
	return err
}

// GetUserPermissions converts echo context to params.
func (w *ServerInterfaceWrapper) GetUserPermissions(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUserPermissions(ctx)
	return err
}

// GetKubernetesClusterResources converts echo context to params.
func (w *ServerInterfaceWrapper) GetKubernetesClusterResources(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetKubernetesClusterResources(ctx)
	return err
}

// DeleteSession converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteSession(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteSession(ctx)
	return err
}

// CreateSession converts echo context to params.
func (w *ServerInterfaceWrapper) CreateSession(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateSession(ctx)
	return err
}

// GetSettings converts echo context to params.
func (w *ServerInterfaceWrapper) GetSettings(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetSettings(ctx)
	return err
}

// VersionInfo converts echo context to params.
func (w *ServerInterfaceWrapper) VersionInfo(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.VersionInfo(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/cluster-info", wrapper.GetKubernetesClusterInfo, options.OperationMiddlewares["getKubernetesClusterInfo"]...)
	router.GET(options.BaseURL+"/clusters", wrapper.ListClusters, options.OperationMiddlewares["listClusters"]...)
	router.GET(options.BaseURL+"/clusters/:cluster/backup-classes", wrapper.ListBackupClasses, options.OperationMiddlewares["listBackupClasses"]...)
	router.GET(options.BaseURL+"/clusters/:cluster/backup-classes/:backupClass", wrapper.GetBackupClass, options.OperationMiddlewares["getBackupClass"]...)
	router.GET(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/backup-storages", wrapper.ListBackupStorages, options.OperationMiddlewares["listBackupStorages"]...)
	router.POST(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/backup-storages", wrapper.CreateBackupStorage, options.OperationMiddlewares["createBackupStorage"]...)
	router.DELETE(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/backup-storages/:name", wrapper.DeleteBackupStorage, options.OperationMiddlewares["deleteBackupStorage"]...)
	router.GET(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/backup-storages/:name", wrapper.GetBackupStorage, options.OperationMiddlewares["getBackupStorage"]...)
	router.PUT(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/backup-storages/:name", wrapper.UpdateBackupStorage, options.OperationMiddlewares["updateBackupStorage"]...)
	router.POST(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/backups", wrapper.CreateBackup, options.OperationMiddlewares["createBackup"]...)
	router.DELETE(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/backups/:backup", wrapper.DeleteBackup, options.OperationMiddlewares["deleteBackup"]...)
	router.GET(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/backups/:backup", wrapper.GetBackup, options.OperationMiddlewares["getBackup"]...)
	router.GET(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/instances", wrapper.ListInstances, options.OperationMiddlewares["listInstances"]...)
	router.POST(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/instances", wrapper.CreateInstance, options.OperationMiddlewares["createInstance"]...)
	router.DELETE(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/instances/:instance", wrapper.DeleteInstance, options.OperationMiddlewares["deleteInstance"]...)
	router.GET(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/instances/:instance", wrapper.GetInstance, options.OperationMiddlewares["getInstance"]...)
	router.PUT(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/instances/:instance", wrapper.UpdateInstance, options.OperationMiddlewares["updateInstance"]...)
	router.GET(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/instances/:instance/backups", wrapper.ListInstanceBackups, options.OperationMiddlewares["listInstanceBackups"]...)
	router.GET(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/instances/:instance/connection", wrapper.GetInstanceConnection, options.OperationMiddlewares["getInstanceConnection"]...)
	router.GET(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/instances/:instance/restores", wrapper.ListInstanceRestores, options.OperationMiddlewares["listInstanceRestores"]...)
	router.GET(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/monitoring-configs", wrapper.ListMonitoringConfigs, options.OperationMiddlewares["listMonitoringConfigs"]...)
	router.POST(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/monitoring-configs", wrapper.CreateMonitoringConfig, options.OperationMiddlewares["createMonitoringConfig"]...)
	router.DELETE(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/monitoring-configs/:name", wrapper.DeleteMonitoringConfig, options.OperationMiddlewares["deleteMonitoringConfig"]...)
	router.GET(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/monitoring-configs/:name", wrapper.GetMonitoringConfig, options.OperationMiddlewares["getMonitoringConfig"]...)
	router.PATCH(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/monitoring-configs/:name", wrapper.UpdateMonitoringConfig, options.OperationMiddlewares["updateMonitoringConfig"]...)
	router.POST(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/restores", wrapper.CreateRestore, options.OperationMiddlewares["createRestore"]...)
	router.DELETE(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/restores/:restore", wrapper.DeleteRestore, options.OperationMiddlewares["deleteRestore"]...)
	router.GET(options.BaseURL+"/clusters/:cluster/namespaces/:namespace/restores/:restore", wrapper.GetRestore, options.OperationMiddlewares["getRestore"]...)
	router.GET(options.BaseURL+"/clusters/:cluster/providers", wrapper.ListProviders, options.OperationMiddlewares["listProviders"]...)
	router.GET(options.BaseURL+"/clusters/:cluster/providers/:provider", wrapper.GetProvider, options.OperationMiddlewares["getProvider"]...)
	router.GET(options.BaseURL+"/clusters/:name", wrapper.GetCluster, options.OperationMiddlewares["getCluster"]...)
	router.GET(options.BaseURL+"/permissions", wrapper.GetUserPermissions, options.OperationMiddlewares["getUserPermissions"]...)
	router.GET(options.BaseURL+"/resources", wrapper.GetKubernetesClusterResources, options.OperationMiddlewares["getKubernetesClusterResources"]...)
	router.DELETE(options.BaseURL+"/session", wrapper.DeleteSession, options.OperationMiddlewares["deleteSession"]...)
	router.POST(options.BaseURL+"/session", wrapper.CreateSession, options.OperationMiddlewares["createSession"]...)
	router.GET(options.BaseURL+"/settings", wrapper.GetSettings, options.OperationMiddlewares["getSettings"]...)
	router.GET(options.BaseURL+"/version", wrapper.VersionInfo, options.OperationMiddlewares["versionInfo"]...)

}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7L3tctw4sij4Krg1J6KlPlUld3vu7Dma6JiwZY9X3XZbYdkzd2/TO0aRUBXaJMABQMnVPY7Yh9gn3CfZ",
	"QCYAgiRYqpL8IY9rfkxbRRIficxEfufvk1xWtRRMGD05/n2i8xWrKPzzpGy0Ycr+s1ayZspwBg8ErZj9",
	"r1nXbHI80UZxsZy8n040U5f4Qe/R++lEsX82XLFicvwLDhBefz31r8vFryw3diQ391OuzXB+bljV/cd/",
	"KHYxOZ784ajdzJHbyZHfxvswDVWKrgeLwsFSi3mslIRdFUzniteGSzE5xp+JYrqWQtv9dFdZMa3pkqWh",
	"MZjjp2bBlGCGabfeU3Ehh3O+Da+RHN8j3L7Yn9w9fAnTpE7KSEWX7KSkWv9MK/yoYLViOTUWHkY1bNqb",
	"3J4GkRfEfUxy+zWxh6mJWVFDqGKEXlJe0kXJCBfErJhf5zwTk+mEvaNVXTIL72X9/WQ6Wdb3LczDSQ5W",
	"2j2z7srZ9lhwHn12LSrE0EvB6vU2B/iCadmo3IP2mlNU4e3+UQaADgkhr5tnvCx5DDnRVAumJtPJu9lS",
	"ztyPDRfmT3+0yyy4fnvOf2Pbf1GxSqr1w7VhW08zQPDotRlyj0kAz4Owv/fTSU5rmnOz/jfd64nf3gDj",
	"/INpdN4pNHsmBTfSEseJFBd8+ZBqNkSw1Fskl8JQLjTJZVVJQS44KwtNLqQiVXjfvnXBlwMsNI6TMNFU",
	"dsF1VUXrc+Qab12/5fVMwoJoOaslF3CXWL7yfjppVAk8kounTCzNanL83c0Hu2SKX6xfPj0fAuJv/hHh",
	"mmhmiJGECd0oRl4+PT86P39K4GueU/vFfBJWsZCyZFSkuXUKvn/nZvWzuxlpWT6/mBz/spknJc/y/XTs",
	"uu3u7AFpNFOkYBdcsIIg0IAZWxZtGa9n044PP/r5HB9fSFVRQ1bG1Pr46KhlRnMujwqZ66NcipzVRh/J",
	"S6YuObs6upLqLRfL2RU3qxnCQR8B5z/6QyH0rKQLVgK665jLWzSZcaENFbllpR/ivIfn8Xq6Bfr749mJ",
	"DIjdL0KNigKvuprCVq7FiRPFqGFnVFG8nW6OEwGzLG7s8vHZs2dbQCdeaAud2v7NDFMImty+ZAFDk8wi",
	"5mUGr01L4lNE3tcJ8Ni1Xcu3zp49a1d09uzZTNcst9S6G/OyzGpwodCa/8TgomnRldb8LVt/IESdTmqq",
	"9ZVURXeS8Ost2KdGMTtaeVFxMflgNJW4xBJnc16zfDsG+aouPhAxfCQiiBc4SgSNfWmMCN5PJ89PH53g",
	"cAlt4ZIppg2x75BayUteMOW+bRTcPgkpnjNhTovhaDAKrevSXVzEvfpogALvpxOudcPUqxdPR8YJq0GS",
	"HSoLuaxTYix87B5uL8IPZG23x3idYc6UCHTOjD0EPQ7jZSkXtLT3Pb7Yh6vkRd6e0yZkik60v/BokOQq",
	"Y4VjsNL4KcFHC9CiWB/nqFOzIr3L/ny14vmKnDGluTZMmL/JsrF6WE4FWTBSrAWteE7Lco3Hq7kUrJhn",
	"IhPnHQ0KlDYhxSxcbsWfYR0pUQKXQvNcqsKivpWmTF5Y4YoL8hw2/4wZOrfX1XyoypSlvMKVPn5XU6EB",
	"GH3YpN4ieiWvNLlaMbNiKrUm+xG5hK8Is58VKWHOiviGFtTQ1JlQUVBVEDzEbzTx787JM6kYaNrHQW5a",
	"cjN/+18gNFlJohHcrK3kZBRfNEYqfVSwS1Yeab6cUZWvuGG5aRQ7ojWf5VJcMmEn1vOq+ENY1ACRUsz1",
	"lWbqRLHCDkBLPbza4ntnQI327hix4IxNdsZUxbU9h8RkTFhlJZ4rgnbd/XJoublW39/IPPzcKQL8m6WN",
	"FH55LnGJL6QNKBdNWZ7IquJmuModBAAl7XJ+ToJ7JwXHb+XG93sMtnhZ7ejTeNMpiOaq0P94SPO3TT2E",
	"Kv5uOYElznPgn8Cp7J8LeKjJg7PTBFeo+ehZPTg7dc+cpoPDuyVbvQcnAj7FNVGsVkwzYfBWlBeECkfP",
	"80ycg8FRW2bSlAUBIlSGKJbLpeC/heG0ZWx2npIaiykASkFLcknLhk2tLpCJiq6JYnZk0ohoCHhHzzPx",
	"kXlGbDEaUNFbLhJSw09cAK+mXl2EtbZAA5a+YuTF4/OXwSKFgEUYtq/qCJwWElxcAF/mmlwoWcEwTBSA",
	"hs4MaO95optFxY09qH82TBsL6XkmTqgQ0tiLC0QsuKhOBTmhFStPqGYfH5oWgnpmwZaEZ3xrDOjCKiVj",
	"BGFF5A7qFkxbMiTaUAP3K743JAukmWB1HJsgvOBJL/oZrbJ+9pW8wgMKpJoJ9o7ljYU3eblyV+k3muCv",
	"XIpnskCFWckSR1eNMLyyUopZHZMf5SITeSRIWDoQOS9ZQRZr+ICLmbdxunl/lQs/ZsnUnzNx5uTPZ1TQ",
	"JSvI5gG9tPqN9ouZp04sH5HDUWTzwEIgz2BLHVnckgYHVCR0aXUBwOJMRND9RpO5Pfo5fjiXNROWX91H",
	"5jefpJSq1toyA0pSl2zWiLdCXokZ6rSB6xesZHYpZ7Lk+bqrNXkz3AtmFZXJdPLIvgya9qaHoAZd0KY0",
	"k2P/a18zetSZtj39K4tLK1rXTAT+2IiCqXJt+QZCklgiycQBmy/nU3jFMQ4rrbHCSonn9w+tHCc6uHjy",
	"wp4I7BiIH9dGDtxqD4k9AdXkRndwwK5DsUpeMrKQZoVHxMSSC6u2Gn7pT7jlZlQUSIfU0OCicCfPCn/A",
	"TkaeE4Th9dNvMfOiAfNjySi+H0PPrSYTdUlzNiVaEm68MG9pwMosBdxHisjGzOTFbGFlXCvQW9IF3LEw",
	"rBoD3hcpCCWlXYcDsZ0eufNvTBApckY8hmViRbXlSMqw4pjoK27ylV1WbXGAW1K8sBPPg0Dsv3zJK6YN",
	"rWocYsGYADMrXMX24C2nk+4CYFQ0NXAOuzPL8BXNGdjYMsGNZuVFkpS9ATHNBk+jp56sY93FP7ewt0dC",
	"mhq5XXhQNdpkAmDlEELb74NCRKxA0CLrPK0jr1jRlCNrPI+eThH7NTNTwkGGv+DubvArcjjoPgIunola",
	"yaLJWdFZivuvRvuclT44haEenJ0Sqcgby29yU4KtYP0mEx77LCYAyrCqNmtyIMWsYBUVxSECJ+KyFVcK",
	"LR2llHUmNDPaYiduo1EXNLcP7d1FjVSzsFAPkyLIf9QvPBMnL3QakEh5I3BsHxLFLphiIrfYSTpUO3KK",
	"CEZ/G16tmGLRHeBIUJMrxY1hYk7+KhUZuZoyAXehX0ERlFGLSoSWitFijaS7tPq5pV0puuh4yWkm8ALB",
	"FczdINpTDLIT4AJ2UYDB3CSg1hPv+5JDj4K6ME4J+lY2afSoSANPO0KNXMBNtoVUk8uqBib/wKTu5vDQ",
	"UzLczO66CEcVBiG6yXOmtVVc1nYy9G1Mjif26oZrfUQ2KLgZKKUDQQFfas2Bhb0MSrTLSGH5Qm3vNsdo",
	"8kYpEHE9DIDKLCF6/98QHCXV5qWiQnPPTYcLGb7jgWOfIITcLeYWbMLbrEBx3K4WT9UiERXSrMAl/9Iu",
	"0alDiwjQ0dXUDpuvqFhaWZGcXqBoyTWxbBzEF7juBWm01yK6R2fhgBzHDQOKSJ6zGu6r7Q8viqvowsk9",
	"QAVn1VRUEEuHcBuGZ6IAi6m9ct1h0oVsUEVpweYhYzWbhZUZHJvEVdi1VvSddxDc//7/+NN/JRbqieIJ",
	"E8wZeAdrHr4TqViwqPbOXbbvAPC7Z35F0cG5oJoVpKlhE5aFedqfEn6RHo1rj7vlmnz3/RQlFTs3osy8",
	"pZdf3r2eJ9bMNfnvaW9BVmlsgDjscWYCXGmKIck4+TFBMiwsuIMS6G0HxwyvrHh7L0DcaudLDPBRjOoU",
	"mPH3lpCpvd+WilYVNTxvr2EVIwiyePjQ2zHC7r7RjvhilDnDi0+hsdZ7qiKytDom4BTyTsLe1Sgioc0A",
	"ZNOKUcHFUrs5/T09zYR9GhtA/UcK1qXtNWW1FbJsqKLCMFaAvQXlQ9T0W0qnrXLtsdrhPBKpXaVTyQH1",
	"ezj/3b3v/9j3ktXUGKYsuP/vXx7M/jed/fb6wP3j3uy//zE9fv1t9Ofrw7/8R/r+T989jnt5XuuBOgXW",
	"Ji/IS9WwKfkrLTWbkleoUdlFe2XIPp9MJ/DCZDpxbwxjGILJsb8A+6udKMLwyEJBgNLIhZRz55Sb57I6",
	"ai0YPZ7x3Z86ADv4BcHy+uCXmfvXt/6nw78cZNl84wuH3x4d/uUggvbrX2YtqOevvz38S/Ts8D+uFSES",
	"91LLeQOdhdNyw6VkiY79tqcBl1ybWUXr2Vu21sF1/Dr1lhumorUdtGOgSFh4O/YLd1laPay0Mkr4mFT2",
	"seOk4Rr1AqpTh6wKmEtV2JvUXvvA/OiClxyJwuNXT1KcTCc/ykUSvX6Vi7R0+yM+aBfsxEvPLX+Ui3Dt",
	"qkYIz6Sc+JiJM1k3JagBUpRrWK/9xgmtSXHbHvTzLS6qp8n3OoJIEAKjq8WRa9Dykzx9yMdH7/hngzt+",
	"Nrjj2wu9c70kt++VFlzgC3aR8HL2XyFg1NQecYLeM6L2g2Wgdfg6Pc1ZSM6YyqWgaEl9JsVSPnqIEx3O",
	"Sfc4M3ExrpAkrepPlExZ6h+cncITf3hL+MNfca25gln8anWceSZOL0j8sb0f3DXHCrz+w58EbM2gDi3a",
	"UFCpUBCEKZ18QsWaSHepcVXMaqrMGu/KaWc6z5/muxu8gcAd/x7dYGrYdOxVytSww7A9XgtL95Ey19gM",
	"LbP0HNXIiudwZboYx56uzH8Li7RveFqM1V0KHhNp+Zw3r6LSOaKaA0dMaW7n/tFGvc2z1K1lfSDc5Gwm",
	"7C0pQy7GLDXvUx7W+DTAmH+N92vEqR9b3jf5wbx9+8HZ6d4ZtneGfT3OMCCNbT1i8HLKgLTRrxNUPDvy",
	"c/TIkMv7njRcqE1XcgL2k4mu/wdNE54vWhUZ1uMNW5HjBykgbbsNryjnoUi5lbh2yxvutudTSkon8Que",
	"7wx33uX+uQfuDh6pVHRIZzG/DzxJ4S+/ruiFsRUN0K3gui7pOi0zP2ofJoVCH/G83VQ76RWalSw3miyY",
	"uWJMkF/lYobWF6upe4lvVjlJLYx9M63BW0VOpNBGUe7ytdK+kOilQGq5rGpqOGouXpiqnJ2JGi+rZUJT",
	"wzXIcIu1vTGCxXrBLqRyLDAGpfdTNXbvYOZBK3UXlf0l+1eHU/21v+g8j201pcs7cjG/8WrR2dSzrANt",
	"ZuIxzVfkLVsjXvx4/vxn9D2xdxbPISYJx3LyvJGEej9aekQrrjrtfkqyCTIBJzDZA8smRKrwwLLIc7T7",
	"2n+eVlbQ8s5iLSsGO80m892CJwc0+KtcJHXJFoStxotGTyCIDjL/kNkvssmcPHOAbYRmJhMgwg306ayP",
	"uLiLfvQqOPx+lIvz5J1w0nnuOYSPYAoGtFZ4CS7EX70irBqh3Rpd6KS9Vp22KRV5wcDv3HMvp5wSFU3J",
	"CCf4IIia7k8j7cxJlrJ9YBuvkhruaeX0WzCFwh/bMcoUarjIi178Xv8Y+u+gSRF/nkEgbkEwGuBFUzJN",
	"lmBeRF8jzYRT91lBfOabLNHPHv39kIvCmc5H/C3tDGQlLZ1b+cYqCcHg3cbJUvRMr4lqLCkuGkMKyVAj",
	"dVgff54JtAlcraQLYrELrOsSHK+ShHja2Fk4eG1cx9bjSrZOuaSDVgvb6ogsQZBFL0vVlIbXZaQ14+lE",
	"arfVn2nuXAcgR0bCBRpH0V1p7xx3UGEWy+nsAGF4csXLEgzEZSmvWDEn2SSb9J0SXUUezjqbfNt9j5Zl",
	"tOodaGOD+a/VeYUU3qv26sXTxAH83H3BSfoMLpKaKsNpSRpV+sxVzKZyutCKXjIQADWcOyHfItQdTBDh",
	"wMRGER4XTVlOyQUHvmVY7S8Qe99k4pzbO0RIK5Y4NQKWhJHXpsU6MKIEE7xVNGAODPO30ozl2xFR6dgF",
	"DZoGTdFcJpBu7TXNOJhaIBzAor49oRYbDnSTr+ymskktC+3vM81yxYzOJof27/5GYJedb61OkU0OpwQA",
	"BcqMNKsPjQJ+DVH+cleeiB7D8Yv2crmy+k8QLKIU5hTdE/IgOACZAQ+Ne5tdMrU2ECrDdSCZj7TPDXt0",
	"6O330x4o2gH6+/nm22/6lNrynQ+8+kumFjqZmLnorRp/QnIM6Pn0KSrhbnlWaQ+yIXOCmtticl8w/Yfd",
	"U89ghBu81vWBglpaEuqJQAPJJ7r9seIACDW/ysVXJMrUm2SYvvASOOom8cWZtawwWcsC43EoaaWZIMbs",
	"5Ze9/LKXX/byy15+2csvX6/80vvMCzOpD+ueVXN4V/a92P4KWYElLmWeGhqcyMsVy4QOdm8uDPowIOtV",
	"1kwcByss+mUwWJmRnNYugiMT8S3tnPI+yOrs9CXYjXRTo490GkKaIyNiJgpOS5abQ7B92nv6Qqoc08RP",
	"Xjxy8Y49yxr4RjORsKyhHW4YKcornjL5PoXf7ZYww6ey16GPJJ7CHmYuTTL62d54fi+a1ExlwocwxxZf",
	"jFXLS8vpISSUxAHLURpH7pyemUCruL14X8E+ndHWMh2STRoB+7DnRw60sXe1btCb5kMCpWKZeEbfnVqE",
	"JznjJYTDSdEPj69Z7oLVfVISs2eJbINplgkACrhdLE0WTkRE3/RBCMlwLhkIomSLlZRvDwE+aO62x6tr",
	"6hIiTnymCK7hzz0Eo0XhHOihUgX4lYIx3s4ua7CcnUhh2Dszj7xdeJYHh8PTr+g7e5KP8SBdnHsCG54l",
	"3/MyXEXf8aqpCBY0ilLKYWHRwVuBixqkGWbIvOZGzR0W/WBUE6KmIMQecrDIY9i3Y4COZKxArblYlgyJ",
	"SRvFaIV0Rs7Onz16OCVn/+vkMCDZd2TFVG+wTIC/8pKRvz94Cinn9taCwAU/0pNDEiU2AIH1I43uf39t",
	"9GhF33m/nT5jykEvCeTEe+NAVixvFLiYA8llwl22lvYiP4Mbigmj1jfcwSbcuB4h7MyQ8OOWx0Xr2kwm",
	"K2xe5XfDVSaVO24UktaYn9OiT/xGr2iCXlGM7qmZmnkoAsrljTaycilemTjoMRF81b45x+EdSwki7IVi",
	"bGY3CDxB1vSfjSUPGWdD/rmbFeZ9vJqkIAfLykRN16WkhQ6qDjeEQxQv+Zv7/sCzN2a1dSYKiy74GcqD",
	"mRj6eS8UXVYQXIBLfHUKcrNiwL4pqTwrs3sCTSAT9soI/soQuOyuNTsVKN/GdGKvbpbU6BiDtkBIBPZE",
	"T30oNovLPoSrxo+DzrsZF5jD6VLl1vNMvNLowfQ+oJjN23vL/T7w1VlcdNXCti0H5iwyY6VfXsSPd4xQ",
	"cEPvFKLQ2Vke8l1D6EEm/i1iDxxofky5P1+EZ9d4QSMYgyWI94WyEc8oSTpGM7H3jO49o3vP6N6yuLcs",
	"7i2Le8vi3rK4tyzuPaN7z+heftnLL3v5ZS+/7OWXvfzyVXtGgyvRW4n0qBE0eiekWTt4BktzB717WRmZ",
	"8DbSbrkrNAuGIbBiUV0zqgLMYR5nHXP1/aB6FiON9sXFYNLTqFTH9kJRw8csiq9OnSkx3Jyt+R0t2JYg",
	"WycxcGglhWEC0vMr7zEKFd0cSKZeNkTXJ9iXobpy5Oz0lWuCIRUrZ3jnolGMGh2zcaqdP+DPyM69uV0K",
	"DbWYuXE+6tiAj54Kd+E756hLva1kQUtnvoPNwqlXrpweyVxhp2wytVycG4X/cjsDttzW6vLIg8ftQX5L",
	"+32//G4nXWr3SlKYD7h9OanxlMB9Oad9Oad9Oad9Oad9Oad9Oad9Oacvq5zThyvJ4dtFjsoa0MHQKYwu",
	"6mxgp/FCNhhW3nFt2urGIBbqz1fBnnzAmh3kmpId5HNW7Nitw+egMktC5/gENUDIhyoBQoYVQEinAAi5",
	"O/U/tmlVB8UZqhA9wf/ZYNFnLghtTWRzctrWeEJBMzQdC8gyJbQ0K9ksV0TLKjKqYvglNIGhHrZQnRvA",
	"inWuOmXJqLBar5K14lZYwR5vjZEgQtCyXM+JLypRK15Rxcs1hhj7UnC4OntxFKyqpYFSbZayulE6QPUo",
	"U6TO7Zbt9/7ge+5tU+doEwPdxDtvyTb3HPMOc8w9s9wzy6+dWWLxPezsmTwQ9BzG3Ah/cQeDLkZGnZ+x",
	"d3zz1snQeiG5Jvb0LmnpgG8HzXx3jmzSvor6e/zIO6qpkMKCv8cBPwbk7EI+xC0zGlPfK+C/qYuUj2Hf",
	"N5Pa18/7yppJIepfX0Gv1xADusQ8IAMao0Qx9OhMI1d1t/BwK/Ohl0EcGFnQNXo8zu/PfFmxkh2Sumwc",
	"a2q7ExLBWOFiSmj51vWwyMSpaxITvNyLtSvWpmR1bBdMyIxsTD355bX/5wt2ge/H1fmiLhf4cCzin71D",
	"iux+kYlHLJdNXULijm+9adGRi4Jf8qKhZVvY2CLuW6YHZd8y4XufuFSlh8+mpF7a7+xyDkmtaA6X6HE3",
	"iQSTNrB7CKGZuODv7AljmEOcthV1CvH5h+BvqhtPgpWLIMiEawsahPV2+UNOqu8nXJP3W6G/c/ZtN874",
	"Op9n4kVHRnm5rl2Wo76fCozHyIyf2DrV8/ZBePgIkReaoswAEZEAOSAtF3Vj5uTvocsO9Xl9mOQInjkf",
	"x3EOARCAeYCCUV9NfPSzb/6dl4wq6Pzirapzgkgs2CVTpHa9WEOnly65uXsjxQ8WTf6WpZQv+D0VZnR+",
	"n+BH6dZnqT0kPGLJraZmQxglu+q4TEGM6wLH0N/P//Hg5OTx+fk/fnr8f/3j9BEAz/56/vjkxeOX0UPy",
	"lq1H6jA6Zp/sWfy4fehXGy4H+1uAUQc/rYiTJ+oa96yTbZaQhkZrwT0VrykIeBSTagj2LFYNtOLm+tWL",
	"pwealReHk/ev34PXI2dn1KzOzbp0B+GasF2Agbu3wb923icup7WmZjXT8AvEGB0gBuBJdaKSuNCG0cID",
	"YiW1OZyTRzgniCMwbbo/ruU5KeHpBfze1qZfRhGYm9ERY4wC9Sa4SveFbYj7nDES8YPkvJdM8Yv1y6fn",
	"HYgb1QwA/jf/JsEcV03sv3PLlyDYFGTEEHcK7elaWNoBRxLFOk2ZkMjHqLOL8+EYxk3wfSB61trruWdZ",
	"j/1gTl621zay305qe+xb0fcTfpT3iSb/N+kdhRLMNj7/vhAz+RB+AjfYJmtX9MptjF5Rfuze9nU3bV9e",
	"G92bwPYmsL0JbG8C+8gmMK/MjtftHjF8+RCafcuIvcnrqzF5eZq43toV6CrdQn1MzmvbPse9wMkFo3aT",
	"bcBWsEGhScGVwZli6k3cjdy3KofyEUt+6UIlQ+OxuD8MFGBC8SMTIEa2LZ/b4OXItkPzXKqCi2W5Jgea",
	"Fyynyl5vSyZMrzDElDCTzw/nJBhfUp2jotUw/eduK/dCYvoKg2YGWI4GKvOQBctpo2Fla4jHJAVXLDfl",
	"GvDWKp8J41iqBALVOtlv68Q9iRv8Jvvad8xljiXB0mQc/x31NGp73OP1BMlA3WIP/eINEKUHxxP3A/im",
	"tfNZzdvS4zBof7jn65tJxXu0b8+7p5QoP3B9N2Ax1uXXIXLKwILlwoxcLsvdiAMMC5g24OPm9Vte637h",
	"rIPD0IhdMa9DWX0UuqxDNbelkN1mX5GRQo8WOQoVjrztVHe1yJ7JdE6gSwQieEVrTWgmSrkEmQIEmYNL",
	"rsGCZDpNme3qFWtcjZnIDBy1dY7MyYfYXaJrEvQ3xJyEclJtdgJVUb0XVyfKK/S+ybfAlMC57nyOFWww",
	"bn9DVmayEFIEtv5q+/2r4RLPqVK8iyIuf/MgLAqL0B06oqVqif3Db0IfnZOJTqOxxBFwUvvm/WiepaWW",
	"yKzxuoZ1RCeGSwKgDs6tF+f5p/uJu82CO12wKpiTYimfjdUsApMXiBAS9hFK8gVGnmCEktDCCmFc+xJr",
	"yIhiPOyVY0yXanMZiYlybT7/JK7X5hgMoYZU0mWj6hFEMZJAK5FhFbk/43lZRQAr94UudH7JU4xaXrtM",
	"JCvDOIn14OwJKdmSG15Rw+zSsUic7laJiyhIsVoe7txQCi3bw+pYACDMOnQJVm0lSpRW7GYQ7+ITa9Gs",
	"fyy3La21NT8P2U8darnehOknSJr9PLUnWHLgTi1zaUviOa5hqH7rEDL0uu8sLxPtODVG5sdEfOB5YiSQ",
	"tclQpZT1Ieay4In0m3b65Svy//0//29c2s05d3RNr4QmJ0qKH+UCeA0kCIxLVC1Td1l6PYMGzZXUWAdw",
	"4M5LptVt5N5+qojJ0DSQu/cfNhWNKkQFlvMylq4gLwKUOVTxQxlU7irhZQLH+8bKLT2IRtzDgegl1W+t",
	"WA/MJBNn/+vEb6Do7id2lYYRD+fE92SdOUyI3KxWRMKDtwRI87e4xghVBixGr6hyqlsmPGY4mH3jBLFd",
	"2Yarq2bXO4tzRyJDT6oVHMtEhEXfaH8juaFw8HmvMpuTvbAuWbfd7AUtS0wLBZaIt6UzowzYVvDuUYfg",
	"iV53i8a4hOMCay16TFDUZbJQAQ9caz3ViFsztlylTBuWFr0yTkVBVUH+58ylpNlHbYXeHjK3hodMdHuB",
	"BXkilJxwl+N80s+OSbgsd5CmPdTm5AEpuHbVeQNRWf5YyUuX7edrPHRc/KWExDzuG7xhCkuCfwyF5w1i",
	"FvKmct2mUPXX24EkiF3cuFoJWIsZdvCWrXuhCVYCciUVUAoL0QddDMfYCylaGo60SPLzOCclPUaKUIsh",
	"0ZPjrjlPxVw16RNZ83SGfueF4DiPy75ajuoZk5HkLWN1uHhbcM3J/2ZKkgOpkIYPXSGCbAIf0LLMJnPy",
	"M1siZ20TxTKBeNxrqbtNrdje1Q4k1iLxdFxrrFxl5snxd/eGbpM2HmdUNeup9n01IxllsElXcH7dyWSa",
	"wmjnnHMTmm5WnBU8Ly5YbsFahp6IrgpI0YAQYo/viqqi30CRRzV8MTceE+sCyumg1EKqGeRLhsxTpAGw",
	"qMA50hLE6JwpQ7kVxK+UhBy+D2/HPto6ZeD63tMpU0MHCXbFoD5aeivRdFz43DqAQ28hj3W4SBvS8T9W",
	"VENER4g9OyT/+hfp/DKnZXmgv5sSfPm7VivHd6Mf8NV89d20N8QFLw1TB/r7KYFBvo8HyZp7977/E/4/",
	"iR/NwfWs7YjfQ4n67+egIP/wg/3jO/jj8HCu+W/sAIe5n/9AvusNGK/Pr2PTgH68H34g3x26SJfW3QqO",
	"iQIzK2l51qHdnQQpXw8pFOfCCUhaqBqT057RdHP/pzKn5XNApBch6rGtGCvAc9gpVyVJyQxZy4aUEkJD",
	"0NjVxjE6S7+r5bznZV8KL5tO3mJw0kgA0x5/9vhzzV04dPtC8fmRIs/hmReoIdYICmtI5erW86gmjWd9",
	"rgSAfTFlcupbQU78d6gs6lurYxtrGrbsmgpiT0BZLA6ObHjHSKs5zDPh1da25B1Hi21jQlgFhDwHl2jY",
	"jPNqa6v46zbm1ju7w5DzsVCHEQ0oFCTwwJ4kdQOo25ZUCvBJ79qKlQL3QrC/daYayPCpohhbFA3rtPdO",
	"TzXwx/Fk2Rz4HVxgbWCw7pQimwbk4wj4uX+EH09djDA0kdFxuXpX7EtBfkLEiwpWM1F4c1gmHmHYut/e",
	"gxJYpz1n749aUsP6o3BNeFU1WI+GnKJvFazcrm84kJlfwyZXyYt4P7HyIoXr1WG3fiYLS83zztu7uQFB",
	"JoUODZ0g7M40tSzmCSiHYpBnEqKhfKP2AAsLegADJiq4MlMuRoFeUl5aQEH0sCVZGh1PmgYgACHdx53p",
	"bth6vpKaYd0VGmKsuIivI3v1ARLOM3F6gVfDNC7DF3gAvEWgnE8RrXxKoArSFddgQHD1uBTTTWmi+BaY",
	"+xZe050KYPhRNhfAmEbNncZkZirWzy9AoRlwhIHE8rpbiyTL/vNfM6gncm/236//E6qPQMGRw78c/iv8",
	"9Z+HhwcHv/z07MnLs8ev+eG/fhFN9Rb/+tfBL+zx6+3HOcRaMJ1Nc2FmUs3cEv1Vkmxl1e3s4lvU0Eo2",
	"wmDFlqpuTBzL58sz7iwidHSHI0zZCRUw9axlDkeTZAMKjMH52s/thY9F6p0cmp82npwnOST6MBDXRGLD",
	"GcczwkmAiFBE4fcOaXhbwoy9s1csN1Z2CJJFJgJ3cFltvKpLuCDh8Gf+DgNpdN4uJcfQKvYuZ6xws31a",
	"RHufjLIfyaNt/fibBQAsJgYhVCXT0RM9DU7ZuKwqJjwNk8T4b+zfF80dlLGozFAzfL9bckZftGxvtFCr",
	"cSSNJR3b6WXd9LgDSXnLauKD2ugOLToheO1cbWhqi2QYoOTUFHsVuqJm/hsUIV2zxWziPJFY1VLJd2v8",
	"J9rNH0B82+QQtAWeryJEhVEx/6orMBLfg5AYWctSLtfzSXKnJbPbxPLkgMVl6bDYp8KcUJ3Tgk2mk+eq",
	"XlExeW0ResPT19NIDW+fd6H6qDMzMDclS02uIJWO1jUTwNuc6wMqrYd+Pb7EaZSlGwditSUa46Bi3+An",
	"E25N5MAt8xCOUDW5k+9DuVPpPnKBFO1aMuEXw0U/LK6N7r6yIp9zX3okQRnXirfMJ1KGRWK3RWIY+mIL",
	"eZWI03rofbLySvjolu4xYtVKLhAjsAZiBF8st8eNzkRUE7OghvrNDJKk60YtrYKpiGJYm3ieCTzvcdBh",
	"N8KR8+MiE3VJc+wbB21JL/kl6x6a3xbGDlEBsdQKa/ACZlsM8McAwWWCXZXrGWQZsKL1fKFW1EWHFegE",
	"uOGXTFVcYN5EvaKaEbuN0tWO9rK5dwbrI7cTjeGTC8aExy5y4JALionjKHGoQXvtt58aqQQe9gE06oTo",
	"Mc70YVh3UGCcKgetKklpAdYiT2OwV5/8jVkdL4JfJlZWHTdUGVYcE33FXf87PxOhFxawbSlN/+VLXjFt",
	"aFXjELBczVzaOrrdfJO93BFVTc3KSwzKZ0dkghsw86e4+7KUC1oOmfsT+L01JYYApJJdsrIXSRAqa7uu",
	"Bwh0w9toUceMdZxXECuH4+YjXEjcevHWBiQ/+nhf4FQWsj2bhUXP4H4ON0itq2LhLhCpzVIx/c/SXhop",
	"iPs7IXFLuye9aPO6lOsKU1Tcc+gWYvR2rodRz0abSejGHQkUufnZ+Q09alOKMvEY61nqY4h7KUgO0rkd",
	"Fv6Obs2pt1ahqYXmRiqMLb8tBlyfwhpgjUG4/qTdEn3ha7SlMScgWCgFc4Afgbuw6REooeLhlI1pH4Du",
	"jmxX4+0o28lS14puKKi4ArZI30EPca8sGlGUbOqyCLCCs89qz4R7C6Uvy7Fj8aibnXbG1KyVwcKHEJrJ",
	"BYkkPUPfWiiwnBUgX8hLV6IW19IBWQjjDlTpiYcG6PktAJvCP3YE5FhSccgR2SafOI4FGbQGityWoxKw",
	"D5Hqla5tn4suo/K8NzYsdieuZbGpZvneu7T3LgXvZD/URjFawCW2hc8AaCDdm0EaFD+uHeX9Fn289pX4",
	"95X495X495X495X495X495X4v7hK/HCBCwYtB8/Hg55Ohi/5aoJR4cCocphjD+7Sc9/6e8LRkS8yhnrL",
	"rG022VPYZt7KFqVbAwf09oJMZJPfPaub2V/ez+ys2QTYgLyKtMBgQDqASb0dy3I0bKjemqHc+iDk/YqV",
	"5QzQHM3bXOga8qzdsOdYbIy4Nn3dtqXHWIwwgzPJJsT+b0YeeaUBqCHou5UUS5m0bfhRPFyyCZkFR0JP",
	"a66ZyqWgM7he1CwMGgZZSW3CUv5PqQ0aXhQ5PSO0KBTTOswnVfvqmVTGBbf4541mCo5hEu8q/OpHoVpf",
	"SVV03wq/+rEUd1ORGflrA+ptQJ9XL04JF3nZAIijqlp7DeaOajBgXU4Y/cDo3LfyRcqzv2nOGJDTZIp2",
	"Qs2lwD9PBbcnz3/DP1+AZjSdvKoLEDgm00lk5Ia7imOWA9qy8cfzRtdhAveHf6mp7M+vb+Kd8xUKPe70",
	"DDtB3G8FRZ9eFdKA2xz75yjyX3ClTWCA3IuuCSYJuZTaWwFcHYquXQZ5BaKXKJDBASq6PB3hHEC6WWj2",
	"zwbKTfSmBl0EnDGX7a4digMJMaFdmQ3oyOrZVCaaeqnAG4X1g6xwhFqMs73GCz30uZi8REAZxZdLSFUX",
	"mWhEKLYUcMiPDtlgrjpbIDng7E+4eQ65ObLU5OCBWsqTR1Py17J5d0jYO8tcgnoH6l7BLy5ITsu8KTHH",
	"AHJ83Tqn6A5ow9hC42IomaHrRnHZgPQ+kxczvRY5oSVTZjvf7E7V7vw227v6EV63m4JVerWDEm+5dOh2",
	"gERm9PCKT4mjYyKFW2ZUUdR+WiRGdaEh4bSDekNerpgGZgn4b5jYRogAH9pPgYX5Cx8KgIDrDaqdQCql",
	"Gw0icOFKxRx3dRnsBX6pvoQPrGlNLiRUHEvJCH2ZAkP42g7BQxOHvbSHp2Zvb890Vsmb3C7WLZEYmTob",
	"fw8neLV74mfwb+JZNGZl72CUc5IDS2VS/cFVWHLdShRbrHNrR1KbyWw5EMbfODbH2+pBWyosHT+FU14C",
	"Fjqhy8lYU9IKbVNSrfU/y8PURI3iiW6oVsJBnZrNFg0vTU/+SY7kJK3EcO6JX7p/c6uzu7aoWbqiZvz0",
	"RsU0Q3zJvo7mXayjGUpv7Uto7kto7kto7ktofuQSms+k4KixnYwEV/TfGCmpWYXXEHX27WT2tTW/ntqa",
	"+tqamgNC61NGXVUJsfvZs1amO3v2rFUKW3q7pkWICS1C6qpK9Qj5EN0tBoZqPTBUewXvLVtjt5qwrze0",
	"5j+x9RuochJMz+5dlz+QlvHLlIwfmlhEvSssHFGz/GCdDTh6MaEKkG4UIy+fnh+dnz/ttzY4vehmZMZ2",
	"GCRJu9zteh6MtTqwkLhZZwMfEBihk5GyjEzdFmkOY6uhRdQbtjPYurREXVUOrQnvS1Qeoe06QkEJiAeF",
	"J//jB/JNXVXfkH/9i4QqE3VVHULqxNgUWKzPmZTHp/kfnRFDyQp49wc3MVZuiL2DDp9+n3DxSjPXpGRg",
	"stHbxFxdy0bcFNe1RDm1r+H1cFHSpbOaokuZQfYPFevWneOMmGzIdtIlkUqqzfMtogqeJt/zyAlmeVf1",
	"J5Z8PVSC47kPlaRDfuiE35HlugOK4sMS+TvAZEZFnPP4sRVNrnSPP3lxZ34zsW4nm2YfbGmTQ+qtG5ke",
	"BiLi3gRxF00QAxazN0XsTRF7U8TeFPGRTRFnWzsfeqYH74vYd/PYWxy+GouDp4nru3kEuhrN0rAK4Q4F",
	"5nyqS0esqHuO76DzDJWDUO9oU/DH1qnhUaXDsTciRnOTenqhrhTynU2Vpxxnan3tz7GyMLm8P8g3C2v5",
	"RpN2hA+WCrY9ANsfloPcxLFEyvidLbbLyDLkX3Yz/G6315CStkt5xN1RwFdtSOHzlni3CaS7AfOa5Mbb",
	"wXSr3TR8bCevTge7eHVKlJXy4EZYcV8+A2Sh8XICOyJCzJKSYWOtXSVvMAy2GzamoU49di3WzGhfXQUw",
	"JUoLDIW3MLIEgw+rxjRQWq3NJJyTVxrr8jvDaCaojw+75LTNnQOad4ucY7oKRhJENbOZIdSv17VJckNh",
	"UQDXPbUNrLRQ8RmBPTF8vCiXW8TDkE9IA6xcl+xEtmMKDJmI4XDW5jFestJSlT+LAHoei/VHfuz5mlbl",
	"dbmFY/R7bXhUSDKEJjX9WhoooPFgjXESTZTrEFI3f2JrHdcZ6w8V1XKL7+x5u4SRYhrhBu3XusDDrqh6",
	"q+O1+HLgvMJyPSRfSe7rV1DRGvNkBfUaYsxz2e1WTXv8jkL3KRkOyAu0UGTATX88arKebtF2xmmtUTZL",
	"D66ux0E2+a/5vfl332M6MlKUxcUk9YQOF64rjXTZwHGm7QcqU7ZTTm049W3su3HlmkHy+z4VcJ8KuE8F",
	"3KcC7lMB96mA+1TALysV8JauOi8XpF108dMbuebq8Sabe5fc53fJBRPe3hW3d8V95a64HTxKrrJesv44",
	"FvpL+pOUL8i3j2Dd+5O+Fn+SI4nr3UnuxZs0cIyICzv13rh/oxtlpH3jba3JFnTngE0J81t4FsDkmwOE",
	"js1Q/hR4NLIZQDGuXQmxRNVn/C4dd/swPOt0eYsycENDv3Svt05pU7sUbDo40jwfVLOQ2eyJo1PyzLUZ",
	"TCEee4esJ9G10T2JaprT0EYVy/RqIiTJpbL6tsQkzv7WMuHS2H2AajsGfcuEVd6hDpu8AO/J40tmN344",
	"BnHY/SawhxdSBTQHDfQ9QqzkVQfowGc8aNyCk+C7noQupLryRSX7i/hGB4zruoSwb3cmkgSG2OIuJqoD",
	"fUdNSm9NUFED8NEK630MT9QOTmM3FG9usaqlxh7EXVXiDhluVij7SNLdSEpX29C63CPHSK/y0Pm605rc",
	"E2KHC25uUj7eDLvnoncV7AbsrU3FxT7uYYl4O9pT4FXbQ91JtC9DmgFYzibb20a3zwlOg+44zEmkItkE",
	"pSBcgTekwGan7tFNo9eTgmZcins8XXeMhcQ93ePq08ii/dNMgI5BSyhRiIx/hBpcxYmoACoo/OB/GvRO",
	"/0aTc0QcVpzFFoDN0Imux97+X+/gFvECxzZekQ0yR1VDiaEHJl1p1D0MmNQx77fc0r1IdJPnTOuLxrlK",
	"t8PgvWtm75rZu2b2rpm9a2bvmtm7Zr7AKo3sHcsbu7JnsmAp3TV6HBkyUEcOH5PKPnacNFyjTnbJhGuZ",
	"YQXnXCpva0XuR7GwXac4W1eAn0wnP8pFEr9+lYu09PkjPhhN0v1RLsK9qxohWi6F4lYmzmTdlBRLOJZr",
	"WLD9CNqIM53UYT9M6h9wwyAIdg3cEVTJyYstc/1Gr/lng2t+Nrjm2zu9c8Mk92/FMWqkcitMFvx8PngH",
	"dRvtsccPMhMUatx5STWycrJMBBHf96hxRpEzLE+JBs9nUizlo4duqsM56Z5pJuyh9pAtPuCB9fuJkk2d",
	"tH3DE3+CS/gjsqnjwhcM3R7emoQZ0vHHEPLYzZcOfxKwCXuPi1OBcgsZKw/ClE5MoWKN/SvtpaeKWU2V",
	"WeOVOe1MFzrm7W6YjnXT0Q3u2C+3pyTuMGyP5cLSpyMBbdtUl3T8KqVZnftHm/Uqz/G2lsVDWf3BdK1V",
	"IinjqVZB/LBl/xzZpN3u0cMbed29o2nvdL+LTnfvPdz73Pc+93366z799WOlv9p7j+WN4mYN/ktE/oeM",
	"KqYeNFa7+30CjAnC7OHndiK7/Mn792CIvpDDw/kDedApRJmJB9CGMPAH4nxkIEA5giFv7EdS8d+wwDrB",
	"xZCsuXfvfm7kWybgn+wNWTFa+ILx1DUPhRegs3pJuZgZ9s6Equ/4LKfCHr9cYP9Hslg7O98bhqvJTele",
	"tedm3jgMgj98P7O3DHs51gokZx6wROeKMTHPoOomN1C4JfIGuhttEqUbTr6b35vfc9K7oDWfHE/uz+/N",
	"v5+AVr2CEzlyrseZh/SSJWSCl95Iu/Qr9R5LkBR9dy/vbXWCdtRmzQu1oc/gxOsUXIrTYnI8ecJMW1b3",
	"BN87tWuygo2updCIQt/fu+f88oYJg2JFaD939KuzbOmQyrXpRkxPCIjXk9WCBZ2EVVvA/vEDLuaxUlKl",
	"Jn8l9Mj0//NTTH/qhSJXyoW5F6cT3VQVVevJ8cSBD7iPxU+6BEtFC9/Ja/uBRzY9imggdUKHOvcm4BQm",
	"GjlMnw9Qx3504kf+iOji5gCxeQckuTOnBMDNW0Alj8kqUY5fhdbjMxRaJuHb+CyPfnf/en+EruWZI//r",
	"uYnVH6Avv3dme8bh3YBBQ97AOOyuIvcfXFg1VbRiiGm/DKfvuivd2OD2mxwDa/QqZtjyJFavsIRae2D9",
	"6/H1R8RBEOKj7Y4h41OnmnUB28vB+7go+XgMBXtrahER93UNEvaQbCtUPPo9inp4v8M1Fy81QkdX2v1N",
	"NOobxKkB5r5xS3ozculFZ/nZEXd63YwxONLTLjrbuZs0k0LWh/FB+4YEcMP/8eNTSmdyq9ZeyEYUn51Y",
	"nzDTP/GPQKmtpnH0e/h3IGAnUt7kMvGfDmmyG1my1d1y7tdxZ2kUN9QlVN2uOjF9q/7eQUp1AN9V2NpL",
	"5MOLNsKCLv0SB2Sg4zrZKCSQF3pjNKFEsKveyLegsBMYtnPkd53EBpHRHgpX3DIf5h1XH5zowLzxUGI/",
	"349Ebyl8ezncqncJyO5+uxt6P+AU333ile+5xDV6O5xc73A3s4lrr/vAbW513+Oz98iQSpZyoAXWhC/o",
	"FEkORXY77JuEmB6W8gZY1kax/RFM+EUxraRc8CE51La6w7VT31IY+eNY1kPACd+/Mw6LvQNM4bOK+ojR",
	"OzGC3TToj0uQQY/eU+PdosZ7d+bC/3RqvEf1O6nIb0XadbOJtNHh/gmpGzq07q/bu0Lgd1UNcYEgW6gh",
	"9/ZqyJ4pIle5Q7oPlmi9gRXmw1hfvjizyxdtbrmGwd0l+8omj4UL0e6rUp+VsDtGjZv5LG5IwN7NeHOz",
	"xYiHcdS5eFOrxRdH7G2G+2eQoja5Om833/NLphQv4q1+g47mOaAHl+JMljxfkwW7kMoZLzCTLnMnmk3I",
	"gSO4Q6JYJS+ZJgvpOs4xsYSqxAjGEKDrQ7awfIAg5/dhxBfMUC6ySRhnwxCLxhBfI0EPB/v7igmoymt8",
	"wkMIEccQYimicghQDQNrOyPuAsD/2TC1biHeBckkhrRPMEKQTKZuJ6ms+E+kpW5gm2MWqE3Wq3Gr1acT",
	"4u6O8NaxV6V5/I72qY/JeYN5as92PwvbvQsU/1kiSu6iCerTSGQ+P36nwBF7fy2obrPrbxs7chpW8UUQ",
	"frttqtjHIPyPToge4NeFRbbocSciInmEJ544/FZ2D84YoPGtLQRhLV/M/RW2/oVaCQLER+wEYX83tBTc",
	"+3TLDeWgxqwFH9xucavV3AXbBW/pLckOxm/LDmO7yX159Lv/5+5WjCHjGYrV/tEHNGl8wdzpM8nXEX4l",
	"Jo2efijThh9yB+PGCdU5LbrWDY9sVlhzIq7FkbZuRtubCvOSuW4rJdlBn6t6RUU2ISWjl0yPDYJpfvDN",
	"tmaMwFc+kCHDbX8ydWv+LJaMrRjpTtaMa7/6JOpRWMWds2hcx/m3tGp8ck78hJk9G74DbPiusIRPa+64",
	"g/T8hJlriXn7OJtPTs/oHd+T9F0h6TulZn62SJutmI9b3V6y6Aa63A2dMo512S2fT4eya1vzwEzcjgnG",
	"JtyHbt17TvhvLNzgIW+XUz/Ex689iSDKOUTgUJHiOp/C6xNznFwKwXJfr3Mz01HMNMpVt2u/69Q0v5k4",
	"thMrgjr5iem5yMvGWVRWUpspqaUyU+isbQebZqKmWl9JVWDxOkpqxWaLhpcmHu/Vi1OYQ7O2wLdipA41",
	"NN0eQilOKfIuU8lEVF3VzgRF/K9RDE/ag9hz0a9ARWzP+5HXB98nmpaPUlmXr35K4U2qFPndTeUysdLP",
	"LOL5CqC7yHihPV3N1IVUlSsg+NnEvRd+D3tO9W/MqeJCuBsEvoCce4kvIfGNkG5a+PP1Zzezo8BBduNG",
	"lRTcSIs8MywwuhMLar925UnBD0TJkl8yERVhTfKNZ+HjEzfznWMcP/ez04Yb/qJiffog35eKuUWpmCQu",
	"eKJtIb17MNJgYKia+mD4e1su2rWKe2Mx6o0zOWpm5pl4CH17nMfVP8dK6bUVgS4ZecvWWLi1W2JYMFbo",
	"zljnTb4iVEPHHxjqmNRV9cZ1aHpj/w2DxV86hajwpWG7HQlHw6f6mPol8oYvIHCqD2YE/pmFtB4zcD8b",
	"Q8PPHFA1QJk9Y7tpdZsUKo9wtnGJJCFa3FY2uWmJmyHnHEm7n4/ES30Z7OgGnOiL44HXVa75mhPHh5y5",
	"Y3+5M1zGBe7swGW2jOG5BZ0/YWZP5HeSyPdiwp6JjBh0d+AgNTX5asvQoVuwEYwc2HOSr0dlwhPfrDJV",
	"m1Um349przPtmeHNmKELWLobelvszNrJ8NV2vr9d7p23mH8xjii/8S808y50yEtzP7+7u1GhZ8NifT7L",
	"Xc5zUwG3P4l/yH929Lv71+7Gl9AFdCBDuScfMK/ti6X8z+SBbrEpMWf78O75nzeR707ZVdd99EnEDL+I",
	"O5dbtZnbbGmV+TQM4Akze+rfU/8nT6S6e7T7hJmPJib4+NabFYkJX+/cru4szPtv36rOb/W6EKv2KO5E",
	"TFMdnZDHOb+Va5Cus5ONWHf0u//nLi3pBviXuIr8o5s2pQtbvfMd6ep2pYkpo6d3kCZSGOmffXLOHya+",
	"W6w/OsEPRIfB6Z6kNzsnDd2NF9i8O+lgOwnovJFEft6WPO5UtwW/ubvWYsE3Gr67Xpz2jG/XXrdmquJa",
	"cyn09mlLFOQUuE/bz0PUcqOZ/Qc1VkTPG6WYMOWalHK5hA7LEJn37eN3tKpLdvxtJh5o3VQo3F/IspRX",
	"XCzJi4cPTkgNhUswycgOq8kbWvKg2izk4s1xJt68eZOJekqULNlxwS6nrd6gp5AyNCXf9t7w19sMq87q",
	"Kfl2Sr49Gn3NA63z3kIuNr6ynBJYbjuiW6y9XixAwXaJUO1tvw9Yt2+/298zQUg2id7KJsfkF/sr8f+x",
	"/8sm8F02mca/teDpPbCw6v30bTbBP19Ptxy9D9rhgN2/j24xhYf5DnPY/7zOxHsHyQeuQvEG0Mdotj3g",
	"F3Lx8VaduileaabOInL+iHy7P9U+avBGTBw4Zd05Ms/NHzRmxYRxCyNZc+/e938i9lep+G+4HWx279m7",
	"3kG4z2lNc27WmL15SXlJFyULNbe1lyTaO2WTrvmEmfZFd3W+CKv6iGi4YdY9Ru4ex+qEHhUdXVK4sFin",
	"GaDsVo4NLi5pyTFU5DEKJfD7j39/SYx8y8S4b+LcTXOrKMbv//vjA/illKSiYk2oMayqjb5TRxtD/alc",
	"ysbszGquzcfgWjfBKx2OFm5QK/rZm5ULcqFkBawlWtIcBaKQ9QBssWq0ISt6iXLhm1IuuXgDjGvBS27W",
	"457sGGc+vPPWXn0nihUWYrQcjV6BPeTRex86TKVWdu+G49cA66Rlw/+CjuQvKVblqyVbljeKm/Xk+JfX",
	"G4iYixuJC5oZw8VS71akwn/lBQO/Fki9LEtMTEoJBud+uo8oBoQ5tkbuDVCOFuyB+4QJpmhJuLiQDoqX",
	"TOmdK324j/owtK8hEqR42t/wo1M790eEoZtmNxAGoPmvx2HWhfjvk4eMKqYsgtoDeG+PAECAtq1GlZPj",
	"ydHldxP7xI3Zh7GF39qs7MWiGBYUMbIvtp54Y0cwgEWizNDuOz7mI28PH47Yf3SzcR+jtpwYFp/carUk",
	"KjTghg9uwdsM25arcqP6FhU7DPqw3xqvM1TojLftkG0oXjtUFMe37TC0y1FBUeqw0zD4Nrx3OGtMIKpy",
	"kyxkY0b5aztjh7hugWzkOdCzjJG5/WnbgcFIx13ZAlqCU96+8uhhMHDXEnNbhSxiFDyTBTnPV6xoSvuB",
	"K1P8/vX7/z8AAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
