# Secret for testing
apiVersion: v1
kind: Secret
metadata:
  name: test-secret
  namespace: everest
  annotations:
    openeverest.io/is-default-components-engine: "true"
type: Opaque
stringData:
  apiKey: "very-secret"
